# -*- coding: utf-8 -*-
"""cross_validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8gSzygZLeKJqW3RdN4_BryefyRAtAQY
"""

# Core libraries
import numpy as np
import pandas as pd
from datetime import datetime
from itertools import combinations

from data_drift import build_regimes_from_clustering

# Scikit-learn utilities
from sklearn.utils import check_random_state
from sklearn.model_selection._split import BaseCrossValidator
from sklearn.base import clone

# Parallel processing
from joblib import Parallel, delayed

# Statistics
from scipy.stats import spearmanr

import matplotlib.pyplot as plt
from scipy import stats
from scipy.signal import find_peaks
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import RobustScaler

from datetime import timedelta
from itertools import combinations
from sklearn.model_selection import BaseCrossValidator
from sklearn.utils import check_random_state

from typing import List, Tuple, Optional, Union

class SlidingWindowPurgedEmbargoCV(BaseCrossValidator):
    """
    Sliding window cross-validation for time series with purge and embargo gaps.

    This cross-validator provides train/test indices to split time series data samples
    that are observed at fixed time intervals according to a sliding window scheme.
    Both training and testing windows have fixed sizes, and each fold's test set
    immediately follows its training set in time, respecting purge and embargo gaps.

    Parameters
    ----------
    train_size_n_blocks : int
        Number of blocks to include in each training set.
    test_size_n_blocks : int
        Number of blocks to include in each testing set.
    step_n_blocks : int, default=1
        Number of blocks to step forward between each fold.
    purge_gap_n_blocks : int, default=0
        Number of blocks to exclude from training that immediately precede the test set.
    embargo_gap_n_blocks : int, default=0
        Number of blocks to exclude from future training sets that immediately follow the test set.
    datetime_level : str, default='date'
        Name of datetime level in the pandas MultiIndex.
    ticker_level : str, default='ticker'
        Name of ticker level in the pandas MultiIndex.
    n_splits : int, default=None
        Maximum number of splits. If None, generate all possible splits.
    random_state : int, RandomState instance or None, default=None
        Controls the random selection of folds when n_splits is specified.
        Pass an int for reproducible output.
    """
    def __init__(self,
                 train_size_n_blocks,
                 test_size_n_blocks,
                 step_n_blocks=1,
                 purge_gap_n_blocks=0,
                 embargo_gap_n_blocks=0,
                 datetime_level='date',
                 ticker_level='ticker',
                 n_splits=None,
                 groups=None,
                 random_state=None):
        self.train_size_n_blocks = train_size_n_blocks
        self.test_size_n_blocks = test_size_n_blocks
        self.step_n_blocks = step_n_blocks
        self.purge_gap_n_blocks = purge_gap_n_blocks
        self.embargo_gap_n_blocks = embargo_gap_n_blocks
        self.datetime_level = datetime_level
        self.ticker_level = ticker_level
        self.n_splits = n_splits
        self.random_state = random_state
        self.groups=groups

    def get_n_splits(self, X=None, y=None, groups=None):
      """
      Returns the number of splitting iterations in the cross-validator.
      """
      if X is not None:
          # Use groups passed here or fall back to groups set at init
          groups_eff = groups if groups is not None else getattr(self, "groups", None)
          dates, _ = self._extract_dates(X, groups_eff)
          total_dates = len(dates)

          # Each date is a block in this implementation
          n_blocks = total_dates
      else:
          # Without X, we can't calculate number of splits; fall back to n_splits
          return self.n_splits if self.n_splits is not None else 0

      min_blocks_needed = (self.train_size_n_blocks +
                          self.purge_gap_n_blocks +
                          self.test_size_n_blocks)

      if min_blocks_needed > n_blocks:
          return 0

      possible_splits = 1 + (n_blocks - min_blocks_needed) // self.step_n_blocks

      if self.n_splits is not None:
          return min(self.n_splits, possible_splits)
      return possible_splits


    def _extract_dates(self, X, groups):
      """
      Return:
          dates_unique_sorted: np.ndarray of unique sorted dates (per-block units)
          sample_dates: np.ndarray of date per sample, same length as X
      """
      # Case 1: DataFrame with MultiIndex → use datetime level, ignore groups
      if isinstance(X, pd.DataFrame) and isinstance(X.index, pd.MultiIndex):
          sample_dates = X.index.get_level_values(self.datetime_level).to_numpy()
          dates_unique = np.unique(sample_dates)
          return dates_unique, sample_dates

      # Case 2: Any other X → require groups (from init or split)
      if groups is None:
          raise ValueError(
              "No MultiIndex present and no `groups` provided. "
              "Pass groups at init or as split(..., groups=...)."
          )

      sample_dates = np.asarray(groups)
      if sample_dates.shape[0] != len(X):
          raise ValueError("`groups` must have same length as X.")

      dates_unique = np.unique(sample_dates)
      return dates_unique, sample_dates


    def split(self, X, y=None, groups=None):

        # Use groups passed here or fall back to groups set at init
        groups_eff = groups if groups is not None else getattr(self, "groups", None)

        # Get unique dates and per-sample dates
        dates, sample_dates = self._extract_dates(X, groups_eff)
        dates = np.sort(dates)
        total_dates = len(dates)

        # Each date is a block
        n_blocks = total_dates
        block_size = 1

        # Create blocks (each date is its own block)
        blocks = [[date] for date in dates]


        # Generate all possible sliding windows
        valid_splits = []

        # Total blocks needed for each split
        min_blocks_needed = (self.train_size_n_blocks +
                            self.purge_gap_n_blocks +
                            self.test_size_n_blocks)

        # Check if we have enough blocks
        if min_blocks_needed > n_blocks:
            raise ValueError(
                f"Not enough blocks ({n_blocks}) for the requested window sizes "
                f"(train: {self.train_size_n_blocks}, purge: {self.purge_gap_n_blocks}, "
                f"test: {self.test_size_n_blocks})."
            )

        # Generate all possible sliding windows
        for start_idx in range(0, n_blocks - min_blocks_needed + 1, self.step_n_blocks):
            train_start = start_idx
            train_end = start_idx + self.train_size_n_blocks

            # Account for purge gap
            test_start = train_end + self.purge_gap_n_blocks
            test_end = test_start + self.test_size_n_blocks

            # Check if test_end exceeds n_blocks
            if test_end > n_blocks:
                break

            valid_splits.append((
                list(range(train_start, train_end)),  # Train blocks
                list(range(test_start, test_end))     # Test blocks
            ))

        if not valid_splits:
            raise ValueError(
                "Cannot create valid train-test splits with the given parameters."
            )

        # Select splits if n_splits is specified
        if self.n_splits and self.n_splits < len(valid_splits):
            rng = check_random_state(self.random_state)
            indices = rng.choice(len(valid_splits), size=self.n_splits, replace=False)
            selected_splits = [valid_splits[i] for i in indices]
        else:
            selected_splits = valid_splits

        # Apply embargo: keep track of embargooed dates for future folds
        embargooed_dates = set()

        # Process each split
        for train_blocks, test_blocks in selected_splits:
            # Get the dates for train and test
            train_dates = np.concatenate([blocks[i] for i in train_blocks])
            test_dates = np.concatenate([blocks[i] for i in test_blocks])

            # Calculate embargo blocks for future iterations
            if self.embargo_gap_n_blocks > 0:
                embargo_end = min(n_blocks, test_blocks[-1] + 1 + self.embargo_gap_n_blocks)
                embargo_blocks = list(range(test_blocks[-1] + 1, embargo_end))
                embargo_dates = np.concatenate([blocks[i] for i in embargo_blocks]) if embargo_blocks else []
                embargooed_dates.update(embargo_dates)

            # Remove embargooed dates from training
            train_dates = [d for d in train_dates if d not in embargooed_dates]

            # Skip if no training dates remain after embargo
            if len(train_dates) == 0:
                continue


            # Get indices from data using sample_dates instead of X.index
            train_mask = np.isin(sample_dates, train_dates)
            test_mask = np.isin(sample_dates, test_dates)

            train_idx = np.where(train_mask)[0]
            test_idx = np.where(test_mask)[0]


            if len(train_idx) == 0 or len(test_idx) == 0:
                continue

            yield train_idx, test_idx

import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.utils import check_random_state
from sklearn.model_selection._split import BaseCrossValidator
from itertools import combinations

class CombinatorialPurgedEmbargoCV(BaseCrossValidator):
    def __init__(self,
                 n_blocks=10,
                 test_size_n_blocks=2,
                 purge_gap_n_blocks=1,
                 embargo_gap_n_blocks=1,
                 datetime_level='date',
                 ticker_level='ticker',
                 max_splits=None,
                 groups=None,
                 random_state=None):
        self.n_blocks = n_blocks
        self.test_size_n_blocks = test_size_n_blocks
        self.purge_gap_n_blocks = purge_gap_n_blocks
        self.embargo_gap_n_blocks = embargo_gap_n_blocks
        self.datetime_level = datetime_level
        self.ticker_level = ticker_level
        self.max_splits = max_splits
        self.random_state = random_state
        self.groups = groups

    def get_n_splits(self, X=None, y=None, groups=None):
        # Number of possible ways to choose test_size_n_blocks blocks from the last n_blocks-(min_train_blocks+purge_gap) blocks
        # We'll compute this dynamically in the split method
        return self.max_splits if self.max_splits else self.n_blocks - self.test_size_n_blocks + 1


    def _extract_dates(self, X, groups):
        """Return unique dates and sample-level dates."""

        # CASE 1: DataFrame with MultiIndex → ignore groups
        if isinstance(X, pd.DataFrame) and isinstance(X.index, pd.MultiIndex):
            sample_dates = X.index.get_level_values(self.datetime_level).to_numpy()
            dates_unique = np.unique(sample_dates)
            return dates_unique, sample_dates

        # CASE 2: Use provided groups (manual or from init)
        if groups is None:
            raise ValueError(
                "No MultiIndex present and no `groups` provided. "
                "Pass groups at init or as split(..., groups=...)."
            )

        sample_dates = np.asarray(groups)
        if sample_dates.shape[0] != len(X):
            raise ValueError("groups must have same length as X.")

        dates_unique = np.unique(sample_dates)
        return dates_unique, sample_dates

    def split(self, X, y=None, groups=None):
        # groups argument overrides the init-set groups
        groups = groups if groups is not None else self.groups

        dates, sample_dates = self._extract_dates(X, groups)

        dates = X.index.get_level_values(self.datetime_level).unique()
        dates = np.sort(dates)
        total_dates = len(dates)

        block_size = total_dates // self.n_blocks
        blocks = [dates[i*block_size : (i+1)*block_size] for i in range(self.n_blocks - 1)]
        blocks.append(dates[(self.n_blocks - 1)*block_size:])

        # Generate chronologically correct splits using a sliding window approach
        valid_splits = []

        # Min train blocks is 1 (we need at least one block for training)
        min_train_blocks = 1

        # Iterate through possible test window starting positions
        # Start at min_train_blocks to ensure we have at least that many blocks for training
        for test_start_idx in range(min_train_blocks, self.n_blocks - self.test_size_n_blocks + 1):
            # End index is exclusive, so add test_size_n_blocks
            test_end_idx = test_start_idx + self.test_size_n_blocks

            # Test blocks are consecutive from start to end
            test_blocks = list(range(test_start_idx, test_end_idx))

            # All blocks before test_start_idx minus purge gap are available for training
            train_start_idx = 0
            # We exclude blocks that are within purge gap before test
            train_end_idx = max(0, test_start_idx - self.purge_gap_n_blocks)

            train_blocks = list(range(train_start_idx, train_end_idx))

            # Skip if no training blocks
            if not train_blocks:
                continue

            valid_splits.append((train_blocks, test_blocks))

        if not valid_splits:
            raise ValueError(
                "Cannot create valid train-test splits with the given parameters. "
                "Try reducing test_size_n_blocks, purge_gap_n_blocks, or increasing n_blocks."
            )

        # Select splits if max_splits is specified
        if self.max_splits and self.max_splits < len(valid_splits):
            rng = check_random_state(self.random_state)
            indices = rng.choice(len(valid_splits), size=self.max_splits, replace=False)
            selected_splits = [valid_splits[i] for i in indices]
        else:
            selected_splits = valid_splits

        # Generate train/test indices for each split
        for train_blocks, test_blocks in selected_splits:
            # Apply embargo (blocks after test)
            test_blocks_set = set(test_blocks)
            last_test_block = max(test_blocks)

            embargo_blocks = set(range(
                last_test_block + 1,
                min(self.n_blocks, last_test_block + 1 + self.embargo_gap_n_blocks)
            ))

            # Training blocks exclude test and embargo
            train_blocks = [b for b in train_blocks if b not in embargo_blocks]

            # Skip if no training blocks remain after embargo
            if not train_blocks:
                continue

            # Convert blocks to dates
            train_dates = np.concatenate([blocks[i] for i in train_blocks])
            test_dates = np.concatenate([blocks[i] for i in test_blocks])

            # Get indices from data
            index = X.index
            train_mask = index.get_level_values(self.datetime_level).isin(train_dates)
            test_mask = index.get_level_values(self.datetime_level).isin(test_dates)

            train_idx = np.where(train_mask)[0]
            test_idx = np.where(test_mask)[0]

            if len(train_idx) == 0 or len(test_idx) == 0:
                continue

            yield train_idx, test_idx


import numpy as np
import pandas as pd
from sklearn.model_selection import BaseCrossValidator

class RollingPurgedKFold(BaseCrossValidator):
    def __init__(self, n_splits=5, purge_gap=0, embargo_gap=0, datetime_level='date', ticker_level='ticker',groups=None):
        self.n_splits = n_splits
        self.purge_gap = purge_gap
        self.embargo_gap = embargo_gap
        self.datetime_level = datetime_level
        self.ticker_level = ticker_level
        self.groups=groups

    def get_n_splits(self, X=None, y=None, groups=None):
        return self.n_splits

    def _extract_dates(self, X, groups):
        """
        Return:
            dates_unique_sorted: np.ndarray of unique sorted dates
            sample_dates: np.ndarray of date per sample, same length as X
        """
        # Case 1: pandas object with MultiIndex → use datetime level, ignore groups
        if isinstance(X, (pd.DataFrame, pd.Series)) and isinstance(X.index, pd.MultiIndex):
            sample_dates = X.index.get_level_values(self.datetime_level).to_numpy()
            dates_unique = np.unique(sample_dates)
            return dates_unique, sample_dates

        # Case 2: generic array-like X → require groups (from init or split)
        if groups is None:
            raise ValueError(
                "No MultiIndex present and no `groups` provided. "
                "Pass groups at init or as split(..., groups=...)."
            )

        sample_dates = np.asarray(groups)
        if sample_dates.shape[0] != len(X):
            raise ValueError("`groups` must have same length as X.")

        dates_unique = np.unique(sample_dates)
        return dates_unique, sample_dates


    def split(self, X, y=None, groups=None):
        # Use groups provided here or fall back to groups set at init
        groups_eff = groups if groups is not None else getattr(self, "groups", None)

        # Get unique dates and per-sample dates
        dates, sample_dates = self._extract_dates(X, groups_eff)
        dates = np.sort(dates)
        n_dates = len(dates)


        usable_dates = n_dates - self.embargo_gap
        max_total_window = usable_dates // self.n_splits
        window_size = max_total_window // 2

        for i in range(self.n_splits):
            train_start = i * 2 * window_size
            train_end = train_start + window_size
            test_start = train_end + self.purge_gap
            test_end = test_start + window_size


            # Skip fold if it doesn't fit (no break!)
            # Adjust test and embargo windows to fit the dataset
            if test_end + self.embargo_gap > n_dates:
                test_end = min(test_end, n_dates)
                embargo_end = n_dates  # use only remaining dates for embargo
            else:
                embargo_end = test_end + self.embargo_gap

            train_dates = dates[train_start:train_end]
            test_dates = dates[test_start:test_end]
            embargo_dates = dates[test_end:test_end + self.embargo_gap]

            print(f"Fold {i}:")
            print(f"  Train: {train_dates[0]} to {train_dates[-1]}")
            print(f"  Test : {test_dates[0]} to {test_dates[-1]}")

            exclude_dates = np.concatenate([test_dates, embargo_dates])  # still unused, optional

            # Build masks from sample_dates instead of MultiIndex
            train_mask = np.isin(sample_dates, train_dates)
            test_mask = np.isin(sample_dates, test_dates)

            train_idx = np.where(train_mask)[0]
            test_idx = np.where(test_mask)[0]



            if len(train_idx) == 0 or len(test_idx) == 0:
                print(f"Warning: Fold {i} has empty train or test set. Skipping.")
                continue

            yield train_idx, test_idx

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.base import clone
from joblib import Parallel, delayed

def compute_fold_score(estimator, X, y, train_idx, test_idx):
    """
    Compute Spearman correlation for a single fold.

    Parameters:
    - estimator: scikit-learn compatible estimator
    - X: pd.DataFrame of features
    - y: pd.Series or array-like target values
    - train_idx: indices for training set
    - test_idx: indices for test set

    Returns:
    - Spearman correlation coefficient
    """
    # Clone estimator to ensure independence across folds
    estimator = clone(estimator)

    # Extract training and test sets using numpy arrays for efficiency
    X_train, X_test = X.values[train_idx], X.values[test_idx]
    y_train, y_test = y.values[train_idx], y.values[test_idx]

    # Fit and predict
    estimator.fit(X_train, y_train)
    y_pred = estimator.predict(X_test)

    # Compute Spearman correlation
    corr, _ = spearmanr(y_test, y_pred)
    return corr

# Example usage with your RollingPurgedKFold

def cross_val_spearman_score(estimator, X, y, cv, n_jobs=-1):
    """
    Custom cross-validation scoring using Spearman correlation with parallel processing.

    Parameters:
    - estimator: scikit-learn compatible estimator with .fit and .predict
    - X: pd.DataFrame of features
    - y: target values (array-like)
    - cv: cross-validator (e.g., RollingPurgedKFold)
    - n_jobs: int, number of parallel jobs (-1 uses all available cores)

    Returns:
    - mean Spearman correlation across folds
    - list of per-fold Spearman correlations
    """
    # Parallelize computation across folds
    scores = Parallel(n_jobs=n_jobs)(
        delayed(compute_fold_score)(estimator, X, y, train_idx, test_idx)
        for train_idx, test_idx in cv.split(X, y)
    )

    return np.mean(scores), scores

def create_regime_feats(df_input):

    df = df_input.copy()

    if 'date' not in df.index.names and 'date' in df.index:
      df=df.set_index(['ticker','date'])

    # Convert all column names to lowercase for consistent access
    df.columns = df.columns.str.lower()

    # Sort the DataFrame by Date
    df.sort_index(inplace=True)

    # 1. Log Returns
    df['log_returns'] = df['close'].apply(lambda x: np.log(x)).diff()

    # 2. Historical Volatility (Rolling Standard Deviation of Log Returns)
    # Using a 21-day window (approx. one trading month)
    df['historical_volatility_21d'] = df['log_returns'].rolling(window=21).std() * np.sqrt(252) # Annualized

    # 3. Day's Range
    df['day_range'] = df['high'] - df['low']

    # 4. Bollinger Bands (20-day Moving Average, 2 Standard Deviations)
    window = 20
    df['bb_middle_band'] = df['close'].rolling(window=window).mean()
    df['bb_upper_band'] = df['bb_middle_band'] + (df['close'].rolling(window=window).std() * 2)
    df['bb_lower_band'] = df['bb_middle_band'] - (df['close'].rolling(window=window).std() * 2)
    df['bb_width'] = df['bb_upper_band'] - df['bb_lower_band']

    # 5. Moving Averages
    df['ma_50'] = df['close'].rolling(window=50).mean()
    df['ma_200'] = df['close'].rolling(window=200).mean()

    # 6. Skewness and Kurtosis of Log Returns
    # Using a 21-day window
    df['rolling_skewness_21d'] = df['log_returns'].rolling(window=21).skew()
    df['rolling_kurtosis_21d'] = df['log_returns'].rolling(window=21).kurt()

    # 7. Maximum Drawdown (Rolling)
    # This is a bit more complex for a rolling window, as it needs to track the peak.
    # Let's calculate the cumulative returns first to apply rolling drawdown.
    df['cumulative_returns'] = (1 + df['log_returns']).cumprod() - 1
    df['rolling_max_252d'] = df['cumulative_returns'].rolling(window=252, min_periods=1).max()
    df['rolling_drawdown_252d'] = df['cumulative_returns'] / df['rolling_max_252d'] - 1

    # List of engineered columns to return
    engineered_columns = [
        'log_returns',
        'historical_volatility_21d',
        'day_range',
        'bb_middle_band',
        'bb_upper_band',
        'bb_lower_band',
        'bb_width',
        'ma_50',
        'ma_200',
        'rolling_skewness_21d',
        'rolling_kurtosis_21d',
        'cumulative_returns',
        'rolling_max_252d',
        'rolling_drawdown_252d'
    ]

    return df[engineered_columns]

from datetime import timedelta
from itertools import combinations

import numpy as np
import pandas as pd
from sklearn.model_selection import BaseCrossValidator
from sklearn.utils import check_random_state


class RegimePurgedEmbargoCV(BaseCrossValidator):
    """
    Regime-based cross-validation with purge and embargo periods.

    Takes a list of regime definitions (regime_id, start_date, end_date) and generates
    temporally valid train/test splits where test regimes always come after train regimes.

    Parameters
    ----------
    regimes : list of tuples
        List of (regime_id, start_date_str, end_date_str) defining the regimes
    purge_period : int, default=1
        Number of **time steps** (unique dates in X) to purge before test periods start
    embargo_period : int, default=1
        Number of **time steps** to embargo at the start of test periods
    datetime_level : str, default='date'
        Name of datetime level in the pandas MultiIndex
    ticker_level : str, default='ticker'
        Name of ticker level in the pandas MultiIndex
    max_test_regimes : int, default=3
        Maximum number of regimes to use in a single test set
    max_splits : int or None
        Maximum number of splits to use
    optimize_training_data : bool, default=True
        If True, optimize split selection to maximize training data while ensuring test coverage
    random_state : int, RandomState instance or None, default=None
        Controls random selection when max_splits is specified and optimize_training_data=False
    """

    def __init__(self,
                 regimes,
                 purge_period=1,
                 embargo_period=1,
                 datetime_level='date',
                 ticker_level='ticker',
                 max_test_regimes=3,
                 max_splits=None,
                 optimize_training_data=True,
                 random_state=None):
        self.regimes = regimes
        self.purge_period = purge_period
        self.embargo_period = embargo_period
        self.datetime_level = datetime_level
        self.ticker_level = ticker_level
        self.max_test_regimes = max_test_regimes
        self.max_splits = max_splits
        self.optimize_training_data = optimize_training_data
        self.random_state = random_state

        # Process regimes on initialization
        self.processed_regimes = self._postprocess_regimes()
        self.valid_splits = self._generate_valid_splits()

    def _postprocess_regimes(self):
        """
        Remove temporal overlaps from regimes, keeping earliest start dates.
        """
        regime_data = []
        for regime_id, start_str, end_str in self.regimes:
            regime_data.append({
                'regime_id': regime_id,
                'start_date': pd.to_datetime(start_str),
                'end_date': pd.to_datetime(end_str)
            })

        regime_data.sort(key=lambda x: x['start_date'])

        processed = []
        for regime in regime_data:
            current = regime.copy()

            for prev in processed:
                if current['start_date'] <= prev['end_date']:
                    # Overlap detected - adjust current start date
                    current['start_date'] = prev['end_date'] + timedelta(days=1)

            if current['start_date'] < current['end_date']:
                processed.append(current)

        return processed

    def _generate_valid_splits(self):
        """
        Generate all temporally valid train/test combinations.
        Test regimes must come after train regimes.
        """
        valid_splits = []
        n_regimes = len(self.processed_regimes)

        for split_point in range(1, n_regimes):
            train_candidates = self.processed_regimes[:split_point]
            test_candidates = self.processed_regimes[split_point:]

            for test_size in range(1, min(self.max_test_regimes + 1,
                                          len(test_candidates) + 1)):
                for test_regimes in combinations(test_candidates, test_size):
                    train_data_size = self._calculate_train_data_size(
                        train_candidates, test_regimes
                    )
                    valid_splits.append({
                        'train_regimes': train_candidates,
                        'test_regimes': list(test_regimes),
                        'split_point': split_point,
                        'train_data_size': train_data_size
                    })

        return valid_splits

    def _calculate_train_data_size(self, train_regimes, test_regimes):
        """
        Rough estimate of training duration in days for a given split.

        This is only used for ranking splits; it still uses calendar days.
        """
        total_days = 0
        first_test_start = min(regime['start_date'] for regime in test_regimes)

        for regime in train_regimes:
            train_start = regime['start_date']
            train_end = min(
                regime['end_date'],
                first_test_start - timedelta(days=self.purge_period + 1)
            )
            if train_start <= train_end:
                total_days += (train_end - train_start).days + 1

        return total_days

    def _optimize_split_selection(self, all_splits, max_splits):
        """
        Select splits that maximize training data while ensuring comprehensive test coverage.
        """
        if len(all_splits) <= max_splits:
            return all_splits

        all_test_regimes = {r['regime_id'] for r in self.processed_regimes}
        selected_splits = []
        covered_regimes = set()

        remaining_splits = sorted(
            all_splits,
            key=lambda x: x['train_data_size'],
            reverse=True
        )

        # Phase 1: cover each regime at least once
        for regime_id in all_test_regimes:
            if len(selected_splits) >= max_splits:
                break

            best_split = None
            best_idx = -1

            for i, split in enumerate(remaining_splits):
                test_regime_ids = {r['regime_id'] for r in split['test_regimes']}
                if regime_id not in test_regime_ids:
                    continue

                new_coverage = test_regime_ids - covered_regimes
                if new_coverage:
                    best_split = split
                    best_idx = i
                    break

            if best_split is not None:
                selected_splits.append(best_split)
                covered_regimes.update({r['regime_id'] for r in best_split['test_regimes']})
                remaining_splits.pop(best_idx)

        # Phase 2: fill remaining with best training data splits
        remaining_slots = max_splits - len(selected_splits)
        if remaining_slots > 0:
            remaining_splits.sort(
                key=lambda x: (
                    x['train_data_size'],
                    -x['split_point'],
                    len(x['test_regimes'])
                ),
                reverse=True
            )
            selected_splits.extend(remaining_splits[:remaining_slots])

        return selected_splits

    def get_n_splits(self, X=None, y=None, groups=None):
        if self.max_splits is not None:
            return min(self.max_splits, len(self.valid_splits))
        return len(self.valid_splits)

    def _get_groups_array(self, X, groups):
        """
        Normalize 'time' info into a 1D array of python dates, agnostic
        to frequency (daily/weekly/etc.).

        - If X is a pandas object with a MultiIndex containing datetime_level,
          we ignore 'groups' and derive them from the index.
        - Otherwise, we require a 'groups' array with datetime-like values.
        """
        if isinstance(X, (pd.DataFrame, pd.Series)) and isinstance(X.index, pd.MultiIndex):
            if self.datetime_level not in X.index.names:
                raise ValueError(
                    f"datetime_level '{self.datetime_level}' not found in index names: {X.index.names}"
                )
            idx_dates = pd.to_datetime(X.index.get_level_values(self.datetime_level))
            return np.array([d.date() for d in idx_dates])

        if groups is None:
            raise ValueError(
                "When X is not a pandas object with a MultiIndex datetime index, "
                "you must pass 'groups' as a datetime-like array aligned with X."
            )

        groups = np.asarray(groups)
        if groups.shape[0] != len(X):
            raise ValueError(
                f"'groups' must have the same length as X; "
                f"got len(groups)={groups.shape[0]}, len(X)={len(X)}."
            )

        grp_dt = pd.to_datetime(groups)
        return np.array([d.date() for d in grp_dt])

    def split(self, X, y=None, groups=None):
        """
        Generate indices to split data into training and test sets.

        Supports:
          - pandas DataFrame/Series with MultiIndex (ticker, date-like)
          - NumPy arrays, when a datetime-like 'groups' array is provided

        Datetime frequency (daily, weekly, etc.) is handled by comparing
        date *boundaries* against these groups. Purge/embargo are in units
        of unique time steps (e.g., 1 = one bar, daily or weekly).
        """
        # 1) per-sample date array
        groups_dates = self._get_groups_array(X, groups)
        n_samples = len(groups_dates)

        # 1b) unique sorted dates = time steps
        unique_dates = np.unique(groups_dates)
        unique_dates.sort()
        unique_dates_np = np.array(unique_dates)

        # helper to map regime timestamps to indices in unique_dates
        def _left_pos(ts):
            d = ts.date()
            i = unique_dates_np.searchsorted(d, side="left")
            if i >= len(unique_dates_np):
                return None
            return i

        def _right_pos(ts):
            d = ts.date()
            j = unique_dates_np.searchsorted(d, side="right") - 1
            if j < 0:
                return None
            return j

        # 2) choose which regime splits to use
        splits_to_use = self.valid_splits
        if self.max_splits and self.max_splits < len(self.valid_splits):
            if self.optimize_training_data:
                splits_to_use = self._optimize_split_selection(
                    self.valid_splits, self.max_splits
                )
            else:
                rng = check_random_state(self.random_state)
                indices = rng.choice(
                    len(self.valid_splits),
                    size=self.max_splits,
                    replace=False
                )
                splits_to_use = [self.valid_splits[i] for i in indices]

        # 3) map regime date ranges -> masks
        for split_info in splits_to_use:
            train_regimes = split_info['train_regimes']
            test_regimes = split_info['test_regimes']

            if not train_regimes or not test_regimes:
                continue

            # earliest test start (in index units)
            first_test_start_ts = min(r['start_date'] for r in test_regimes)
            first_test_start_idx = _left_pos(first_test_start_ts)
            if first_test_start_idx is None:
                continue

            train_mask = np.zeros(n_samples, dtype=bool)
            test_mask = np.zeros(n_samples, dtype=bool)

            # ---- TRAIN MASK (purge vs first test start, frequency-aware) ----
            for regime in train_regimes:
                r_start_idx = _left_pos(regime['start_date'])
                r_end_idx = _right_pos(regime['end_date'])
                if r_start_idx is None or r_end_idx is None:
                    continue

                # training ends purge_period steps before first test start
                max_train_end_idx = first_test_start_idx - (self.purge_period + 1)
                train_end_idx = min(r_end_idx, max_train_end_idx)

                if r_start_idx <= train_end_idx:
                    start_d = unique_dates[r_start_idx]
                    end_d = unique_dates[train_end_idx]
                    train_mask |= (
                        (groups_dates >= start_d) &
                        (groups_dates <= end_d)
                    )

            # ---- TEST MASK (embargo/purge around regime bounds, frequency-aware) ----
            for regime in test_regimes:
                r_start_idx = _left_pos(regime['start_date'])
                r_end_idx = _right_pos(regime['end_date'])
                if r_start_idx is None or r_end_idx is None:
                    continue

                # embargo shifts start forward by embargo_period steps
                test_start_idx = r_start_idx + self.embargo_period
                # purge shifts end backward by purge_period steps
                test_end_idx = r_end_idx - self.purge_period

                if test_start_idx <= test_end_idx:
                    start_d = unique_dates[test_start_idx]
                    end_d = unique_dates[test_end_idx]
                    test_mask |= (
                        (groups_dates >= start_d) &
                        (groups_dates <= end_d)
                    )

            if not train_mask.any() or not test_mask.any():
                continue

            train_idx = np.where(train_mask)[0]
            test_idx = np.where(test_mask)[0]

            if len(train_idx) == 0 or len(test_idx) == 0:
                continue

            yield train_idx, test_idx

from dataclasses import dataclass
from datetime import timedelta
from typing import Iterable, List, Tuple, Dict, Optional, Any, Sequence

import numpy as np
import pandas as pd
from sklearn.model_selection import BaseCrossValidator

@dataclass(frozen=True)
class RegimeDefinition:
    """Container for a single regime.

    Parameters
    ----------
    regime_id : Any
        Identifier for the regime (int, str, etc.).
    start_date : pd.Timestamp
        Inclusive start date of the regime.
    end_date : pd.Timestamp
        Inclusive end date of the regime.
    """

    regime_id: Any
    start_date: pd.Timestamp
    end_date: pd.Timestamp

    @classmethod
    def from_any(cls, raw: Any) -> "RegimeDefinition":
        """Build from a tuple or dict.

        Accepts:
        - (regime_id, start, end)
        - {"regime_id": ..., "start_date": ..., "end_date": ...}
        where dates are anything `pd.to_datetime` can parse.
        """

        if isinstance(raw, dict):
            rid = raw.get("regime_id")
            start = raw.get("start_date")
            end = raw.get("end_date")
        else:
            if len(raw) != 3:
                raise ValueError(
                    "Regime tuple must be (regime_id, start_date, end_date). "
                    f"Got: {raw!r}"
                )
            rid, start, end = raw

        start_ts = pd.to_datetime(start)
        end_ts = pd.to_datetime(end)

        if pd.isna(start_ts) or pd.isna(end_ts):
            raise ValueError(f"Invalid start/end date in regime {raw!r}")
        if start_ts > end_ts:
            raise ValueError(
                f"Regime start_date must be <= end_date. Got {start_ts} > {end_ts}"
            )

        return cls(regime_id=rid, start_date=start_ts, end_date=end_ts)


class BalancedRegimePurgedEmbargoCV(BaseCrossValidator):
    """Regime-based time-series CV with purge + (optional) embargo and
    **balanced** train/test sizes.

    This cross-validator:

    1. Takes *regime* definitions (id, start_date, end_date).
    2. Generates all temporally valid combinations where test regimes are
       strictly after training regimes.
    3. Applies a purge period before the first test regime, removing the
       last `purge_period` days from the *end* of the training region.
    4. Scores each split by how close its train/test length ratio is to
       a target ratio.
    5. Keeps only the `max_splits` most balanced splits.

    Notes
    -----
    - Regimes are defined in *calendar days*; your actual data can be
      daily, weekly, etc. Dates are filtered via inequalities against the
      datetime level in the MultiIndex when the **ordering is first inferred**.
    - After the first call to `split` with a pandas object that has the
      datetime level, this class caches:
         * `self._dates_`  – per-row timestamps
         * `self._groups_` – per-row regime IDs
      and you can subsequently call `split` with numpy arrays (or any
      array-like) of the same length, without needing the index.

    Parameters
    ----------
    regimes : Sequence[tuple | dict]
        Iterable of regime definitions. Each element is either
        `(regime_id, start_date, end_date)` or a dict with keys
        `{"regime_id", "start_date", "end_date"}`.
    purge_period : int, default 1
        Number of **calendar days** to remove from the training region
        immediately before the *first* test regime's start date.
    embargo_period : int, default 1
        Number of **calendar days** after each test regime's end date
        that are excluded from training.
    datetime_level : str, default "date"
        Name of the datetime level in the pandas MultiIndex.
    ticker_level : str, default "ticker"
        Name of the ticker level (unused in the splitting logic but
        validated for clarity).
    max_test_regimes : int, default 3
        Maximum number of regimes included in a single test fold.
    max_splits : int, default 10
        Maximum number of folds to keep (the most balanced ones).
    target_train_test_ratio : float or None, default None
        Desired train/test size ratio (in **days**). If None, the median
        ratio of all valid regime combinations is used as the target.
    """

    def __init__(
        self,
        regimes: Sequence[Any],
        purge_period: int = 1,
        embargo_period: int = 1,
        datetime_level: str = "date",
        ticker_level: str = "ticker",
        max_test_regimes: int = 3,
        max_splits: int = 10,
        target_train_test_ratio: Optional[float] = None,
    ) -> None:
        self.regimes_raw = list(regimes)
        self.purge_period = int(purge_period)
        self.embargo_period = int(embargo_period)
        self.datetime_level = datetime_level
        self.ticker_level = ticker_level
        self.max_test_regimes = int(max_test_regimes)
        self.max_splits = int(max_splits) if max_splits is not None else None
        self.target_train_test_ratio = (
            float(target_train_test_ratio)
            if target_train_test_ratio is not None
            else None
        )

        # Normalised regimes
        self.processed_regimes: List[RegimeDefinition] = self._postprocess_regimes()

        # All valid temporal splits (before pruning)
        self._all_splits: List[Dict[str, Any]] = self._generate_all_splits()
        if not self._all_splits:
            raise ValueError("No valid regime splits could be generated.")

        # Prune to the most balanced ones
        if self.max_splits is not None and self.max_splits < len(self._all_splits):
            self._selected_splits = self._select_most_balanced_splits(
                self._all_splits, self.max_splits
            )
        else:
            self._selected_splits = list(self._all_splits)

        # --- NEW: internal cache so we can work with numpy arrays ---
        self._dates_: Optional[pd.DatetimeIndex] = None  # per-sample timestamps
        self._groups_: Optional[np.ndarray] = None        # per-sample regime_id
        self._n_samples_: Optional[int] = None

    # ------------------------------------------------------------------
    # Regime preparation
    # ------------------------------------------------------------------
    def _postprocess_regimes(self) -> List[RegimeDefinition]:
        """Normalise and de-overlap regimes.

        Overlaps are removed by *pushing forward* the start date of later
        regimes so they begin the day after the previous regime's end.
        Regimes that end up with non-positive duration are dropped.
        """

        if not self.regimes_raw:
            raise ValueError("`regimes` must be a non-empty sequence.")

        # Convert everything into RegimeDefinition objects
        regime_objs = [RegimeDefinition.from_any(r) for r in self.regimes_raw]

        # Sort by start date
        regime_objs.sort(key=lambda r: r.start_date)

        processed: List[RegimeDefinition] = []
        for reg in regime_objs:
            start, end = reg.start_date, reg.end_date

            # Adjust start to avoid overlaps with previous regimes
            for prev in processed:
                if start <= prev.end_date:
                    start = prev.end_date + timedelta(days=1)

            if start <= end:
                processed.append(
                    RegimeDefinition(
                        regime_id=reg.regime_id,
                        start_date=start,
                        end_date=end,
                    )
                )

        if not processed:
            raise ValueError("All regimes were filtered out after overlap removal.")

        return processed

    # ------------------------------------------------------------------
    # Split generation + scoring (regime-level, independent of X)
    # ------------------------------------------------------------------
    @staticmethod
    def _regime_duration_days(reg: RegimeDefinition) -> int:
        return int((reg.end_date - reg.start_date).days) + 1

    def _calculate_train_data_size(
        self,
        train_candidates: Sequence[RegimeDefinition],
        test_regimes: Sequence[RegimeDefinition],
    ) -> int:
        """Total training days for a candidate split.

        Training regimes are truncated so that they end `purge_period`
        days before the *earliest* test regime starts.
        """

        if not train_candidates or not test_regimes:
            return 0

        first_test_start = min(r.start_date for r in test_regimes)

        total_days = 0
        for reg in train_candidates:
            train_start = reg.start_date
            # Last inclusive train day after applying purge
            train_end = min(
                reg.end_date,
                first_test_start - timedelta(days=self.purge_period + 1),
            )
            if train_start <= train_end:
                total_days += int((train_end - train_start).days) + 1

        return total_days

    def _calculate_test_data_size(
        self, test_regimes: Sequence[RegimeDefinition]
    ) -> int:
        """Total number of test days for a candidate split."""
        return sum(self._regime_duration_days(reg) for reg in test_regimes)

    def _generate_all_splits(self) -> List[Dict[str, Any]]:
        """Enumerate all temporally valid train/test combinations.

        For a split point `k`, regimes `[0..k-1]` are *candidates* for
        training and `[k..end]` are *candidates* for testing. Test regimes
        are chosen as consecutive combinations starting at some index
        ≥ `k`, up to `max_test_regimes` in size.
        """

        regs = self.processed_regimes
        n = len(regs)

        if n < 2:
            # Need at least one train regime and one test regime
            return []

        all_splits: List[Dict[str, Any]] = []

        for split_point in range(1, n):
            train_candidates = regs[:split_point]
            test_candidates = regs[split_point:]

            max_test = min(self.max_test_regimes, len(test_candidates))
            for test_size in range(1, max_test + 1):
                # consecutive test regimes
                for start_idx in range(0, len(test_candidates) - test_size + 1):
                    test_regimes = test_candidates[start_idx : start_idx + test_size]

                    train_days = self._calculate_train_data_size(
                        train_candidates, test_regimes
                    )
                    if train_days <= 0:
                        continue

                    test_days = self._calculate_test_data_size(test_regimes)
                    if test_days <= 0:
                        continue

                    all_splits.append(
                        {
                            "train_regimes": list(train_candidates),
                            "test_regimes": list(test_regimes),
                            "split_point": split_point,
                            "train_days": int(train_days),
                            "test_days": int(test_days),
                        }
                    )

        return all_splits

    def _select_most_balanced_splits(
        self, all_splits: Sequence[Dict[str, Any]], max_splits: int
    ) -> List[Dict[str, Any]]:
        """Select up to `max_splits` splits whose train/test ratio is
        closest to `target_train_test_ratio` (in log space)."""

        if len(all_splits) <= max_splits:
            return list(all_splits)

        train_days_arr = np.array([s["train_days"] for s in all_splits], dtype=float)
        test_days_arr = np.array([s["test_days"] for s in all_splits], dtype=float)

        # Avoid division-by-zero (shouldn't happen because we filter > 0)
        test_days_arr = np.maximum(test_days_arr, 1.0)

        ratios = train_days_arr / test_days_arr

        if self.target_train_test_ratio is not None:
            target = float(self.target_train_test_ratio)
        else:
            # Use median observed ratio as target if none provided
            target = float(np.median(ratios))

        # Enforce sane limits on target
        if not np.isfinite(target) or target <= 0:
            target = 1.0

        balance_scores = np.abs(np.log(ratios / target))
        order = np.argsort(balance_scores)

        selected = [all_splits[i] for i in order[:max_splits]]
        return selected

    # ------------------------------------------------------------------
    # NEW: internal dates/groups cache, to allow numpy inputs later
    # ------------------------------------------------------------------
    def _ensure_dates_and_groups(self, X: Any) -> None:
        """
        Ensure that self._dates_ and self._groups_ are populated.

        First call must provide a pandas object with a MultiIndex that
        includes `datetime_level`, so we can infer ordering and regimes.

        Subsequent calls can pass numpy arrays (or anything with len(X)),
        as long as the length matches the cached `_n_samples_`.
        """
        n_samples = len(X)

        # If already cached, just sanity-check length
        if self._dates_ is not None:
            if n_samples != self._n_samples_:
                raise ValueError(
                    f"Length mismatch: previous data length was {self._n_samples_}, "
                    f"but new X has length {n_samples}. "
                    "To reuse this CV with a different ordering/length, "
                    "you need a new BalancedRegimePurgedEmbargoCV instance."
                )
            return

        # No cache yet: we must infer from a pandas index
        if not isinstance(X, (pd.DataFrame, pd.Series)):
            raise ValueError(
                "First call to `split` for BalancedRegimePurgedEmbargoCV must be "
                "with a pandas DataFrame/Series whose index has a datetime level "
                f"named '{self.datetime_level}'. After that, you can pass numpy "
                "arrays of the same length."
            )

        index = X.index
        if not isinstance(index, pd.MultiIndex):
            raise ValueError(
                "When inferring dates/groups, X.index must be a MultiIndex "
                "with at least a datetime level."
            )
        if self.datetime_level not in index.names:
            raise ValueError(
                f"datetime_level '{self.datetime_level}' not found in index names: "
                f"{index.names}"
            )

        # Per-row timestamps
        dates = pd.to_datetime(index.get_level_values(self.datetime_level))
        self._dates_ = pd.DatetimeIndex(dates)
        self._n_samples_ = n_samples

        # Per-row regime id (group) — this is the "internal groups" array
        groups = np.full(n_samples, fill_value=None, dtype=object)
        for reg in self.processed_regimes:
            mask = (self._dates_ >= reg.start_date) & (self._dates_ <= reg.end_date)
            groups[mask] = reg.regime_id
        self._groups_ = groups

    def get_groups(self) -> Optional[np.ndarray]:
        """
        Return the cached per-sample regime IDs (or None if not initialised yet).

        This is equivalent to the `groups` vector you would otherwise have to
        build and pass manually to `.split(groups=...)`.
        """
        return self._groups_

    # ------------------------------------------------------------------
    # scikit-learn API
    # ------------------------------------------------------------------
    def get_n_splits(self, X: Any = None, y: Any = None, groups: Any = None) -> int:
        return len(self._selected_splits)

    def split(self, X: Any, y: Any = None, groups: Any = None):
        """Yield train/test index arrays for each selected split.

        Parameters
        ----------
        X : array-like or pandas object
            - On the **first** call, must be a pandas DataFrame/Series with a
              MultiIndex containing `datetime_level`, so that we can infer the
              temporal ordering and map rows to regimes.
            - On **subsequent** calls, can be a numpy array (or any array-like)
              of the same length; the cached dates/groups will be reused.
        """

        # Make sure we have per-row dates & groups cached
        self._ensure_dates_and_groups(X)

        dates = self._dates_
        n_samples = self._n_samples_
        idx_positions = np.arange(n_samples)

        for split_info in self._selected_splits:
            train_regimes: List[RegimeDefinition] = split_info["train_regimes"]
            test_regimes: List[RegimeDefinition] = split_info["test_regimes"]

            # 1) Build test mask
            test_mask = np.zeros(n_samples, dtype=bool)
            for reg in test_regimes:
                mask = (dates >= reg.start_date) & (dates <= reg.end_date)
                test_mask |= mask

            if not test_mask.any():
                continue

            # 2) Build train mask with purge before earliest test
            first_test_start = min(r.start_date for r in test_regimes)
            train_mask = np.zeros(n_samples, dtype=bool)

            for reg in train_regimes:
                train_start = reg.start_date
                train_end = min(
                    reg.end_date,
                    first_test_start - timedelta(days=self.purge_period + 1),
                )
                if train_start > train_end:
                    continue
                mask = (dates >= train_start) & (dates <= train_end)
                train_mask |= mask

            # 3) Apply embargo after each test regime (if any)
            if self.embargo_period > 0:
                embargo_mask = np.zeros(n_samples, dtype=bool)
                for reg in test_regimes:
                    emb_start = reg.end_date + timedelta(days=1)
                    emb_end = emb_start + timedelta(days=self.embargo_period)
                    mask = (dates >= emb_start) & (dates <= emb_end)
                    embargo_mask |= mask

                train_mask &= ~embargo_mask

            # Final indices
            train_idx = idx_positions[train_mask]
            test_idx = idx_positions[test_mask]

            if len(train_idx) == 0 or len(test_idx) == 0:
                continue

            yield train_idx, test_idx

import numpy as np
import pandas as pd

def derive_spearman_eigenvector_matrix(
    df: pd.DataFrame,
    ticker_level: str = "ticker",
    date_level: str = "date",
    value_cols=None,
    use_abs: bool = True,
    scale_by_eigenvalue: bool = False,
) -> pd.DataFrame:
    """
    For each date, compute the Spearman correlation matrix between tickers
    using the feature vectors at that date, then extract the leading eigenvector.

    Assumes df has a MultiIndex with levels including `ticker_level` and `date_level`,
    and columns are features.

    For each date:
        - Take sub-DF of shape (n_tickers, n_features)
        - Compute corr = sub.T.corr('spearman')  -> (n_tickers x n_tickers)
        - Compute leading eigenvector of corr
    Stack these eigenvectors into a DataFrame of shape (n_dates, n_tickers).

    Parameters
    ----------
    df : pd.DataFrame
        MultiIndex DataFrame indexed by (ticker, date) in some order.
    ticker_level : str, default "ticker"
        Name of the ticker index level.
    date_level : str, default "date"
        Name of the date index level.
    value_cols : list or None, default None
        List of feature columns to use. If None, all numeric columns are used.
    use_abs : bool, default True
        Take absolute value of eigenvector components (since sign is arbitrary).
    scale_by_eigenvalue : bool, default False
        If True, scale the eigenvector by its leading eigenvalue.

    Returns
    -------
    pd.DataFrame
        Index: dates
        Columns: union of all tickers seen across dates
        Values: leading eigenvector loadings per (date, ticker).
        Missing ticker on a date ⇒ NaN.
    """
    if not isinstance(df.index, pd.MultiIndex):
        raise ValueError("df must have a MultiIndex with ticker and date levels.")

    if ticker_level not in df.index.names or date_level not in df.index.names:
        raise ValueError(
            f"MultiIndex must contain levels '{ticker_level}' and '{date_level}'. "
            f"Got levels: {df.index.names}"
        )

    # Choose feature columns
    if value_cols is None:
        value_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    else:
        missing = set(value_cols) - set(df.columns)
        if missing:
            raise ValueError(f"value_cols missing in df.columns: {missing}")

    # Sort for stable grouping
    df = df.sort_index(level=[date_level, ticker_level])

    results = []

    # Group by date; each `sub` has rows = tickers, columns = features
    for date, sub in df.groupby(level=date_level):
        # Keep only feature columns
        sub = sub[value_cols]

        # Drop rows/cols that are all NaN
        sub = sub.dropna(how="all", axis=0)  # drop tickers with no data
        sub = sub.dropna(how="all", axis=1)  # drop features with no data

        # Need at least 2 tickers and 2 features to get a meaningful correlation
        if sub.shape[0] < 2 or sub.shape[1] < 2:
            continue

        # sub: (n_tickers, n_features)
        # We want corr between tickers using features as observations:
        #   variables = tickers, observations = features
        # => sub.T: (n_features, n_tickers), corr() along columns => (n_tickers x n_tickers)
        corr = sub.T.corr(method="spearman")

        # Drop tickers with entirely NaN correlations (degenerate)
        corr = corr.dropna(axis=0, how="all").dropna(axis=1, how="all")
        if corr.shape[0] < 2:
            continue

        C = corr.values.astype(float)

        # Handle any remaining NaNs in corr
        if np.isnan(C).any():
            # Set diagonal to 1, off-diagonal NaNs -> 0
            np.fill_diagonal(C, 1.0)
            C = np.nan_to_num(C, nan=0.0)

        # Symmetric matrix: use eigh
        eigenvals, eigenvecs = np.linalg.eigh(C)
        idx_max = np.argmax(eigenvals)
        leading_vec = eigenvecs[:, idx_max]

        if use_abs:
            leading_vec = np.abs(leading_vec)

        if scale_by_eigenvalue:
            leading_vec = leading_vec * eigenvals[idx_max]

        tickers = corr.index
        s = pd.Series(leading_vec, index=tickers, name=date)
        results.append(s)

    if not results:
        return pd.DataFrame()

    # Stack into DataFrame: rows = dates, columns = union of tickers
    if not results:
        return pd.DataFrame()

    # Stack into DataFrame, aligning by ticker (columns) and stacking by date (rows)
    # The index names (dates) and Series index (tickers) will be used correctly.
    out = pd.concat(results, axis=0)

    # Since `results` is a list of Series, pd.concat(..., axis=0) will result in a
    # Series with a MultiIndex of (date, ticker). We need to unstack to get
    # the final (date x ticker) DataFrame.
    out = out.unstack(level=-1)

    # Sort by date
    out = out.sort_index()
    return out.T

def create_cv_object(X,purge_period=45,embargo_period=45,max_splits=10):

  eigvec_df=derive_spearman_eigenvector_matrix(X)
  results=build_regimes_from_clustering(eigvec_df.fillna(-1),10,'auto')

  cv = BalancedRegimePurgedEmbargoCV(
    regimes=results,
    purge_period=purge_period,
    embargo_period=embargo_period,
    datetime_level="date",
    ticker_level="ticker",
    max_test_regimes=2,          # up to 2 regimes per test fold
    max_splits=max_splits,               # keep the 10 most balanced splits
    target_train_test_ratio=3  # aim for 3:1 train:test (in days); or None for auto
    )

  return cv