# -*- coding: utf-8 -*-
"""data_generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhBT9PYXx4Bl0_3PqPhQh7il1THLiB6q
"""

from __future__ import annotations
import pandas as pd
from functools import wraps


api_key='merp'

def convert_df_index(df):
    """
    Converts the second level of a MultiIndex to string-formatted dates (YYYY-MM-DD).

    Parameters:
    - df: pandas DataFrame with a MultiIndex, where the second level is datetime-like.

    Returns:
    - A new DataFrame with the second index level converted to strings.
    """
    if not isinstance(df.index, pd.MultiIndex):
        raise ValueError("DataFrame does not have a MultiIndex.")

    # Convert second level of index
    new_index = df.index.set_levels(
        df.index.levels[1].strftime("%Y-%m-%d"),
        level=1
    )
    df.index = new_index
    return df


def check_format(func):
    """
    A decorator to ensure input and output DataFrames have a specific
    MultiIndex format with 'ticker' and 'date' as index levels.

    The decorator handles:
    1. Converting 'date' column/index level to string type in the input.
    2. Ensuring the input DataFrame to the wrapped function has a
       MultiIndex of ['ticker', 'date'], setting it if necessary from columns.
    3. Ensuring the returned DataFrame from the wrapped function has a
       MultiIndex of ['ticker', 'date'], setting it if necessary from columns
       or returning it directly if already correctly indexed.
    """
    @wraps(func)
    def wrapper(X: pd.DataFrame, *args, **kwargs):
        # Create a copy to avoid modifying the original DataFrame in place
        X_copy = X.copy()

        # --- Part 1: Prepare the input DataFrame (X_copy) for the wrapped function ---

        # Handle 'date' conversion for input: ensure 'date' is string type
        if 'date' in X_copy.columns:
            X_copy['date'] = X_copy['date'].astype(str)
        elif 'date' in X_copy.index.names:
            # Get the index of the 'date' level
            date_level_idx = X_copy.index.names.index('date')
            # Get the current levels of the 'date' index
            current_date_levels = X_copy.index.levels[date_level_idx]
            # Convert them to string type
            new_date_levels = current_date_levels.astype(str)
            # Only update if the levels have actually changed to avoid unnecessary operations
            if not current_date_levels.equals(new_date_levels):
                X_copy.index = X_copy.index.set_levels(new_date_levels, level='date')

        # Check if X_copy already has the desired MultiIndex ('ticker', 'date')
        is_input_already_multiindex = isinstance(X_copy.index, pd.MultiIndex) and X_copy.index.names == ['ticker', 'date']

        # If the input is not already correctly multi-indexed, try to set it
        if not is_input_already_multiindex:
            if 'ticker' in X_copy.columns and 'date' in X_copy.columns:
                # If 'ticker' and 'date' are columns, set them as the MultiIndex
                X_copy.set_index(['ticker', 'date'], inplace=True)
            else:
                # If the required columns/index levels are not present,
                # the input cannot be formatted as expected by the wrapped function.
                raise ValueError(
                    "Input DataFrame must have 'ticker' and 'date' as columns "
                    "or as a MultiIndex with names ['ticker', 'date']."
                )

        # --- Part 2: Call the original function with the prepared DataFrame ---
        result_df = func(X_copy, *args, **kwargs)

        # --- Part 3: Ensure the returned DataFrame (result_df) is correctly formatted ---

        # First, ensure the returned object is indeed a Pandas DataFrame
        if not isinstance(result_df, pd.DataFrame):
            raise TypeError(
                f"Wrapped function did not return a Pandas DataFrame. "
                f"Instead, received type: {type(result_df)}"
            )

        # Check if the result_df already has the correct MultiIndex ('ticker', 'date')
        is_output_already_multiindex = isinstance(result_df.index, pd.MultiIndex) and result_df.index.names == ['ticker', 'date']

        if is_output_already_multiindex:
            # If it's already in the desired MultiIndex format, return it directly.
            return result_df
        else:
            # If not, assume 'ticker' and 'date' should be columns that need
            # to be set as the MultiIndex.
            if 'ticker' not in result_df.columns or 'date' not in result_df.columns:
                # If 'ticker' or 'date' are neither in the index nor in the columns,
                # then the output DataFrame is not in a format that can be handled.
                raise ValueError(
                    "Returned DataFrame must contain 'ticker' and 'date' "
                    "as columns (if not already MultiIndexed) to set MultiIndex."
                )
            # If 'ticker' and 'date' are found as columns, set the MultiIndex
            return result_df.set_index(['ticker', 'date'])

    return wrapper

# Core Libraries
import random
import pandas as pd
import numpy as np
import warnings

# Financial Data Access
import yfinance as yf

# Machine Learning / Nearest Neighbors
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

# Parallel Processing
from joblib import Parallel, delayed

# Suppress Warnings
warnings.filterwarnings('ignore')

@check_format
# --- 1. engineer_ticker_specific_features ---
def engineer_specific_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes all technical indicators, various returns, volatility metrics,
    crossovers, interaction terms, and all lagged versions of these
    ticker-specific features.

    Parameters:
    df (pd.DataFrame): Input DataFrame with a MultiIndex (ticker, date)
                       containing 'open', 'high', 'low', 'close', 'volume' columns.

    Returns:
    pd.DataFrame: The input DataFrame with all added ticker-specific features.
    """
    df = df.copy()
    # Ensure DataFrame is sorted by ticker and date for correct time-series operations
    df = df.sort_index(level=['ticker', 'date'])

    grouped = df.groupby(level=0) # Group by ticker for all ticker-specific ops

    result_dfs = []

    for ticker, group in grouped:
        group_df = group.reset_index(level=0, drop=True)
        original_len = len(group_df)

        # --- Technical Indicators ---
        group_df['ma4'] = group_df['close'].rolling(window=4, min_periods=1).mean()
        group_df['ma8'] = group_df['close'].rolling(window=8, min_periods=1).mean()
        group_df['ma16'] = group_df['close'].rolling(window=16, min_periods=1).mean()
        group_df['ma26'] = group_df['close'].rolling(window=26, min_periods=1).mean()

        delta = group_df['close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=10, min_periods=1).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=10, min_periods=1).mean()
        rs = gain / loss.replace(0, np.finfo(float).eps)
        group_df['rsi'] = 100 - (100 / (1 + rs))

        group_df['ema12'] = group_df['close'].ewm(span=12, adjust=False).mean()
        group_df['ema26'] = group_df['close'].ewm(span=26, adjust=False).mean()
        group_df['macd'] = group_df['ema12'] - group_df['ema26']
        group_df['macd_signal'] = group_df['macd'].ewm(span=9, adjust=False).mean()

        high_low = group_df['high'] - group_df['low']
        high_close = np.abs(group_df['high'] - group_df['close'].shift())
        low_close = np.abs(group_df['low'] - group_df['close'].shift())
        ranges = pd.concat([high_low, high_close, low_close], axis=1)
        true_range = np.max(ranges, axis=1)
        group_df['atr'] = true_range.rolling(window=10, min_periods=1).mean()

        group_df['bb_middle'] = group_df['close'].rolling(window=20, min_periods=1).mean()
        std_dev = group_df['close'].rolling(window=20, min_periods=1).std()
        group_df['bb_upper'] = group_df['bb_middle'] + (2 * std_dev)
        group_df['bb_lower'] = group_df['bb_middle'] - (2 * std_dev)

        group_df['volume_ma4'] = group_df['volume'].rolling(window=4, min_periods=1).mean()

        group_df['momentum_4w'] = group_df['close'] / group_df['close'].shift(4) - 1
        group_df['momentum_8w'] = group_df['close'] / group_df['close'].shift(8) - 1

        # --- Time-Series Derivatives & Basic Features ---
        group_df['pct_change_1w'] = group_df['close'].pct_change(1)
        group_df['pct_change_4w'] = group_df['close'].pct_change(4)
        group_df['weekly_return'] = group_df['close'] / group_df['open'] - 1

        group_df['log_ret'] = np.log(group_df['close'] / group_df['close'].shift())
        group_df['volatility_4w'] = group_df['log_ret'].rolling(4, min_periods=1).std()

        group_df['daily_range'] = (group_df['high'] - group_df['low']) / group_df['close']
        group_df['open_close_ret'] = (group_df['close'] - group_df['open']) / group_df['open']
        group_df['bb_position'] = (group_df['close'] - group_df['bb_lower']) / (group_df['bb_upper'] - group_df['bb_lower'])
        group_df['dist_ma26'] = (group_df['close'] - group_df['ma26']) / group_df['ma26']
        group_df['vol_rel_ma'] = group_df['volume'] / group_df['volume_ma4']

        group_df['macd_cross_signal'] = ((group_df['macd'] > group_df['macd_signal']) & \
                                         (group_df['macd'].shift() <= group_df['macd_signal'].shift())).astype(int)
        group_df['rsi_overbought'] = (group_df['rsi'] > 70).astype(int)
        group_df['rsi_oversold'] = (group_df['rsi'] < 30).astype(int)

        group_df['rsi_x_momentum'] = group_df['rsi'] * group_df['momentum_4w']
        group_df['macd_x_return'] = group_df['macd'] * group_df['weekly_return']

        # --- Ticker-Specific Deltas (derived from original fundamentals enhancement) ---
        delta_base_cols = [
            'rsi', 'macd', 'atr', 'momentum_4w', 'momentum_8w',
            'weekly_return', 'volatility_4w', 'daily_range', 'open_close_ret',
            'bb_position', 'dist_ma26', 'vol_rel_ma'
        ]
        for col in delta_base_cols:
            if col in group_df.columns:
                group_df[f"{col}_delta_fund"] = group_df[col].diff()
            else:
                pass # Already handled by print in debug, now silent for consolidated func

        # --- Lagged Features ---
        features_to_lag = [
            'open', 'high', 'low', 'close', 'volume', 'ma4', 'ma8', 'ma16', 'ma26', 'rsi',
            'weekly_return', 'macd', 'atr', 'pct_change_1w', 'pct_change_4w', 'log_ret',
            'volatility_4w', 'daily_range', 'open_close_ret', 'bb_position',
            'dist_ma26', 'vol_rel_ma', 'macd_cross_signal', 'rsi_overbought', 'rsi_oversold',
            'rsi_x_momentum', 'macd_x_return'
        ] + [f"{col}_delta_fund" for col in delta_base_cols if f"{col}_delta_fund" in group_df.columns]

        lags = [1, 2, 4, 8, 20, 40]
        for feature in features_to_lag:
            if feature in group_df.columns:
                for lag in lags:
                    group_df[f'{feature}_lag{lag}'] = group_df[feature].shift(lag)

        # Verify length
        if len(group_df) != original_len:
            raise ValueError(f"Length mismatch for ticker {ticker}: expected {original_len}, got {len(group_df)}")

        group_df = group_df.set_index(
            pd.Series([ticker] * len(group_df.index), name='ticker'), append=True
        )
        result_dfs.append(group_df)

    result = pd.concat(result_dfs)
    result = result.reorder_levels(['ticker', 'date'])
    return result

@check_format
def engineer_market_relative_features(
    df: pd.DataFrame,
    features_to_standardize: list[str],
    base_cols_for_rank_derivatives: list[str],
    *,
    suffix: str = "_fund",
    rolling_rank_window: int = 4,
    add_rank_shock: bool = True,
    add_rank_trend: bool = True,
    long_lags: tuple[int, ...] = (1, 3, 5, 10, 20),
) -> pd.DataFrame:
    """
    Vectorised re-implementation of engineer_market_relative_features.
    Produces identical columns; ~3-10× faster on typical equity universes.
    """

    out = df.copy()
    out = out.sort_index(level=['date', 'ticker'])

    # -------- 1. Cross-sectional ops (batch) --------
    feats = [c for c in features_to_standardize if c in out.columns]
    by_date = out.groupby(level='date')

    z_df = by_date[feats].transform(lambda x: (x - x.mean()) / (x.std(ddof=0) + 1e-8))
    rk_df = by_date[feats].rank(pct=True)

    z_df.columns  = [f"z_{c}{suffix}" for c in feats]
    rk_df.columns = [f"{c}_rank_pct{suffix}" for c in feats]

    out = pd.concat([out, z_df.astype("float32"), rk_df.astype("float32")], axis=1)

    # -------- 2. Derived rank features (batch) --------
    rank_cols = [f"{c}_rank_pct{suffix}" for c in base_cols_for_rank_derivatives
                 if f"{c}_rank_pct{suffix}" in out.columns]

    by_ticker = out.groupby(level=0)

    if add_rank_trend and rolling_rank_window > 0 and rank_cols:
        trend = (
            by_ticker[rank_cols]
            .rolling(rolling_rank_window, min_periods=1)
            .mean()
            .reset_index(level=0, drop=True)
        )
        trend.columns = [f"{c.replace('_rank_pct', '_rank_trend')}{suffix}" for c in base_cols_for_rank_derivatives
                         if f"{c}_rank_pct{suffix}" in out.columns]
        out = pd.concat([out, trend.astype("float32")], axis=1)

    if add_rank_shock and rank_cols:
        shock = by_ticker[rank_cols].diff().rename(
            columns={c: c.replace("_rank_pct", "_rank_shock") for c in rank_cols}
        )
        out = pd.concat([out, shock.astype("float32")], axis=1)

        # -------- 3. Lagged Z-scores (batch) --------
    z_cols = [c for c in out.columns if c.startswith("z_") and c.endswith(suffix)]
    if z_cols and long_lags:
        # Build a dict of Series
        lagged = {
            f"{col}_lag{lag}": by_ticker[col].shift(lag).astype("float32")
            for lag in long_lags
            for col in z_cols
        }

        # <<< fix starts here >>>
        lagged_df = pd.DataFrame(lagged)           # index aligns with `out`
        out = out.join(lagged_df)
        # <<< fix ends here >>>

    return out

@check_format
def engineer_features(X,specific=True,relative=True,n_neighbors=5):
  base_cols_for_rank_derivatives = [
      # -- technical level data --
      "volume",          # raw trading activity
      "volume_ma4",      # short-term liquidity
      "rsi",             # momentum level
      # optionally: "close", "open", "high", "low",

      # -- balance-sheet size / leverage --
      "Balance_Sheet::totalAssets",
      "Balance_Sheet::totalLiab",
      "Balance_Sheet::netDebt",
      "Balance_Sheet::cashAndShortTermInvestments",
      "Balance_Sheet::propertyPlantAndEquipmentNet",
      "Balance_Sheet::commonStockSharesOutstanding",

      # -- income-statement quality & growth --
      "Income_Statement::netIncome",
      "Income_Statement::ebit",
      "Income_Statement::ebitda",
      "Income_Statement::totalRevenue",

      # -- cash-flow quality --
      "Cash_Flow::freeCashFlow",
      "Cash_Flow::totalCashFromOperatingActivities",
      "Cash_Flow::totalCashFromFinancingActivities"
  ]

  if specific:
    X=engineer_specific_features(X)
  if not relative:
    return X

  knn_X=engineer_relative_features(X,n_neighbors)

  return knn_X

@check_format
def engineer_relative_features(X,columns=[],n_neighbors=5):
  base_cols_for_rank_derivatives = [
      # -- technical level data --
      "volume",          # raw trading activity
      "volume_ma4",      # short-term liquidity
      "rsi",             # momentum level
      # optionally: "close", "open", "high", "low",

      # -- balance-sheet size / leverage --
      "Balance_Sheet::totalAssets",
      "Balance_Sheet::totalLiab",
      "Balance_Sheet::netDebt",
      "Balance_Sheet::cashAndShortTermInvestments",
      "Balance_Sheet::propertyPlantAndEquipmentNet",
      "Balance_Sheet::commonStockSharesOutstanding",

      # -- income-statement quality & growth --
      "Income_Statement::netIncome",
      "Income_Statement::ebit",
      "Income_Statement::ebitda",
      "Income_Statement::totalRevenue",

      # -- cash-flow quality --
      "Cash_Flow::freeCashFlow",
      "Cash_Flow::totalCashFromOperatingActivities",
      "Cash_Flow::totalCashFromFinancingActivities"
  ]

  columns=X.columns if not columns else columns

  rel_X=engineer_market_relative_features(X,columns,base_cols_for_rank_derivatives)
  knn_X=create_stock_knn_features(rel_X,feature_cols=rel_X.columns,n_neighbors=n_neighbors)
  return knn_X

import polars as pl
import numpy as np
import faiss                      # pip install faiss-cpu  (or faiss-gpu)
from typing import Sequence, List, Dict

import faiss

def _build_faiss_index(dim: int, use_gpu: bool = False):
    """
    Returns an index that
      • supports add / add_with_ids
      • supports remove_ids
      • can run on CPU **or** GPU
    """
    base = faiss.IndexFlatL2(dim)           # exact L2
    id_map = faiss.IndexIDMap(base)         # <-- gives us add_with_ids / remove_ids

    if use_gpu:
        res     = faiss.StandardGpuResources()
        id_map  = faiss.index_cpu_to_gpu(res, 0, id_map)   # GPU version keeps the ID-map layer

    return id_map


def _aggregate(values: np.ndarray, agg_funcs: Sequence[str]) -> Dict[str, float]:
    out = {}
    if 'mean'   in agg_funcs: out['mean']   = values.mean(axis=0)
    if 'std'    in agg_funcs: out['std']    = values.std(axis=0, ddof=0)
    if 'median' in agg_funcs: out['median'] = np.median(values, axis=0)
    if 'max'    in agg_funcs: out['max']    = values.max(axis=0)
    if 'min'    in agg_funcs: out['min']    = values.min(axis=0)
    return out

@check_format
def create_stock_knn_features(
        df: pl.DataFrame,
        feature_cols: Sequence[str] = ('close',),
        n_neighbors: int = 5,
        lookback_window: int | None = None,
        agg_funcs: Sequence[str] = ('mean',),
        use_gpu: bool = False
    ) -> pl.DataFrame:
    """
    Vectorised, FAISS-powered KNN feature builder.
    * df must have columns: 'ticker', 'date' (string/ts), <feature_cols>
    * Returns df with additional columns of the form
        {f}_{agg}_{k}  (one per feature, agg function and k-th neighbor rank)
    """

    df = pl.from_pandas(df.reset_index() if isinstance(df.index, pd.MultiIndex) else df)
    # ---- 0. Preparation ----------------------------------------------------
    if not {'ticker', 'date', *feature_cols}.issubset(df.columns):
        raise ValueError("df must contain 'ticker', 'date' and all feature_cols")

    df = (df
          .with_columns(pl.col('date').str.to_date())
          .sort(['ticker', 'date'])
    )

    out_rows: List[Dict] = []
    dim = len(feature_cols)

    # ---- 1. Per-ticker processing (but done serially and fast) ------------
    for ticker_df in df.partition_by('ticker', maintain_order=True):
        values = ticker_df.select(feature_cols).to_numpy().astype('float32')
        dates  = ticker_df['date'].to_numpy()
        n      = len(values)

        index  = _build_faiss_index(dim, use_gpu=use_gpu)

        # sliding window boundaries
        left = 0
        for i in range(n):
            # drop rows that moved out of lookback_window
            if lookback_window is not None:
                while left < i and i - left > lookback_window:
                    index.remove_ids(np.array([left], dtype=np.int64))
                    left += 1

            # search k neighbours among past rows
            if index.ntotal > 0:
                _, idx = index.search(values[i:i+1], n_neighbors)
                past_mask         = idx[0] < i          # ensure strictly historical
                valid_idx         = idx[0][past_mask]
                if valid_idx.size:
                    neigh_values  = values[valid_idx]
                    aggs = _aggregate(neigh_values, agg_funcs)
                    out_rows.append(
                        {
                            "ticker": ticker_df[0, "ticker"],
                            # NEW: store as ISO string → Polars sees utf8
                            "date":   str(dates[i].astype("datetime64[D]")),
                            **{f"{col}_{agg}_{n_neighbors}": v[j]
                              for j, col in enumerate(feature_cols)
                              for agg, v in aggs.items()}
                        }
                    )

            # add current row to index
            index.add_with_ids(values[i:i+1], np.array([i], dtype=np.int64))

    feature_df = (
    pl.DataFrame(out_rows)
      .with_columns(
          pl.col("date")
            .str.strptime(pl.Date, "%Y-%m-%d")        # utf8 → Date
      )
    )

    return df.join(feature_df, on=['ticker', 'date'], how='left').to_pandas()

def fundamentals_multi(tickers,api_key=api_key):
  lst=[]
  for ticker in tickers:

      fun_df=fundamentals_single(ticker,api_key)

      fun_df=clean_and_convert_numeric_columns(fun_df)

      fun_df=fun_df.dropna(how='all',axis=1)
      good_cols=fun_df.columns[fun_df.isnull().sum()<0.3*len(fun_df)]
      rel=fun_df[good_cols]

      rel.index=pd.MultiIndex.from_tuples([(ticker,y) for y in fun_df.index.astype(str)], names=['ticker', 'date'])

      lst.append(rel)

  return pd.concat(lst)

import numpy as np
import pandas as pd

@check_format
def enhance_fundamental_neutral(
    df: pd.DataFrame,
    base_cols: list[str],
    *,
    delta: bool = True,
    rolling_rank_window: int = 4,
    add_rank_shock: bool = True,
    add_crosssec_z: bool = True,
    suffix: str = ""
) -> pd.DataFrame:
    """
    Add market-neutral feature derivatives to `base_cols`.

    Parameters
    ----------
    df : DataFrame
        Must have a MultiIndex (ticker, date) **OR** flat cols named 'ticker'/'date'.
    base_cols : list[str]
        Columns to transform.
    delta : bool
        If True, create *_delta and *_delta_rel (cross-sectional z-score of delta).
    rolling_rank_window : int
        Window length (per ticker) for the rolling mean of daily rank-percentile.
        Set to None or 0 to skip rolling-rank features.
    add_rank_shock : bool
        If True, add *_rank_shock (= today’s rank_pct − yesterday’s).
    add_crosssec_z : bool
        If True, add a one-shot cross-sectional z-score of every `base_col`.
    suffix : str
        Optional suffix to tag the new cols (useful if you call the function twice).

    Returns
    -------
    DataFrame  (same index as input)  with the new columns appended.
    """
    out = df.copy()

    # ----- Δ and cross-sectional Δ-z -----
    if delta:
        grp_ticker = out.groupby(level=0)
        grp_date   = out.groupby(level='date')
        for col in base_cols:
            dcol = f"{col}_delta{suffix}"
            zcol = f"{col}_delta_rel{suffix}"
            out[dcol] = grp_ticker[col].diff()
            out[zcol] = grp_date[dcol].transform(
                lambda x: (x - x.mean()) / (x.std(ddof=0) + 1e-8)
            )

    # ----- Rank pct and rolling rank trend -----
    if rolling_rank_window and rolling_rank_window > 0:
        for col in base_cols:
            rcol = f"{col}_rank{suffix}"
            tcol = f"{col}_rank_trend{suffix}"
            # cross-sectional rank every date
            out[rcol] = out.groupby(level='date')[col].rank(pct=True)
            # rolling mean of that rank within ticker
            out[tcol] = out.groupby(level=0)[rcol].transform(
                lambda x: x.rolling(rolling_rank_window).mean()
            )

    # ----- Rank shocks (day-to-day change in rank pct) -----
    if add_rank_shock:
        for col in base_cols:
            rcol = f"{col}_rank{suffix}"
            scol = f"{col}_rank_shock{suffix}"
            # need the rank column from step above; compute if it doesn't exist
            if rcol not in out.columns:
                out[rcol] = out.groupby(level='date')[col].rank(pct=True)
            out[scol] = out.groupby(level=0)[rcol].diff()

    # ----- One-shot cross-sectional z for the raw levels -----
    if add_crosssec_z:
        xs_z = out.groupby(level='date')[base_cols].transform(
            lambda x: (x - x.mean()) / (x.std(ddof=0) + 1e-8)
        )
        xs_z.columns = [f"{c}_rel_z{suffix}" for c in xs_z.columns]
        out = pd.concat([out, xs_z], axis=1)

    return out

def align_quarterly_to_weekly(
    weekly_df: pd.DataFrame,
    quarterly_df: pd.DataFrame,
    suffix: str = "_q",
):
    """
    Attach the most-recent (≤) quarterly snapshot to every (ticker, week-date)
    row, with optional ffill for weeks that precede the first quarter.

    Both inputs must have a MultiIndex (ticker, date) *or* ordinary columns
    named 'ticker' and 'date'.
    """

    def _prep(df):
        # Accept either MultiIndex or flat columns
        if isinstance(df.index, pd.MultiIndex):
            df = df.reset_index()

        # Robust renaming in case levels are unnamed (0, 1)
        df = df.rename(columns={df.columns[0]: "ticker", df.columns[1]: "date"})

        # Parse dates once, coercing errors to NaT (they will drop out later)
        df["date"] = pd.to_datetime(df["date"], errors="coerce")

        # Keep only rows with a real date, then sort *by date first*
        df = df.dropna(subset=["date"]).sort_values(["date", "ticker"], ignore_index=True)
        return df

    wk = _prep(weekly_df.copy())
    qt = _prep(quarterly_df.copy())

    merged = pd.merge_asof(
        wk,
        qt,
        by="ticker",
        on="date",
        direction="backward",
        suffixes=("", suffix),
    )

    # Forward-fill quarterly columns within each ticker so that
    # weeks before the first quarterly print stay NaN (remove next 3 lines
    # if you prefer to keep those NaNs instead of back-filling).
    qcols = [c for c in merged.columns if c.endswith(suffix)]
    merged[qcols] = merged.groupby("ticker", sort=False)[qcols].ffill()

    return (
        merged.set_index(["ticker", "date"])
              .sort_index()               # nice, clean MultiIndex again
    )


def eodhd_symbol(ticker: str, api_token: str,
                 exchange_hint: str = "US",
                 offline_map: dict | None = None) -> str:
    """
    Convert a Yahoo/IB/Polygon ticker to the canonical EODHD symbol.

    Parameters
    ----------
    ticker : str
        Raw ticker (e.g. 'BRK.B', 'brkb', 'brk-b').
    api_token : str
        Your EODHD API key.
    exchange_hint : str, default 'US'
        Restrict Search API results to this exchange.
    offline_map : dict, optional
        Pre-loaded {raw_ticker -> eodhd_symbol} mapping to skip the API call.

    Returns
    -------
    str
        Canonical EODHD symbol such as 'BRK-B.US'.
    """
    if offline_map and ticker.upper() in offline_map:
        return offline_map[ticker.upper()]

    # --- heuristic normalisation -----------------------------
    cleaned = ticker.upper().replace('.', '-').replace('_', '-')

    # Use Search API to be 100 % sure
    url = (f"https://eodhd.com/api/search/{cleaned}"
           f"?api_token={api_token}&fmt=json&type=stock&limit=10")
    res = requests.get(url, timeout=10)
    res.raise_for_status()
    for item in res.json():                       # pick the first hit on the desired exchange
        if item["Exchange"] == exchange_hint:
            return f'{item["Code"]}.{item["Exchange"]}'

    # fallback: first result of any exchange
    if res.json():
        item = res.json()[0]
        return f'{item["Code"]}.{item["Exchange"]}'

    raise ValueError(f"No EODHD match found for '{ticker}'")

import requests

def fundamentals_single(ticker, api_token):

    ticker=eodhd_symbol(ticker,api_token)

    base_url = "https://eodhd.com/api/fundamentals"
    sections = [
        "General", "Highlights", "Valuation", "SharesStats", "Technicals",
        "SplitsDividends", "AnalystRatings", "Holders", "ESGScores", "outstandingShares",
        "Earnings", # Earnings can be time-series, we'll handle it carefully
        "Financials::Balance_Sheet::quarterly",
        "Financials::Income_Statement::quarterly",
        "Financials::Cash_Flow::quarterly"
    ]

    # Dictionary to hold time-series data (e.g., financials)
    time_series_data = {}
    # Dictionary to hold static/snapshot data (e.g., general, highlights)
    static_data = {}

    #if '.' not in ticker:
     #   ticker = f"{ticker}.US"


    for section in sections:
        url = f"{base_url}/{ticker}?api_token={api_token}&fmt=json&filter={section}"
        try:
            resp = requests.get(url)
            resp.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
            data = resp.json()

            if "Financials::" in section:
                # Handle Financials (quarterly data with dates as keys)
                for date, metrics in data.items():
                    for key, value in metrics.items():
                        # Use the specific financial type in the column name
                        col_name = f"{section.split('::')[1]}::{key}"
                        time_series_data.setdefault(date, {})[col_name] = value
            elif section == "Earnings":
                # Earnings usually has 'quarterly' and 'annual' keys
                if 'quarterly' in data:
                    for entry in data['quarterly']:
                        date = entry.get('dateReport') # Or 'date' depending on API
                        if date:
                            for key, value in entry.items():
                                col_name = f"Earnings::quarterly::{key}"
                                time_series_data.setdefault(date, {})[col_name] = value
                # You might also want to handle 'annual' earnings similarly if needed
            else:
                # Handle static/snapshot data
                # For static data, we'll just take the latest available info
                # and prefix columns with the section name
                for key, value in data.items():
                    static_data[f"{section}::{key}"] = value

        except requests.exceptions.HTTPError as e:
            print(f"HTTP error for {section}: {e.response.status_code} - {e.response.text}")
        except requests.exceptions.ConnectionError as e:
            print(f"Connection error for {section}: {e}")
        except requests.exceptions.Timeout as e:
            print(f"Timeout error for {section}: {e}")
        except requests.exceptions.RequestException as e:
            print(f"Request error for {section}: {e}")
        except Exception as e:
            print(f"An unexpected error occurred for {section}: {e}")

    # Create DataFrame for time-series data
    df_time_series = pd.DataFrame.from_dict(time_series_data, orient='index')
    if not df_time_series.empty:
        df_time_series.index = pd.to_datetime(df_time_series.index)
        df_time_series = df_time_series.sort_index(ascending=False) # Sort by most recent date first

    # Create DataFrame for static data
    # Static data will be a single row DataFrame
    df_static = pd.DataFrame([static_data]) # Wrap in a list to make it a single-row DF

    # You can now choose how to combine them:
    # Option 1: Return two separate DataFrames (recommended for clarity)
    return df_time_series


# Assuming df_financials is the DataFrame you want to clean
# If you combined df_financials and df_general_info into one, use that combined DF name.

def clean_and_convert_numeric_columns(df):
    """
    Identifies columns that should be numeric but might contain string representations
    of numbers or 'None'/'null' and converts them to numeric, coercing errors to NaN.

    Args:
        df (pd.DataFrame): The input DataFrame.

    Returns:
        pd.DataFrame: The DataFrame with relevant columns converted to numeric.
    """
    df_cleaned = df.copy() # Work on a copy to avoid modifying the original directly

    for col in df_cleaned.columns:
        # Try converting the column to numeric.
        # 'errors='coerce' will turn any non-numeric values (like 'None', 'null',
        # or other non-convertible strings) into NaN.
        converted_col = pd.to_numeric(df_cleaned[col], errors='coerce')

        # Check if the conversion actually resulted in a numeric type
        # AND if it introduced any NaNs that weren't there before (indicating
        # that non-numeric strings were present) or if it successfully converted
        # a string/object column to numeric.

        # A simple heuristic: if the column's dtype changed from object to a numeric type,
        # or if the non-null values are now numeric and it was an object type.

        # More precise check: If the original column's dtype was 'object' (string mix)
        # AND the converted column's dtype is now numeric (int, float)
        # OR if it's already numeric but has 'None' as a string, to ensure it handles it.

        # Let's be more direct: if the original column contains strings/objects
        # and after conversion it *can* be numeric, then replace.

        # We replace if the new column is numeric OR if it contains NaNs but
        # the *original* was not fully numeric (i.e., it had non-numeric strings).
        # This prevents converting genuinely string columns with some numbers (like IDs)
        # into floats if that's not desired.

        # A robust way is to check if it improved the dtype towards numeric.
        # If the original column was 'object' (strings, mixed types)
        # and the coerced column is now a number (float, int), then we replace.
        if df_cleaned[col].dtype == 'object' or df_cleaned[col].apply(lambda x: isinstance(x, (str, type(None)))).any():
            if pd.api.types.is_numeric_dtype(converted_col):
                # Ensure we don't accidentally convert columns that are legitimately strings
                # but might contain numbers (like '2023-12-31' which is a date string).
                # This is why 'errors=coerce' is powerful.
                df_cleaned[col] = converted_col
            elif pd.api.types.is_object_dtype(converted_col) and (converted_col.isna().sum() > 0 or df_cleaned[col].apply(lambda x: isinstance(x, (str, type(None))) and str(x).lower() in ['none', 'null']).any()):
                 # This condition handles cases where 'to_numeric' might not fully convert
                 # but we still want to clean 'None' strings to NaN
                 df_cleaned[col] = converted_col # Assign the coerced column, letting NaNs be in place.

    return df_cleaned

import re
import pandas as pd
import yfinance as yf

# --- helpers ---------------------------------------------------------------

_YF_SUPPORTED_INTERVALS = {"1m","2m","5m","15m","30m","60m","90m","1h",
                           "1d","5d","1wk","1mo","3mo"}

def _ohlcv_resample(df: pd.DataFrame, rule: str) -> pd.DataFrame:
    """
    Resample per-ticker OHLCV to a new frequency rule.
    Assumes index is DatetimeIndex, columns: open/high/low/close/volume (lowercase).
    """
    agg = {
        "open": "first",
        "high": "max",
        "low": "min",
        "close": "last",
        "volume": "sum",
    }
    out = df.resample(rule).agg(agg)
    return out.dropna(subset=["open","high","low","close"], how="any")

def _parse_freq(freq: str) -> tuple[str, str | None]:
    """
    Returns (yf_interval, pandas_resample_rule or None).
    If pandas_resample_rule is not None, we will download '1d' and resample.
    """
    if not isinstance(freq, str) or not freq:
        raise ValueError("freq must be a non-empty string (e.g., '1d', '1wk', '10d').")

    f = freq.strip().lower()

    # If yfinance can do it directly, prefer that.
    if f in _YF_SUPPORTED_INTERVALS:
        return f, None

    # Allow "n days" like "10d", "21d" by resampling daily bars
    m = re.fullmatch(r"(\d+)d", f)
    if m:
        n = int(m.group(1))
        if n <= 0:
            raise ValueError("freq like 'nD' must have n >= 1.")
        # yfinance supports 1d and 5d; everything else -> resample from 1d
        if f in _YF_SUPPORTED_INTERVALS:
            return f, None
        return "1d", f"{n}D"

    # Common aliases
    if f in {"1w", "w", "week", "weekly"}:
        return "1wk", None
    if f in {"1day", "day", "daily"}:
        return "1d", None

    raise ValueError(
        f"Unsupported freq='{freq}'. Use a yfinance interval like {sorted(_YF_SUPPORTED_INTERVALS)} "
        "or an 'nD' string like '10d' (will resample from daily)."
    )

# --- core: generalized OHLCV download --------------------------------------

def generate_stock_data(
    tickers,
    start_date,
    end_date,
    freq: str = "1d",
    auto_adjust: bool = False,
    threads: bool = True,
):
    """
    Download OHLCV via yfinance at `freq` (yfinance interval strings),
    with optional pandas resampling for 'nD' (e.g., '10d').

    Returns
    -------
    pd.DataFrame
        MultiIndex (ticker, date) with columns: open, high, low, close, volume.
    """
    if isinstance(tickers, str):
        tickers = [tickers]

    yf_interval, pandas_rule = _parse_freq(freq)

    raw = yf.download(
        tickers,
        start=start_date,
        end=end_date,
        interval=yf_interval,
        group_by="ticker",
        auto_adjust=auto_adjust,
        progress=False,
        threads=threads,
    )

    if raw.empty:
        raise ValueError("No data returned from yfinance for given tickers/date range")

    frames = []

    # Case 1: MultiIndex columns
    if isinstance(raw.columns, pd.MultiIndex):
        lvl0 = raw.columns.get_level_values(0)
        lvl1 = raw.columns.get_level_values(1)

        tickers_set = set(tickers)
        if tickers_set.issubset(set(lvl0)):
            ticker_level = 0
        elif tickers_set.issubset(set(lvl1)):
            ticker_level = 1
        else:
            raise ValueError("Could not locate tickers in returned MultiIndex columns.")

        for tkr in tickers:
            if ticker_level == 0:
                df_tkr = raw[tkr].copy()
            else:
                df_tkr = raw.xs(tkr, axis=1, level=ticker_level).copy()

            df_tkr = (
                df_tkr.rename(columns=str.lower)
                      .rename_axis("date")
                      .sort_index()
            )

            ohlcv = pd.DataFrame({
                "open":   df_tkr.get("open"),
                "high":   df_tkr.get("high"),
                "low":    df_tkr.get("low"),
                "close":  df_tkr.get("close"),
                "volume": df_tkr.get("volume"),
            }).dropna(how="all")

            # Resample if requested (only for nD / custom)
            if pandas_rule is not None:
                ohlcv = _ohlcv_resample(ohlcv, pandas_rule)

            ohlcv["ticker"] = tkr
            frames.append(ohlcv.reset_index())

    # Case 2: Single-index columns (single ticker)
    else:
        if len(tickers) != 1:
            raise ValueError("Non-MultiIndex columns returned but multiple tickers requested.")

        tkr = tickers[0]
        df_tkr = (
            raw.rename(columns=str.lower)
               .rename_axis("date")
               .sort_index()
        )

        ohlcv = pd.DataFrame({
            "open":   df_tkr.get("open"),
            "high":   df_tkr.get("high"),
            "low":    df_tkr.get("low"),
            "close":  df_tkr.get("close"),
            "volume": df_tkr.get("volume"),
        }).dropna(how="all")

        if pandas_rule is not None:
            ohlcv = _ohlcv_resample(ohlcv, pandas_rule)

        ohlcv["ticker"] = tkr
        frames.append(ohlcv.reset_index())

    all_data = (
        pd.concat(frames, ignore_index=True)
          .set_index(["ticker", "date"])
          .sort_index()
    )

    if all_data.index.duplicated().any():
        raise ValueError("Duplicate (ticker, date) entries found in fetched data")

    return all_data

def compute_y_for_params(
    data_base: pd.DataFrame,
    *,
    horizon: int,
    rank_ascending: bool,
    # fixed-only params
    stop_pct: float,
    take_profit_pct: float,
    entry_price_col: str = "close",
    use_ohlc: bool = True,
) -> pd.Series:
    """Compute ranked target y aligned to data_base.index using vectorbt fixed SL/TP."""

    raw_profit = calculate_profit_vectorbt(
        data_base,
        horizon=horizon,
        stop_pct=stop_pct,
        take_profit_pct=take_profit_pct,
        entry_price_col=entry_price_col,
        use_ohlc=use_ohlc,
    )

    return raw_profit


import vectorbt as vbt
def calculate_profit_vectorbt(
    data: pd.DataFrame,
    horizon: int = 1,
    *,
    stop_pct: float = np.inf,
    take_profit_pct: float = np.inf,
    entry_price_col: str = "close",
    use_ohlc: bool = True,
    chunk_size: int = 512,

    # --- new label options ---
    higher_is_better: bool = True,       # True: higher profit => higher percentile
    pct_method: str = "average",         # rank tie handling: 'average', 'min', 'max', 'dense', 'first'
    output: str = "pct",                 # "pct" -> [0,1], "signed" -> [-1,1]
) -> pd.Series:
    """
    1) Computes per-(ticker,date) realized probe profit using fixed SL/TP + time exit at horizon
       (same semantics as your existing function).
    2) Converts those profits into cross-sectional percentile ranks PER DATE.

    output:
      - "pct": percentile in [0,1]
      - "signed": maps pct to [-1,1] via (2*pct - 1)

    Notes:
      - NaNs remain NaN and are excluded from daily ranking.
      - If a given date has <2 valid names, percentile ranks may be NaN or degenerate.
    """

    if horizon < 1:
        raise ValueError("horizon must be >= 1")
    if not isinstance(data.index, pd.MultiIndex):
        raise ValueError("data must have MultiIndex with ticker as level 0 (and date as another level).")
    for col in ["close", entry_price_col]:
        if col not in data.columns:
            raise KeyError(f"Missing required column: '{col}'")

    need_ohlc = use_ohlc and all(c in data.columns for c in ["open", "high", "low"])
    if use_ohlc and not need_ohlc:
        raise KeyError("use_ohlc=True requires columns: open, high, low (in addition to close).")

    # Identify date level (keep your original intent)
    if "date" in data.index.names:
        date_level = data.index.names.index("date")
    else:
        date_level = 1 if data.index.nlevels >= 2 else None
    if date_level is None:
        raise ValueError("Could not infer date level in MultiIndex.")

    # --- Step 1: compute profits exactly like before ---
    out_profit = pd.Series(np.nan, index=data.index, dtype="float64", name="profit")

    for tkr, g in data.groupby(level=0, sort=False):
        lvl = g.index.get_level_values(date_level)
        dt = pd.to_datetime(lvl, errors="coerce")
        order = np.argsort(np.asarray(dt, dtype="datetime64[ns]"), kind="mergesort")
        g = g.iloc[order]

        n = len(g)
        if n <= horizon:
            continue

        close = pd.to_numeric(g["close"], errors="coerce").to_numpy(float)
        entry_px = pd.to_numeric(g[entry_price_col], errors="coerce").to_numpy(float)

        if need_ohlc:
            opn  = pd.to_numeric(g["open"], errors="coerce").to_numpy(float)
            high = pd.to_numeric(g["high"], errors="coerce").to_numpy(float)
            low  = pd.to_numeric(g["low"], errors="coerce").to_numpy(float)
        else:
            opn = high = low = None

        valid_entry = np.isfinite(entry_px) & (entry_px > 0)
        valid_i = np.where(valid_entry)[0]
        valid_i = valid_i[valid_i <= (n - 1 - horizon)]
        if valid_i.size == 0:
            continue

        profits_sorted = np.full(n, np.nan, dtype=float)

        for start in range(0, valid_i.size, chunk_size):
            idx_chunk = valid_i[start:start + chunk_size]
            m = idx_chunk.size

            close_df = pd.DataFrame(
                np.tile(close.reshape(-1, 1), (1, m)),
                index=np.arange(n),
                columns=np.arange(m)
            )

            entries = np.zeros((n, m), dtype=bool)
            entries[idx_chunk, np.arange(m)] = True

            exits = np.zeros((n, m), dtype=bool)
            exits[idx_chunk + horizon, np.arange(m)] = True

            pf_kwargs = dict(
                close=close_df,
                entries=pd.DataFrame(entries, index=close_df.index, columns=close_df.columns),
                exits=pd.DataFrame(exits, index=close_df.index, columns=close_df.columns),
                init_cash=1.0,
                size=1.0,
                size_type="value",
                fees=0.0,
                slippage=0.0,
                sl_stop=float(stop_pct),
                sl_trail=False,
                tp_stop=float(take_profit_pct),
            )

            if need_ohlc:
                open_df = pd.DataFrame(np.tile(opn.reshape(-1, 1), (1, m)), index=close_df.index, columns=close_df.columns)
                high_df = pd.DataFrame(np.tile(high.reshape(-1, 1), (1, m)), index=close_df.index, columns=close_df.columns)
                low_df  = pd.DataFrame(np.tile(low.reshape(-1, 1), (1, m)), index=close_df.index, columns=close_df.columns)
                pf_kwargs.update(open=open_df, high=high_df, low=low_df)

            pf = vbt.Portfolio.from_signals(**pf_kwargs)
            rets = pf.total_return().to_numpy(dtype=float)
            profits_sorted[idx_chunk] = rets

        out_profit.loc[g.index] = profits_sorted

    out_profit.name = "profit"

    # --- Step 2: convert profit -> cross-sectional percentile per date ---
    # Higher profit should map to higher percentile.
    # For pandas rank: ascending=True gives smallest rank=1, largest rank=N; pct=True makes largest -> 1.0
    ascending = True if higher_is_better else False

    out_pct = out_profit.groupby(level=date_level).rank(
        method=pct_method,
        pct=True,
        ascending=ascending
    )

    if output == "pct":
        out_pct.name = "y_rank_pct"
        return out_pct

    if output == "signed":
        out_signed = 2.0 * out_pct - 1.0
        out_signed.name = "y_rank_signed"
        return out_signed

    raise ValueError("output must be one of: {'pct', 'signed'}")

import operator
import random
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union, Literal

import numpy as np

try:
    import pandas as pd
except Exception:  # pragma: no cover
    pd = None

import polars as pl

try:
    from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin
except Exception:  # pragma: no cover
    class BaseEstimator:
        pass
    class TransformerMixin:
        pass
    class RegressorMixin:
        pass

from deap import base, creator, tools, gp

Arg = Union[str, "FeatureNode"]
OpType = Literal["element-wise", "groupby", "time-series", "target_encoding"]
SearchMode = Literal["ga", "hill_climb", "ga_hill_climb"]


@dataclass(frozen=True)
class OperatorSpec:
    name: str
    arity: int
    operator_type: OpType
    fn: Callable
    cat_pos: tuple[int, ...]
    num_pos: tuple[int, ...]
    target_pos: Optional[int] = None


@dataclass(frozen=True)
class OperationSpec:
    name: str
    arity: int
    kind: str
    builder: Callable[["GAFeatureEngineerDEAP", List[pl.Expr], Dict[str, Any]], pl.Expr]
    formatter: Callable[[List[str], Dict[str, Any]], str]
    requires_group_col: bool = False
    restrict_group_cols_to_categoricals: bool = False


@dataclass
class FeatureNode:
    op_token: str
    op_name: str
    args: List[Arg]
    params: Dict[str, Any]
    kind: str


@dataclass(frozen=True)
class NumE:
    expr: pl.Expr
    pre_cols: Tuple[Tuple[str, pl.Expr], ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class CatE:
    expr: pl.Expr


class GAFeatureEngineerDEAP(BaseEstimator, TransformerMixin, RegressorMixin):
    def __init__(
        self,
        index_cols: Tuple[str, str] = ("ticker", "date"),
        categorical_cols: Optional[Sequence[str]] = None,
        numeric_cols: Optional[Sequence[str]] = None,
        max_colname_len: int = 160,
        random_state: int = 0,
        target_encoding_smoothing: float = 10.0,
        enable_impostor_op: bool = False,

        # GA metric: used ONLY in search_mode="ga"
        metric: Optional[Callable[[np.ndarray, np.ndarray], float]] = None,
        maximize_metric: bool = False,

        # Hill-climb metric: used in search_mode="hill_climb" or "ga_hill_climb"
        hc_metric: Optional[Callable[[np.ndarray, np.ndarray], float]] = None,
        maximize_hc_metric: Optional[bool] = None,

        # GA knobs
        population_size: int = 300,
        generations: int = 25,
        tournament_size: int = 7,
        cxpb: float = 0.5,
        mutpb: float = 0.3,
        init_min_depth: int = 1,
        init_max_depth: int = 4,
        max_tree_height: int = 10,
        hall_of_fame: int = 5,
        parsimony_coefficient: float = 1e-4,
        early_stop_rounds: Optional[int] = 7,
        early_stop_tol: float = 1e-6,

        # hill-climb knobs (still apply in ga_hill_climb)
        hc_max_steps: int = 25,
        hc_num_gp_candidates: int = 50,
        hc_include_identity_candidates: bool = True,
        hc_start_with_one_identity: bool = True,
        hc_prune: bool = True,
        hc_patience: int = 5,
        hc_tol: float = 1e-12,

        # new
        search_mode: SearchMode = "ga",
        verbose: bool = False,
    ):
        self.index_cols = index_cols
        self.categorical_cols = list(categorical_cols) if categorical_cols else []
        self.numeric_cols = list(numeric_cols) if numeric_cols else []
        self.max_colname_len = int(max_colname_len)
        self.random_state = int(random_state)
        self.target_encoding_smoothing = float(target_encoding_smoothing)
        self.enable_impostor_op = bool(enable_impostor_op)
        self._tmp_col_counter = 0
        self.verbose = bool(verbose)

        # GA metric
        self.metric = metric
        self.maximize_metric = bool(maximize_metric)
        if isinstance(self.metric, (list, tuple)):
            raise TypeError("Pass exactly one GA metric callable (not a list/tuple).")
        if self.metric is not None and not callable(self.metric):
            raise TypeError("metric must be a callable or None.")

        # HC metric
        self.hc_metric = hc_metric
        if self.hc_metric is not None and not callable(self.hc_metric):
            raise TypeError("hc_metric must be a callable or None.")
        # If not specified, default to GA maximize flag for HC as well (keeps old behavior workable)
        self.maximize_hc_metric = bool(self.maximize_metric if maximize_hc_metric is None else maximize_hc_metric)

        self.search_mode: SearchMode = search_mode

        # DEAP knobs
        self.population_size = int(population_size)
        self.generations = int(generations)
        self.tournament_size = int(tournament_size)
        self.cxpb = float(cxpb)
        self.mutpb = float(mutpb)
        self.init_min_depth = int(init_min_depth)
        self.init_max_depth = int(init_max_depth)
        self.max_tree_height = int(max_tree_height)
        self.hall_of_fame = int(hall_of_fame)
        self.parsimony_coefficient = float(parsimony_coefficient)
        self.early_stop_rounds = None if early_stop_rounds is None else int(early_stop_rounds)
        self.early_stop_tol = float(early_stop_tol)

        self._rng: random.Random = random.Random(self.random_state)

        # registries (keep your existing ones)
        self._custom_ops: Dict[str, OperatorSpec] = {}
        self._ops_elementary: Dict[str, OperationSpec] = {}
        self._ops_groupby: Dict[str, OperationSpec] = {}
        self._ops_ts: Dict[str, OperationSpec] = {}
        self._ops_target: Dict[str, OperationSpec] = {}

        # target encoding
        self._te_maps: Dict[str, pl.DataFrame] = {}
        self._te_global_mean: Optional[float] = None
        self._te_target_col: Optional[str] = None

        # hill climb knobs
        self.hc_max_steps = int(hc_max_steps)
        self.hc_num_gp_candidates = int(hc_num_gp_candidates)
        self.hc_include_identity_candidates = bool(hc_include_identity_candidates)
        self.hc_start_with_one_identity = bool(hc_start_with_one_identity)
        self.hc_prune = bool(hc_prune)
        self.hc_patience = int(hc_patience)
        self.hc_tol = float(hc_tol)

        # outputs
        self.selected_programs_: Optional[List[str]] = None
        self.selected_fitness_: Optional[float] = None
        self.selected_feature_names_: Optional[List[str]] = None

        self.hof_: Optional[tools.HallOfFame] = None
        self.best_programs_: Optional[List[str]] = None
        self.best_fitness_: Optional[List[float]] = None
        self.best_feature_names_: Optional[List[str]] = None

        # internal
        self._pset: Optional[gp.PrimitiveSetTyped] = None
        self._toolbox: Optional[base.Toolbox] = None
        self._fitted: bool = False

        # keep your existing operator registration
        self._register_default_ops()

    # -------------------------
    # You should KEEP all your existing helpers:
    #   _register_default_ops, _build_pset, _ensure_deap, _to_polars, _infer_numeric_cols,
    #   _fit_target_encoders, _apply_target_encoders, _program_to_numpy,
    #   _compile_to_numexpr, _individual_to_symbolic, _sanitize_feature_name, _dedupe_names, etc.
    # -------------------------

    # ---- existing default metric for GA mode ----
    def _default_metric(self, y_true: np.ndarray, y_pred: np.ndarray) -> float:
        return float(np.mean((y_pred - y_true) ** 2))

    def _compute_single_metric(self, y_true: np.ndarray, y_pred: np.ndarray) -> float:
        fn = self.metric if self.metric is not None else self._default_metric
        val = fn(y_true, y_pred)
        if not isinstance(val, (int, float, np.number)):
            raise TypeError(f"Metric must return a single number, got {type(val)}")
        val = float(val)
        if not np.isfinite(val):
            raise ValueError("Metric must return a finite number.")
        return val

    # ---- HC scoring ----
    def _hc_score(self, Xmat: np.ndarray, y: np.ndarray) -> float:
        if self.hc_metric is None:
            raise ValueError("hc_metric must be provided for hill climbing modes.")
        val = float(self.hc_metric(Xmat, y))
        if not np.isfinite(val):
            raise ValueError("hc_metric must return a finite number.")
        return val

    def _hc_improved(self, new_score: float, old_score: float) -> bool:
        if self.maximize_hc_metric:
            return new_score > (old_score + self.hc_tol)
        return new_score < (old_score - self.hc_tol)

    # -------------------------
    # GA-backed hill climbing
    # -------------------------
    @dataclass
    class _HCState:
        selected_inds: List[Any]
        selected_names: List[str]
        best_X: np.ndarray
        best_score: float
        no_improve: int = 0

    def _make_identity_individual(self, col: str):
        self._ensure_deap()
        expr = f"el__identity(num__{col})"
        return creator.Individual(gp.PrimitiveTree.from_string(expr, self._pset))

    def _fit_ga_hill_climb(self, df: pl.DataFrame, y_np: np.ndarray) -> "GAFeatureEngineerDEAP":
        """Hybrid mode:
        - GA generates candidates via evolution.
        - Evaluation uses HC metric incrementally (add candidate feature to current selected set).
        - Acceptance updates the HC state (selected feature set).
        - GA's original y/y_pred evaluation is not performed.
        """
        self._ensure_deap()

        # ---- init HC state (same idea as your old hill climb) ----
        remaining_identity = set(self.numeric_cols)
        selected_inds: List[Any] = []
        selected_names: List[str] = []

        if self.hc_start_with_one_identity and remaining_identity:
            c0 = self._rng.choice(list(remaining_identity))
            ind0 = self._make_identity_individual(c0)
            selected_inds.append(ind0)
            selected_names.append(str(ind0))
            remaining_identity.remove(c0)

        if not selected_inds:
            if not remaining_identity:
                raise ValueError("No numeric columns available for hill-climb.")
            c0 = self._rng.choice(list(remaining_identity))
            ind0 = self._make_identity_individual(c0)
            selected_inds.append(ind0)
            selected_names.append(str(ind0))
            remaining_identity.remove(c0)

        def build_X(ind_list: List[Any]) -> np.ndarray:
            cols = [self._program_to_numpy(df, ind) for ind in ind_list]
            return np.column_stack(cols) if cols else np.empty((df.height, 0), dtype=float)

        best_X = build_X(selected_inds)
        best_score = self._hc_score(best_X, y_np)

        state = GAFeatureEngineerDEAP._HCState(
            selected_inds=selected_inds,
            selected_names=selected_names,
            best_X=best_X,
            best_score=best_score,
            no_improve=0,
        )

        # ---- DEAP fitness: based on HC metric for THIS individual (incremental) ----
        def _eval_hc(individual):
            try:
                feat = self._program_to_numpy(df, individual)
                X_try = np.column_stack([state.best_X, feat])
            except Exception:
                return (1e18,)  # minimize

            mask = np.isfinite(y_np) & np.all(np.isfinite(X_try), axis=1)
            if mask.sum() < max(5, int(0.2 * len(y_np))):
                return (1e18,)

            sc = self._hc_score(X_try[mask], y_np[mask])

            # accept if improves the running HC solution
            if self._hc_improved(sc, state.best_score):
                state.selected_inds.append(individual)
                state.selected_names.append(str(individual))
                state.best_X = X_try
                state.best_score = sc
                state.no_improve = 0

                # optional prune (same semantics as your original)
                if self.hc_prune and len(state.selected_inds) > 1:
                    # Greedy redundancy pruning: drop any feature whose removal doesn't hurt.
                    changed = True
                    while changed and len(state.selected_inds) > 1:
                        changed = False
                        for j in range(len(state.selected_inds)):
                            trial_inds = state.selected_inds[:j] + state.selected_inds[j + 1 :]
                            X_trial = build_X(trial_inds)
                            m2 = np.isfinite(y_np) & np.all(np.isfinite(X_trial), axis=1)
                            if m2.sum() < max(5, int(0.2 * len(y_np))):
                                continue
                            sc2 = self._hc_score(X_trial[m2], y_np[m2])
                            not_worse = (
                                sc2 >= state.best_score - self.hc_tol
                                if self.maximize_hc_metric
                                else sc2 <= state.best_score + self.hc_tol
                            )
                            if not_worse:
                                state.selected_inds.pop(j)
                                state.selected_names.pop(j)
                                state.best_X = X_trial
                                state.best_score = sc2
                                changed = True
                                break

            # translate to DEAP FitnessMin
            fit_val = -sc if self.maximize_hc_metric else sc
            return (fit_val + self.parsimony_coefficient * len(individual),)

        self._toolbox.register("evaluate", _eval_hc)

        # ---- run GA (unchanged loop structure) ----
        pop = self._toolbox.population(n=self.population_size)
        hof = tools.HallOfFame(maxsize=self.hall_of_fame)

        # initial eval
        for ind, fit in zip(pop, map(self._toolbox.evaluate, pop)):
            ind.fitness.values = fit
        hof.update(pop)

        best_hist = [hof[0].fitness.values[0]]
        no_improve_ga = 0

        for _gen in range(1, self.generations + 1):
            offspring = list(map(self._toolbox.clone, self._toolbox.select(pop, len(pop))))

            for c1, c2 in zip(offspring[::2], offspring[1::2]):
                if self._rng.random() < self.cxpb:
                    self._toolbox.mate(c1, c2)
                    del c1.fitness.values, c2.fitness.values

            for mut in offspring:
                if self._rng.random() < self.mutpb:
                    self._toolbox.mutate(mut)
                    del mut.fitness.values

            invalid = [ind for ind in offspring if not ind.fitness.valid]
            for ind, fit in zip(invalid, map(self._toolbox.evaluate, invalid)):
                ind.fitness.values = fit

            pop[:] = offspring
            hof.update(pop)

            cur_best = hof[0].fitness.values[0]
            best_hist.append(cur_best)

            if self.early_stop_rounds is not None:
                if len(best_hist) >= 2 and (best_hist[-2] - best_hist[-1]) <= self.early_stop_tol:
                    no_improve_ga += 1
                else:
                    no_improve_ga = 0
                if no_improve_ga >= self.early_stop_rounds:
                    break

        # ---- store hybrid outputs ----
        self.hof_ = hof
        self.best_programs_ = [str(ind) for ind in hof]
        self.best_fitness_ = [float(ind.fitness.values[0]) for ind in hof]
        self.best_feature_names_ = self._dedupe_names(
            [self._sanitize_feature_name(self._individual_to_symbolic(ind)) for ind in hof]
        )

        # HC-selected (accepted) programs
        self.selected_programs_ = list(state.selected_names)
        raw = [self._individual_to_symbolic(ind) for ind in state.selected_inds]
        raw = [self._sanitize_feature_name(s) for s in raw]
        self.selected_feature_names_ = self._dedupe_names(raw)
        self.selected_fitness_ = float(state.best_score)
        self._hc_selected_inds_ = list(state.selected_inds)

        self._fitted = True
        return self

    # -------------------------
    # fit(): route modes
    # -------------------------
    def fit(self, X: Any, y: Any, target_col: Optional[str] = None) -> "GAFeatureEngineerDEAP":
        df = self._to_polars(X)
        self.numeric_cols = self._infer_numeric_cols(df)

        y_np = np.asarray(y).reshape(-1).astype(float)
        if y_np.shape[0] != df.height:
            raise ValueError("y length != number of rows in X")

        if target_col is None:
            target_col = "__target__"
        self._te_target_col = target_col

        if self.categorical_cols:
            df_te = df.with_columns(pl.Series(target_col, y_np))
            self._fit_target_encoders(df_te, target_col=target_col)
            df = self._apply_target_encoders(df)

        # rebuild GP primitives now that columns/TE are known
        self._pset = None
        self._toolbox = None
        self._ensure_deap()

        if self.search_mode in ("hill_climb", "ga_hill_climb"):
            # smoke test: hc_metric signature
            if self.hc_metric is None:
                raise ValueError("hc_metric must be provided when search_mode is hill_climb or ga_hill_climb.")
            try:
                _ = float(self.hc_metric(np.zeros((len(y_np), 1)), y_np))
            except TypeError as e:
                raise TypeError(
                    "In hill climbing modes, hc_metric must have signature hc_metric(X, y)."
                ) from e

        if self.search_mode == "hill_climb":
            return self._fit_hill_climb(df, y_np)  # keep your existing implementation

        if self.search_mode == "ga_hill_climb":
            return self._fit_ga_hill_climb(df, y_np)

        # --------------------
        # Pure GA mode (unchanged): metric(y, y_pred)
        # --------------------
        if self.metric is not None:
            # smoke test ga metric
            try:
                _ = float(self.metric(np.zeros(3), np.zeros(3)))
            except TypeError as e:
                raise TypeError(
                    "In ga mode, metric must have signature metric(y_true, y_pred)."
                ) from e

        def _eval_ga(individual):
            compiled = gp.compile(expr=individual, pset=self._pset)
            out = compiled() if callable(compiled) else compiled

            lf = df
            if out.pre_cols:
                for name, e in out.pre_cols:
                    lf = lf.with_columns(e.alias(name))

            pred = (
                lf.select(out.expr.alias("__pred__"))
                .to_series()
                .to_numpy()
                .astype(float, copy=False)
            )

            mask = np.isfinite(pred) & np.isfinite(y_np)
            if mask.sum() < max(5, int(0.2 * len(y_np))):
                return (1e18,)

            metric_val = self._compute_single_metric(y_np[mask], pred[mask])
            fitness_val = -metric_val if self.maximize_metric else metric_val
            return (fitness_val + self.parsimony_coefficient * len(individual),)

        self._toolbox.register("evaluate", _eval_ga)

        pop = self._toolbox.population(n=self.population_size)
        hof = tools.HallOfFame(maxsize=self.hall_of_fame)

        for ind, fit in zip(pop, map(self._toolbox.evaluate, pop)):
            ind.fitness.values = fit
        hof.update(pop)

        best_hist = [hof[0].fitness.values[0]]
        no_improve = 0

        for _gen in range(1, self.generations + 1):
            offspring = list(map(self._toolbox.clone, self._toolbox.select(pop, len(pop))))

            for c1, c2 in zip(offspring[::2], offspring[1::2]):
                if self._rng.random() < self.cxpb:
                    self._toolbox.mate(c1, c2)
                    del c1.fitness.values, c2.fitness.values

            for mut in offspring:
                if self._rng.random() < self.mutpb:
                    self._toolbox.mutate(mut)
                    del mut.fitness.values

            invalid = [ind for ind in offspring if not ind.fitness.valid]
            for ind, fit in zip(invalid, map(self._toolbox.evaluate, invalid)):
                ind.fitness.values = fit

            pop[:] = offspring
            hof.update(pop)

            cur_best = hof[0].fitness.values[0]
            best_hist.append(cur_best)

            if self.early_stop_rounds is not None:
                if len(best_hist) >= 2 and (best_hist[-2] - best_hist[-1]) <= self.early_stop_tol:
                    no_improve += 1
                else:
                    no_improve = 0
                if no_improve >= self.early_stop_rounds:
                    break

        self.hof_ = hof
        self.best_programs_ = [str(ind) for ind in hof]
        self.best_feature_names_ = self._dedupe_names(
            [self._sanitize_feature_name(self._individual_to_symbolic(ind)) for ind in hof]
        )
        self.best_fitness_ = [float(ind.fitness.values[0]) for ind in hof]

        self._fitted = True
        return self

    # -------------------------
    # transform(): keep your existing logic, but in ga_hill_climb we emit selected HC features
    # -------------------------
    def transform(self, X: Any) -> pl.DataFrame:
        df = self._to_polars(X)
        if self._te_maps and self._te_target_col is not None:
            df = self._apply_target_encoders(df)

        self._ensure_deap()

        if self.search_mode in ("hill_climb", "ga_hill_climb"):
            if not getattr(self, "_hc_selected_inds_", None):
                raise RuntimeError("Call fit(X, y) before transform().")

            names = getattr(self, "selected_feature_names_", None)
            if not names:
                raw = [self._individual_to_symbolic(ind) for ind in self._hc_selected_inds_]
                names = self._dedupe_names([self._sanitize_feature_name(s) for s in raw])

            lf = df.lazy()
            for ind, nm in zip(self._hc_selected_inds_, names):
                out = self._compile_to_numexpr(ind)
                if out.pre_cols:
                    for name, e in out.pre_cols:
                        lf = lf.with_columns(e.alias(name))
                lf = lf.with_columns(out.expr.alias(nm))

            out_df = lf.collect()
            base_cols = list(self.index_cols) + [c for c in self.numeric_cols if c in out_df.columns]
            return out_df.select(base_cols + list(names))

        # pure GA: emit HOF
        if self.hof_ is None:
            raise RuntimeError("Call fit(X, y) before transform().")

        names = getattr(self, "best_feature_names_", None)
        if not names:
            raw = [self._individual_to_symbolic(ind) for ind in self.hof_]
            names = self._dedupe_names([self._sanitize_feature_name(s) for s in raw])

        lf = df.lazy()
        for ind, nm in zip(self.hof_, names):
            compiled = gp.compile(expr=ind, pset=self._pset)
            out = compiled() if callable(compiled) else compiled
            if getattr(out, "pre_cols", None):
                for name, e in out.pre_cols:
                    lf = lf.with_columns(e.alias(name))
            lf = lf.with_columns(out.expr.alias(nm))

        out_df = lf.collect()
        base_cols = list(self.index_cols) + [c for c in self.numeric_cols if c in out_df.columns]
        return out_df.select(base_cols + list(names))



    def _compile_to_numexpr(self, individual) -> NumE:
        self._ensure_deap()
        compiled = gp.compile(expr=individual, pset=self._pset)
        out = compiled() if callable(compiled) else compiled
        if not isinstance(out, NumE):
            raise TypeError("Program did not compile to NumE.")
        return out


    def _program_to_numpy(self, df: pl.DataFrame, individual) -> np.ndarray:
        out = self._compile_to_numexpr(individual)

        lf = df.lazy()

        if out.pre_cols:
            lf = lf.with_columns_seq([e.alias(name) for name, e in out.pre_cols])

        lf = lf.select(out.expr.alias("__feat__"))

        arr = (
            lf.collect(cluster_with_columns=False)
              .to_series()
              .to_numpy()
              .astype(float, copy=False)
        )
        return arr


    def _to_polars(self, X: Any) -> pl.DataFrame:
        if isinstance(X, pl.DataFrame):
            df = X
        elif pd is not None and isinstance(X, pd.DataFrame):
            df_pd = X.reset_index() if isinstance(X.index, pd.MultiIndex) else X.copy()
            df = pl.from_pandas(df_pd)
        elif isinstance(X, np.ndarray):
            if not self.numeric_cols:
                raise ValueError("If passing a numpy array, you must provide numeric_cols in __init__.")
            if X.shape[1] != len(self.numeric_cols):
                raise ValueError("numpy array column count != len(numeric_cols).")
            df = pl.DataFrame({c: X[:, i] for i, c in enumerate(self.numeric_cols)})
        else:
            raise TypeError(f"Unsupported input type: {type(X)}")

        for c in self.index_cols:
            if c not in df.columns:
                raise ValueError(f"Missing required index column '{c}'.")
        return df


    def _infer_numeric_cols(self, df: pl.DataFrame) -> List[str]:
        if self.numeric_cols:
            return list(self.numeric_cols)
        forbidden = set(self.index_cols) | set(self.categorical_cols)
        return [c for c in df.columns if c not in forbidden]


    def _fit_target_encoders(self, df: pl.DataFrame, target_col: str) -> None:
        self._te_global_mean = float(df.select(pl.col(target_col).mean()).item())
        smooth = float(self.target_encoding_smoothing)
        for cat in self.categorical_cols:
            if cat not in df.columns:
                continue
            tec = self._te_colname(cat, target_col)
            agg = (
                df.group_by(cat, maintain_order=True)
                  .agg(pl.col(target_col).mean().alias("__m"), pl.len().alias("__n"))
                  .with_columns(
                      ((pl.col("__m") * pl.col("__n") + smooth * self._te_global_mean)
                      / (pl.col("__n") + smooth)).alias(tec)
                  )
                  .select([cat, tec])
            )
            self._te_maps[cat] = agg


    def _apply_target_encoders(self, df: pl.DataFrame) -> pl.DataFrame:
        assert self._te_target_col is not None
        assert self._te_global_mean is not None
        out = df
        for cat, mdf in self._te_maps.items():
            tec = self._te_colname(cat, self._te_target_col)
            out = (
                out.join(mdf, on=cat, how="left")
                  .with_columns(pl.col(tec).fill_null(self._te_global_mean))
            )
        return out


    def _dedupe_names(self, names: list[str]) -> list[str]:
        seen = {}
        out = []
        for n in names:
            k = n
            if k in seen:
                seen[k] += 1
                k = f"{k}__{seen[n]}"
            else:
                seen[k] = 0
            out.append(k)
        return out


    def _sanitize_feature_name(self, s: str) -> str:
        s = s.strip()
        s = re.sub(r"\s+", "_", s)
        s = re.sub(r"[^0-9a-zA-Z_()\[\],.=+\-*/|:]", "_", s)
        if len(s) > self.max_colname_len:
            suffix = hex(abs(hash(s)) % (16**6))[2:]
            keep = max(8, self.max_colname_len - (2 + len(suffix)))
            s = f"{s[:keep]}__{suffix}"
        return s