# -*- coding: utf-8 -*-
"""data_drift

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypQkHiK8S-XafRbS7lPHN7Odabqi5Y51
"""

from __future__ import annotations
# Core packages
import numpy as np
import pandas as pd
import scipy.stats

# Scikit-learn components
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from functools import wraps
from sklearn.model_selection import train_test_split

def ensure_2d(func):
    @wraps(func)
    def wrapper(X_train, X_test, *args, **kwargs):
        # Convert pandas objects to numpy if needed
        if hasattr(X_train, "values"):
            X_train_arr = X_train.values
        else:
            X_train_arr = np.asarray(X_train)

        if hasattr(X_test, "values"):
            X_test_arr = X_test.values
        else:
            X_test_arr = np.asarray(X_test)

        # Enforce two dimensions
        if X_train_arr.ndim == 1:
            X_train_arr = X_train_arr.reshape(-1, 1)
        if X_test_arr.ndim == 1:
            X_test_arr = X_test_arr.reshape(-1, 1)

        return func(X_train_arr, X_test_arr, *args, **kwargs)
    return wrapper

def adv_cv(
    model,
    X,
    cv=None,
    categorical_cols=None,
    random_state=42,
    n_splits=5,
    embargo_period=2,
    datetime_level='date',
    ticker_level='ticker'
):
    """
    Evaluate a model using adversarial validation to detect concept drift across time series folds.

    Parameters:
    -----------
    model : estimator object
        The model to evaluate. Must implement fit and predict methods.
    X : pandas.DataFrame
        Features with a MultiIndex of (ticker, date)
    y : pandas.Series or numpy.ndarray
        Target variable
    cv : cross-validator object, default=None
        Cross-validation strategy, defaults to PurgedKFold if None
    categorical_cols : list, default=None
        List of categorical column names
    random_state : int, default=42
        Random seed for reproducibility
    n_splits : int, default=5
        Number of folds for cross-validation
    embargo_period : int, default=2
        Number of days to embargo after each validation set
    datetime_level : str, default='date'
        Name of the datetime level in the MultiIndex
    ticker_level : str, default='ticker'
        Name of the ticker level in the MultiIndex

    Returns:
    --------
    dict
        Dictionary containing adversarial validation scores across folds and averaged probabilities
    """

    # Initialize results storage
    fold_scores = []
    adv_probs_by_fold = {}
    fold_feature_importances = []

    # Apply cross-validation
    for fold, (train_idx, val_idx) in enumerate(cv.split(X)):
        # Split data for this fold
        X_train_fold = X.iloc[train_idx]
        X_val_fold = X.iloc[val_idx]

        c1=X_train_fold.copy()
        c2=X_val_fold.copy()
        # Run adversarial validation on this fold's train/val split
        adv_results = av_tts(
            X_train=X_train_fold,
            X_test=X_val_fold,
            model=model,
        )

        # Skip failed folds
        if isinstance(adv_results, float) and np.isnan(adv_results):
            print(f"Fold {fold+1} failed, skipping")
            continue

        # Store results for this fold
        fold_scores.append(adv_results['avg_score'])

    # Calculate average scores across folds
    avg_score = np.mean(fold_scores) if fold_scores else np.nan

    return avg_score

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression



def _predict_proba_smart(model, X) -> np.ndarray:
    """
    Return 'probability of class 1' for a wide range of sklearn-like models.

    Preference order:
    1. model.predict_proba
       - If binary: return P(y=1)
       - If multiclass: try P(y=1), else max probability.
    2. model.decision_function
       - Convert scores to (0,1) via logistic transform for a 'probability-like' score.
    3. model.predict
       - Use hard labels (0/1) as degenerate probabilities.

    Always returns a 1D float array of shape (n_samples,).
    """

    X = np.asarray(X)

    # 1) True probabilities if available
    if hasattr(model, "predict_proba"):
        proba = np.asarray(model.predict_proba(X))

        # If already 1D, just ensure float
        if proba.ndim == 1:
            return proba.astype(float)

        n_classes = proba.shape[1]

        # Try to locate class "1" explicitly, if we know classes_
        if hasattr(model, "classes_"):
            classes = list(getattr(model, "classes_", []))
            if 1 in classes:
                pos_idx = classes.index(1)
                return proba[:, pos_idx].astype(float)

        # Fallbacks:
        if n_classes == 2:
            # Standard binary convention: column 1 is "positive"
            return proba[:, 1].astype(float)

        # Multiclass & no explicit class 1: use max probability as 'positiveness'
        return proba.max(axis=1).astype(float)

    # 2) Decision function (e.g., linear SVM, logistic regression w/o predict_proba)
    if hasattr(model, "decision_function"):
        scores = np.asarray(model.decision_function(X))

        # Binary: 1D decision scores
        if scores.ndim == 1:
            # Map scores to (0, 1) using logistic transform
            return 1.0 / (1.0 + np.exp(-scores))

        # Multiclass: scores shape (n_samples, n_classes)
        n_classes = scores.shape[1]
        if hasattr(model, "classes_"):
            classes = list(getattr(model, "classes_", []))
            if 1 in classes:
                pos_idx = classes.index(1)
                s = scores[:, pos_idx]
            elif n_classes == 2:
                # fall back to second column if binary
                s = scores[:, 1]
            else:
                # otherwise, take the max score as a proxy
                s = scores.max(axis=1)
        else:
            # No classes_: treat max as "positiveness"
            if n_classes == 2:
                s = scores[:, 1]
            else:
                s = scores.max(axis=1)

        return 1.0 / (1.0 + np.exp(-s))

    # 3) Fallback: just use predictions as probabilities (0 or 1)
    if hasattr(model, "predict"):
        preds = np.asarray(model.predict(X))

        if preds.ndim == 1:
            return preds.astype(float)

        # Occasionally predictors output one-hot-style arrays
        if preds.ndim == 2 and preds.shape[1] == 2:
            return preds[:, 1].astype(float)

    raise TypeError(
        f"Model of type {type(model)!r} does not support probability or score "
        "prediction via predict_proba, decision_function, or predict()."
    )


@ensure_2d
def av_tts(
    x_train: np.ndarray | pd.DataFrame,
    x_test:  np.ndarray | pd.DataFrame,
    model: Any | None = None,
    metric=roc_auc_score,
    test_size: float = 0.30,
    random_state: Optional[int] = 42,
    stratify: bool = True,
    feature_names: Optional[list[str]] = None,
    **kwargs: Any,  # absorb unused extras for compatibility
) -> dict:

    # Coerce to arrays, preserve/resolve feature names if possible
    if isinstance(x_train, pd.DataFrame):
        X_tr = x_train.values
        cols = list(x_train.columns)
    else:
        X_tr = np.asarray(x_train)
        cols = None

    if isinstance(x_test, pd.DataFrame):
        X_te = x_test.values
        if cols is None:
            cols = list(x_test.columns)
    else:
        X_te = np.asarray(x_test)

    if feature_names is None and cols is not None:
        feature_names = cols

    # Build domain-labeled dataset: 0 = source(train), 1 = target(test)
    n_tr, n_te = len(X_tr), len(X_te)
    X_adv = np.vstack([X_tr, X_te])
    y_adv = np.r_[np.zeros(n_tr, dtype=int), np.ones(n_te, dtype=int)]

    # Train/validation split on the concatenated dataset
    stratify_vec = y_adv if stratify else None
    idx = np.arange(len(X_adv))
    tr_idx, va_idx = train_test_split(
        idx,
        test_size=float(test_size),
        random_state=random_state,
        stratify=stratify_vec,
        shuffle=True,
    )

    X_tr_split, y_tr_split = X_adv[tr_idx], y_adv[tr_idx]
    X_va_split, y_va_split = X_adv[va_idx], y_adv[va_idx]

    # Prepare model
    if model is None:
        model = LogisticRegression()

    mdl = _safe_clone(model)
    _maybe_set_random_state(mdl, random_state)

    # Fit and evaluate
    mdl.fit(X_tr_split, y_tr_split)
    val_probs = _predict_proba_smart(mdl, X_va_split)
    # Threshold at 0.5 for binary preds
    val_preds = (val_probs >= 0.5).astype(int)
    score = float(metric(y_va_split, val_probs))

    out = {
        "avg_score": score,
        "val_probs": np.asarray(val_probs, dtype=float),
        "val_preds": np.asarray(val_preds, dtype=int),
        'models': [mdl]
    }

    return out

from typing import Any, Optional


def _safe_clone(estimator: Any | None) -> Any | None:
    """
    Best-effort 'safe' clone of an estimator-like object.

    - If sklearn is available, use sklearn.base.clone (resets fitted state).
    - Otherwise, if the object exposes get_params, re-instantiates the class
      with those params.
    - Returns None unchanged.
    """
    if estimator is None:
        return None

    # Prefer sklearn.clone if available (handles Pipelines, meta-estimators, etc.)
    try:
        from sklearn.base import clone as sk_clone  # type: ignore
        return sk_clone(estimator)
    except Exception:
        pass  # fall back to a simple get_params-based clone

    # Generic fallback for estimator-like objects
    if hasattr(estimator, "get_params"):
        params = estimator.get_params(deep=True)
        return estimator.__class__(**params)

    # At this point we don't know how to clone without copying learned state.
    raise TypeError(
        f"Cannot safely clone object of type {type(estimator)!r}; "
        "no sklearn.clone and no get_params() found."
    )


def _maybe_set_random_state(
    obj: Any | None,
    random_state: Optional[int] = None,
) -> Any | None:
    """
    Set random_state on estimator-like objects *if* possible.

    - If random_state is None or obj is None, it's a no-op.
    - Handles:
        * single estimators
        * lists / tuples of estimators
        * dicts of estimators
    - Tries set_params(random_state=...), then falls back to attribute assignment
      if a .random_state attribute exists.
    """
    if obj is None or random_state is None:
        return obj

    # Containers: apply recursively
    if isinstance(obj, (list, tuple)):
        for est in obj:
            _maybe_set_random_state(est, random_state)
        return obj

    if isinstance(obj, dict):
        for est in obj.values():
            _maybe_set_random_state(est, random_state)
        return obj

    # Estimator-like object
    # 1) Try sklearn-style set_params
    if hasattr(obj, "set_params"):
        try:
            obj.set_params(random_state=random_state)
            return obj
        except (TypeError, ValueError):
            # Not all estimators expose random_state in set_params
            pass

    # 2) Fall back to direct attribute if present
    if hasattr(obj, "random_state"):
        try:
            setattr(obj, "random_state", random_state)
        except Exception:
            pass

    return obj


from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression


@ensure_2d
def adversarial_validation(X_train, X_test, model=None, metric=roc_auc_score,random_state=42,n_splits=5):
    """
    Perform adversarial validation to detect distribution shift between X_train and X_test.
    Assigns label 0 to X_train, label 1 to X_test, then trains a classifier to predict the label.

    Parameters
    ----------
    X_train : array-like
        Training feature matrix.
    X_test : array-like
        Test feature matrix.
    model : sklearn-like estimator, optional
        Classifier with .fit() and .predict_proba().
    metric : callable, optional
        Scoring function (default is roc_auc_score).

    Returns
    -------
    results : dict
        Dictionary with average score and fold-level predictions.
    """
    # Create adversarial labels
    y_train_adv = np.zeros(len(X_train))
    y_test_adv = np.ones(len(X_test))

    X_adv = np.vstack((X_train, X_test))
    y_adv = np.concatenate((y_train_adv, y_test_adv))

    # Default model
    if model is None:
        model = LogisticRegression()

    prob_scores_lst = []
    pred_scores_lst = []
    scores = []
    models=[]

    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    val_probs_all = np.full(len(X_adv), np.nan)  # to store out-of-fold probabilities
    val_preds_all = np.full(len(X_adv), np.nan)  # optional, for predicted classes

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_adv, y_adv)):
        X_train_cv, X_val_cv = X_adv[train_idx], X_adv[val_idx]
        y_train_cv, y_val_cv = y_adv[train_idx], y_adv[val_idx]

        clf = model
        clf.fit(X_train_cv, y_train_cv)
        models.append(clf)

        val_probs = clf.predict_proba(X_val_cv)[:, 1]
        val_preds = clf.predict(X_val_cv)

        val_probs_all[val_idx] = val_probs
        val_preds_all[val_idx] = val_preds

        score = metric(y_val_cv, val_probs)
        scores.append(score)

    results = {
    'avg_score': np.mean(scores),
    'std_score': np.std(scores),
    'kurt_score': scipy.stats.kurtosis(scores),
    'skew_score': scipy.stats.skew(scores),
    'val_probs_all': val_probs_all,
    'val_preds_all': val_preds_all,
    'models': models
    }

    return results

from sklearn.base import clone

def adversarial_validation_with_permutation(
    x_train: np.ndarray | pd.DataFrame,
    x_test:  np.ndarray | pd.DataFrame,
    model,
    *,
    n_perm: int = 200,
    perm_random_state: int = 123,
    random_state: int = 42
):

    # Coerce to numpy for grouping; keep a DataFrame for the helper calls
    X_tr = x_train.values if isinstance(x_train, pd.DataFrame) else np.asarray(x_train)
    X_te = x_test.values  if isinstance(x_test,  pd.DataFrame) else np.asarray(x_test)
    X = np.vstack([X_tr, X_te])
    y = np.r_[np.zeros(len(X_tr), dtype=int), np.ones(len(X_te), dtype=int)]

    # ----- Observed (original grouping) -----
    obs = adversarial_validation(
        pd.DataFrame(X_tr),
        pd.DataFrame(X_te),
        model=clone(model),
        return_models=True
    )
    observed_score = float(obs["avg_score"])

    # Average feature importances across observed models (if supported)
    feat_imps = None
    models = obs.get("models", None)
    if models:
        imps = []
        for m in models:
            if hasattr(m, "feature_importances_"):
                imps.append(m.feature_importances_)
        if len(imps) > 0:
            feat_imps = np.mean(np.vstack(imps), axis=0)

    # ----- Permutation null -----
    rng = np.random.default_rng(perm_random_state)
    null_scores = []
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        # Rebuild groups by permuted labels
        X0 = pd.DataFrame(X[y_perm == 0])
        X1 = pd.DataFrame(X[y_perm == 1])

        res = adversarial_validation(
            X0, X1,
            model=clone(model)
        )
        null_scores.append(float(res["avg_score"]))

    null_scores = np.array(null_scores, dtype=float)
    # Guard in case all permutations were degenerate (should be rare)
    if null_scores.size == 0:
        return {
            "observed_score": observed_score,
            "null_scores": np.array([]),
            "p_value": 1.0,
            "null_mean": np.nan,-
            "null_std": np.nan,
            "z": np.nan,
            "feature_importances": feat_imps
        }

    # ----- Stats (two-sided around 0.5) -----
    dist_obs = abs(observed_score - 0.5)
    dist_null = np.abs(null_scores - 0.5)
    p_value = (np.sum(dist_null >= dist_obs) + 1) / (len(null_scores) + 1)

    null_mean = float(null_scores.mean())
    null_std  = float(null_scores.std(ddof=1))
    z = (observed_score - null_mean) / null_std if null_std > 0 else float("nan")
    ecdf = np.mean(null_scores <= observed_score)   # in [0, 1]

    drift_strength = 2.0 * abs(ecdf - 0.5)

    raw_effect = 2.0 * abs(observed_score - 0.5)  # 0–1
    composite = raw_effect * drift_strength       # 0–1

    return {
        "observed_score": observed_score,
        "null_scores": null_scores,
        "p_value": p_value,
        "null_mean": null_mean,
        "null_std": null_std,
        "z": z,
        "feature_importances": feat_imps,
        'ecdf': ecdf,
        'penalty': composite
    }

try:
    import hdbscan
except ImportError as e:
    raise ImportError("Please install hdbscan: pip install hdbscan") from e

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils.validation import check_is_fitted
from scipy.stats import rankdata


def _spearman_corr_df(X_df: pd.DataFrame) -> pd.DataFrame:
    """Spearman (via Pearson on ranks) with tie handling; symmetric DataFrame."""
    ranks = X_df.apply(
        lambda col: pd.Series(rankdata(col, method="average"), index=X_df.index),
        axis=0,
    )
    return ranks.corr(method="pearson")

def _to_distance_from_corr(corr: np.ndarray, absolute=True) -> np.ndarray:
    """Distance = |1 - corr| with NaNs→1.0, clipped to [0,2], zero diag."""
    C = np.array(corr, dtype=float)
    if absolute:
        C = np.abs(C)
    D = np.abs(1.0 - C)
    D = np.where(np.isnan(D), 1.0, D)
    D = np.clip(D, 0.0, 2.0)
    np.fill_diagonal(D, 0.0)
    return D


def _avg_intercluster_distance(D: np.ndarray, A: list[int], B: list[int]) -> float:
    """Average pairwise distance between two index sets A and B."""
    if len(A) == 0 or len(B) == 0:
        return np.inf
    return D[np.ix_(A, B)].mean()


def _merge_clusters_until_k(D: np.ndarray, clusters: list[list[int]], k: int) -> list[list[int]]:
    """
    Greedily merge the pair of clusters with the smallest average inter-cluster distance
    until len(clusters) <= k. Operates on index lists; returns new list of clusters.
    """
    if k is None or k < 1:
        return clusters
    clusters = [sorted(c) for c in clusters if len(c) > 0]
    if len(clusters) <= k:
        return clusters

    # Precompute a distance matrix between current clusters
    # We’ll rebuild rows/cols as merges happen (small N; features count drives earlier step anyway).
    while len(clusters) > k:
        n = len(clusters)
        best_i = best_j = None
        best_d = np.inf
        for i in range(n):
            for j in range(i + 1, n):
                d = _avg_intercluster_distance(D, clusters[i], clusters[j])
                if d < best_d:
                    best_d, best_i, best_j = d, i, j
        # Merge the closest pair
        merged = sorted(clusters[best_i] + clusters[best_j])
        # Rebuild cluster list
        new_clusters = []
        for t, cl in enumerate(clusters):
            if t not in (best_i, best_j):
                new_clusters.append(cl)
        new_clusters.append(merged)
        clusters = new_clusters
    return clusters

class HDBSCANClusterFeatureSelector(BaseEstimator, TransformerMixin):
    """
    Cluster features via HDBSCAN on a precomputed distance matrix built from
    Spearman rank correlation: D = |1 - rho_s|. Select one representative feature per cluster.

    New:
    ----
    max_k : int or None
        If provided, post-process clusters by greedily merging the closest clusters
        (average linkage on D) until the number of clusters <= max_k.

    Other params are unchanged from your previous class.
    """

    def __init__(
        self,
        min_cluster_size=None,
        min_samples=None,
        cluster_selection_method="eom",
        selection_strategy="medoid",
        scorer=None,
        absolute_correlation=True,
        metric="spearman",
        allow_noise=True,
        random_state=None,
        max_k=None,
    ):
        self.min_cluster_size = min_cluster_size
        self.min_samples = min_samples
        self.cluster_selection_method = cluster_selection_method
        self.selection_strategy = selection_strategy
        self.scorer = scorer
        self.absolute_correlation = absolute_correlation
        self.metric = metric
        self.allow_noise = allow_noise
        self.random_state = random_state
        self.max_k = max_k

    def fit(self, X, y=None):
        # Preserve DataFrame columns if present
        self.columns_ = list(X.columns) if isinstance(X, pd.DataFrame) else None
        X_df = pd.DataFrame(X) if not isinstance(X, pd.DataFrame) else X

        if self.metric != "spearman":
            raise ValueError("Only 'spearman' is supported per the project instructions.")

        # 1) Spearman correlation across features
        corr_df = _spearman_corr_df(X_df)

        # 2) Distance = |1 - rho|
        D = _to_distance_from_corr(corr_df.values, absolute=self.absolute_correlation)
        self.distance_ = D

        n_features = D.shape[0]
        mcs = self.min_cluster_size if self.min_cluster_size is not None else max(
            2, int(np.sqrt(n_features))
        )

        # 3) HDBSCAN clustering on precomputed distances (features as samples)
        clusterer = hdbscan.HDBSCAN(
            metric="precomputed",
            min_cluster_size=mcs,
            min_samples=self.min_samples,
            cluster_selection_method=self.cluster_selection_method,
            cluster_selection_epsilon=0.0,
            allow_single_cluster=False,
            core_dist_n_jobs=1,
            gen_min_span_tree=False,
        )
        base_labels = clusterer.fit_predict(D)

        # 4) Build initial cluster lists (include noise as singleton if allowed, else drop)
        clusters = {}
        for j, c in enumerate(base_labels):
            if c == -1 and not self.allow_noise:
                continue
            cid = c if c != -1 else f"noise_{j}"
            clusters.setdefault(cid, []).append(j)

        # Convert to list of index lists for max_k merging
        cluster_lists = list(clusters.values())

        # 5) Enforce max_k via greedy merging (if needed)
        if self.max_k is not None:
            cluster_lists = _merge_clusters_until_k(self.distance_, cluster_lists, int(self.max_k))

        # Reindex cluster ids to simple integers after merging
        self.clusters_ = {i: cl for i, cl in enumerate(cluster_lists)}

        # 6) Representative selection (medoid or scorer-based)
        self.medoids_ = {}
        reps = []
        n_features = D.shape[0]
        colnames = self.columns_ if self.columns_ is not None else list(range(n_features))

        for cid, idxs in self.clusters_.items():
            if len(idxs) == 1:
                rep = idxs[0]
                self.medoids_[cid] = rep
                reps.append(rep)
                continue

            if self.selection_strategy == "best_scorer" and callable(self.scorer) and y is not None:
                best_score, best_idx = -np.inf, None
                for j in idxs:
                    xj = X_df[colnames[j]].values
                    try:
                        s = float(self.scorer(xj, y))
                    except Exception:
                        s = -np.inf
                    if s > best_score:
                        best_score, best_idx = s, j
                rep = best_idx if best_idx is not None else idxs[0]
                # also compute medoid
                intra = D[np.ix_(idxs, idxs)]
                medoid = idxs[np.argmin(intra.mean(axis=1))]
                self.medoids_[cid] = medoid
                reps.append(rep)
            else:
                intra = D[np.ix_(idxs, idxs)]
                medoid = idxs[np.argmin(intra.mean(axis=1))]
                self.medoids_[cid] = medoid
                reps.append(medoid)

        # 7) Finalize selected features list
        if self.columns_ is not None:
            self.selected_features_ = [self.columns_[j] for j in reps]
        else:
            self.selected_features_ = reps

        # 8) Export labels_ compatible with sklearn convention (noise = -1)
        # Map features to cluster labels; merged clusters get new integer ids.
        labels = np.full(n_features, -1, dtype=object)
        for cid, idxs in self.clusters_.items():
            for j in idxs:
                labels[j] = cid
        self.labels_ = np.array(labels)

        return self

    def transform(self, X):
        check_is_fitted(self, "selected_features_")
        if isinstance(X, pd.DataFrame):
            return X.loc[:, self.selected_features_]
        if self.columns_ is None and all(isinstance(f, int) for f in self.selected_features_):
            return np.asarray(X)[:, self.selected_features_]
        X_df = pd.DataFrame(X, columns=self.columns_)
        return X_df.loc[:, self.selected_features_].values

    def fit_transform(self, X, y=None):
        return self.fit(X, y).transform(X)

    def cluster_summary(self):
        """List of dicts: {cluster_id, size, representative, members} (uses column names if available)."""
        check_is_fitted(self, "clusters_")
        out = []
        for cid, idxs in self.clusters_.items():
            rep_idx = self.medoids_.get(cid, idxs[0])
            if self.columns_ is not None:
                members = [self.columns_[j] for j in idxs]
                representative = self.columns_[rep_idx]
            else:
                members = idxs
                representative = rep_idx
            out.append(
                {
                    "cluster_id": cid,
                    "size": len(idxs),
                    "representative": representative,
                    "members": members,
                }
            )
        return out

import math
from scipy.sparse import diags
from sklearn.cluster import AgglomerativeClustering

def calc_max_min_seg_len(T: int, n_clusters: int) -> int:
    """
    Compute the maximum valid min_seg_len given:
      - T          : number of rows in eigvec_df
      - n_clusters : desired number of clusters

    Clustering is possible iff:
        ceil(T / min_seg_len) >= max(2, n_clusters)

    Returns
    -------
    int
        Maximum allowable min_seg_len (>= 1).

    Raises
    ------
    ValueError
        If it is mathematically impossible to satisfy the constraints
        (i.e., T too small for the requested n_clusters).
    """
    if T < 2:
        raise ValueError(f"T must be >= 2, got {T}.")

    B = max(2, n_clusters)

    if B > T:
        raise ValueError(
            "Impossible clustering configuration.\n"
            f"  T          : {T}\n"
            f"  n_clusters : {n_clusters}\n\n"
            "Need at least T >= max(2, n_clusters)."
        )

    return (T - 1) // (B - 1)

def build_regimes_from_clustering(
    eigvec_df: pd.DataFrame,
    n_clusters: int,
    min_seg_len: int = 'auto',
):
    """
    Create regime definitions with a minimum segment length by clustering
    over block representatives (no averaging).
    """

    # Index must be datetime
    dates = pd.to_datetime(eigvec_df.index)
    eigvec_df = eigvec_df.copy()
    eigvec_df.index = dates


    X = eigvec_df.fillna(-1).values
    T = X.shape[0]
    if T == 0:
        return []

    # ---------------------------------------------------------
    # 1) Create blocks of length >= min_seg_len
    # ---------------------------------------------------------
    T = len(eigvec_df)
    if min_seg_len=='auto':
      min_seg_len = calc_max_min_seg_len(T, n_clusters)

    block_ids = np.arange(T) // min_seg_len
    n_blocks = block_ids[-1] + 1

    B = max(2, n_clusters)
    max_min_seg_len = (T - 1) // (B - 1)

    assert 1 <= min_seg_len <= max_min_seg_len, (
        "Invalid min_seg_len.\n"
        f"  T (rows)           : {T}\n"
        f"  n_clusters         : {n_clusters}\n"
        f"  min_seg_len (given): {min_seg_len}\n\n"
        "Required bounds:\n"
        f"  1 <= min_seg_len <= {max_min_seg_len}\n"
    )

    # ---------------------------------------------------------
    # 2) Pick one representative from each block
    #    (first timestamp in each block)
    # ---------------------------------------------------------
    rep_indices = []
    for b in range(n_blocks):
        first_idx = np.where(block_ids == b)[0][0]
        rep_indices.append(first_idx)

    X_block = X[rep_indices]  # shape (n_blocks, D)

    # ---------------------------------------------------------
    # 3) Chain connectivity between neighboring blocks
    # ---------------------------------------------------------
    connectivity = diags(
        [1, 1],
        offsets=[-1, 1],
        shape=(n_blocks, n_blocks)
    )

    # ---------------------------------------------------------
    # 4) Cluster the representatives
    # ---------------------------------------------------------
    model = AgglomerativeClustering(
        n_clusters=n_clusters,
        linkage="ward",
        connectivity=connectivity
    )
    block_labels = model.fit_predict(X_block)

    # ---------------------------------------------------------
    # 5) Expand block labels back to the full timeline
    # ---------------------------------------------------------
    labels_full = block_labels[block_ids]

    # ---------------------------------------------------------
    # 6) Convert contiguous runs into regime tuples
    # ---------------------------------------------------------
    regimes = []
    current = labels_full[0]
    start_idx = 0
    regime_id = 0

    for i in range(1, T):
        if labels_full[i] != current:
            start = dates[start_idx]
            end = dates[i - 1]
            regimes.append((regime_id, start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")))
            regime_id += 1

            current = labels_full[i]
            start_idx = i

    # last regime
    start = dates[start_idx]
    end = dates[T - 1]
    regimes.append((regime_id, start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")))

    return regimes

from sklearn.ensemble import IsolationForest
from scipy.stats import ks_2samp
from numpy.random import choice

class IsolationForestSubSampler:
    """
    Subsamples rows using IsolationForest anomaly scores while preserving the
    distribution of anomaly scores, using the same logic as BorutaShap.find_sample.

    Workflow
    --------
    1. Fit an IsolationForest on X (optionally with sample_weight).
    2. Compute anomaly scores via score_samples(X).
    3. Iteratively:
        - Draw a random subset of size k (starting at ~10% of data).
        - Compare the distribution of scores in the subset vs. full set using KS test.
        - If p-value > ks_pvalue_threshold, accept that subset.
        - Otherwise, after max_draws_per_size tries, increase subset size by step_percent.
    4. Expose sampled indices and sampled data.
    """

    def __init__(self,
                 ks_pvalue_threshold: float = 0.95,
                 max_draws_per_size: int = 20,
                 step_percent: float = 5.0,
                 random_state: int | None = None,
                 isolation_forest_kwargs: dict | None = None):
        """
        Parameters
        ----------
        ks_pvalue_threshold : float
            P-value threshold for KS test between full and sample score distributions.
            Must be in (0, 1). Default is 0.95 (same as in BorutaShap).

        max_draws_per_size : int
            Number of random draws to attempt at a given sample size before
            increasing the sample size. Mirrors the `iteration == 20` logic.

        step_percent : float
            Step size in percent for candidate sample sizes. The original logic uses
            fixed 5% increments (5%, 10%, 15%, ...). Here we keep that default.

        random_state : int or None
            Random state passed to IsolationForest and used for sampling indices.

        isolation_forest_kwargs : dict or None
            Extra keyword arguments forwarded to IsolationForest.
        """
        if not (0.0 < ks_pvalue_threshold < 1.0):
            raise ValueError("ks_pvalue_threshold must be in (0, 1).")

        self.ks_pvalue_threshold = ks_pvalue_threshold
        self.max_draws_per_size = max_draws_per_size
        self.step_percent = step_percent
        self.random_state = random_state
        self.isolation_forest_kwargs = isolation_forest_kwargs or {}

        # Attributes filled after fit
        self.iforest_ = None
        self.scores_ = None           # anomaly scores for all rows
        self.sample_indices_ = None   # indices of chosen sample
        self.n_samples_ = None

    # ---------------------------------------------------------------------
    # Internal helpers – mirror the BorutaShap implementation
    # ---------------------------------------------------------------------
    @staticmethod
    def _get_percent(num, percent):
        """Generic percent helper (BorutaShap.get_5_percent is a special case)."""
        return round(percent / 100.0 * num)

    def _get_percent_splits(self, length: int):
        """
        Splits into step_percent intervals, e.g.
        5% increments: [5%, 10%, 15%, ...] * length

        Mirrors BorutaShap.get_5_percent_splits but with configurable percent.
        """
        if length <= 1:
            return np.array([length], dtype=int)

        base = self._get_percent(length, self.step_percent)
        base = max(base, 1)  # at least 1 row
        return np.arange(base, length, base)

    def _find_sample_indices(self) -> np.ndarray:
        """
        Implements the same sampling logic as BorutaShap.find_sample:

        - Compute candidate sizes: step_percent, 2*step_percent, ...
        - For each size, try 'max_draws_per_size' random subsamples.
        - Use KS-test on scores to check similarity.
        - Return indices of first subsample with KS p-value > threshold.
        """
        if self.scores_ is None:
            raise RuntimeError("You must call fit(X, ...) before sampling.")

        n = self.scores_.shape[0]
        if n == 0:
            raise ValueError("Cannot subsample an empty dataset.")

        # Candidate sizes in percent increments (as integers)
        size_candidates = self._get_percent_splits(n)
        if size_candidates.size == 0:
            # fallback: sample all rows
            return np.arange(n)

        # For reproducibility of choice()
        rng = np.random.default_rng(self.random_state)

        element = 1  # start at ~2 * step_percent, as in original code (index 1)
        iteration = 0

        # Ensure we start in-bounds
        element = min(element, size_candidates.size - 1)

        while True:
            current_size = size_candidates[element]

            # Draw candidate subsample
            sample_indices = rng.choice(
                np.arange(n),
                size=current_size,
                replace=False
            )
            sample_scores = self.scores_[sample_indices]

            # KS test between full and subsample distributions
            pvalue = ks_2samp(self.scores_, sample_scores).pvalue
            if pvalue > self.ks_pvalue_threshold:
                # Good subsample found
                return sample_indices

            iteration += 1

            # After 'max_draws_per_size' tries, move to a larger sample size
            if iteration >= self.max_draws_per_size:
                iteration = 0
                element += 1
                if element >= size_candidates.size:
                    # If we exhausted all sizes without passing the KS test,
                    # fallback to using the largest candidate size.
                    return rng.choice(
                        np.arange(n),
                        size=size_candidates[-1],
                        replace=False
                    )

    # ---------------------------------------------------------------------
    # Public API
    # ---------------------------------------------------------------------
    def fit(self, X, sample_weight=None):
        """
        Fit the IsolationForest on X and compute the subsample indices.

        Parameters
        ----------
        X : pandas.DataFrame or array-like, shape (n_samples, n_features)
            Input data.

        sample_weight : array-like, shape (n_samples,), optional
            Sample weights to pass to IsolationForest.

        Returns
        -------
        self
        """
        # Convert to array for IsolationForest, but keep original index
        if isinstance(X, pd.DataFrame):
            X_array = X.values
            self._index_ = X.index.to_numpy()
        else:
            X_array = np.asarray(X)
            self._index_ = np.arange(X_array.shape[0])

        self.n_samples_ = X_array.shape[0]

        # Fit IsolationForest using same pattern as BorutaShap.isolation_forest
        iforest_params = {
            "random_state": self.random_state,
            **self.isolation_forest_kwargs
        }
        self.iforest_ = IsolationForest(**iforest_params).fit(
            X_array,
            sample_weight=sample_weight
        )
        self.scores_ = self.iforest_.score_samples(X_array)

        # Find representative subsample indices (relative to original index)
        rel_indices = self._find_sample_indices()
        self.sample_indices_ = self._index_[rel_indices]

        return self

    def get_sample_indices(self):
        """
        Return the indices (matching the index of the fitted X if DataFrame)
        of the selected subsample.

        Returns
        -------
        np.ndarray
            1D array of indices.
        """
        if self.sample_indices_ is None:
            raise RuntimeError("Subsample not yet computed. Call fit(X, ...) first.")
        return self.sample_indices_

    def transform(self, X):
        """
        Return the subsampled X, using the indices learned in fit().

        Parameters
        ----------
        X : pandas.DataFrame or array-like
            Data to subsample. Must be aligned with what was passed to fit.

        Returns
        -------
        subsampled_X : same type as X
        """
        if self.sample_indices_ is None:
            raise RuntimeError("Subsample not yet computed. Call fit(X, ...) first.")

        if isinstance(X, pd.DataFrame):
            # Use index-based selection; assumes alignment with fit() call
            return X.loc[self.sample_indices_]
        else:
            X_array = np.asarray(X)
            # Here sample_indices_ are positional if X was an array at fit time
            # or label-based if X was a DataFrame. In the latter case, we stored
            # the original index values, so we need to map back to positions.
            if isinstance(getattr(self, "_index_", None), np.ndarray):
                # Map label indices to positions if needed
                if not np.array_equal(self._index_, np.arange(self._index_.size)):
                    # build mapping from label -> position
                    label_to_pos = {label: pos for pos, label in enumerate(self._index_)}
                    pos_indices = np.array([label_to_pos[i] for i in self.sample_indices_])
                    return X_array[pos_indices]
            return X_array[self.sample_indices_]

    def fit_transform(self, X, sample_weight=None):
        """
        Convenience method: fit and then transform.

        Parameters
        ----------
        X : pandas.DataFrame or array-like
        sample_weight : array-like, optional

        Returns
        -------
        subsampled_X : same type as X
        """
        return self.fit(X, sample_weight=sample_weight).transform(X)

from dataclasses import dataclass
from typing import Optional, Tuple, Iterable, Union
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import KFold

ArrayLike = Union[np.ndarray, pd.DataFrame]

def _to_numpy(X: ArrayLike) -> np.ndarray:
    return X.values if isinstance(X, pd.DataFrame) else np.asarray(X)

def _oof_if_scores(
    X: np.ndarray,
    splitter,
    if_kwargs: dict,
) -> Tuple[np.ndarray, list[IsolationForest]]:
    """
    Compute OOF score_samples for X using IsolationForest and return fitted fold models.
    """
    n = X.shape[0]
    oof_scores = np.empty(n, dtype=float)
    models = []
    for tr_idx, va_idx in splitter.split(X):
        model = IsolationForest(**if_kwargs)
        model.fit(X[tr_idx])
        oof_scores[va_idx] = model.score_samples(X[va_idx])
        models.append(model)
    return oof_scores, models

def _avg_scores_from_models(models: Iterable[IsolationForest], X: np.ndarray) -> np.ndarray:
    """Average score_samples across a list of fitted IsolationForest models."""
    scores = np.column_stack([m.score_samples(X) for m in models])
    return scores.mean(axis=1)

@dataclass
class IFDriftTriadCV(BaseEstimator, TransformerMixin):
    """
    Build 3 leakage-safe features from IsolationForest using CV:

    - score_train_model: scores from models trained only on train folds
    - score_test_model:  scores from models trained only on test folds
    - score_both_model:  OOF scores from CV over concatenated train+test

    Parameters
    ----------
    n_splits_train : int
        Folds for the 'train-only' models (default 5).
    n_splits_test : int
        Folds for the 'test-only' models (default 5).
    n_splits_both : int
        Folds for the 'both' (concatenated) models (default 5).
    splitter_train, splitter_test, splitter_both :
        Optional custom splitters with .split(X) (e.g., TimeSeriesSplit).
        If provided, they override the corresponding n_splits_*.
    if_kwargs : dict
        Keyword args passed to IsolationForest (e.g., n_estimators, random_state, n_jobs, contamination).
        Reasonable defaults are provided if omitted.
    return_pandas : bool
        If True, returns pandas DataFrames with the specified column names; else numpy arrays.

    Notes
    -----
    - No adversarial classifier here—just features.
    - Supports time-aware CV if you pass a TimeSeriesSplit (or your PurgedKFold) as splitters.
    - For cross-domain scoring:
        * Train-models score test by averaging predictions from each train-fold model.
        * Test-models score train by averaging predictions from each test-fold model.
    """
    n_splits_train: int = 5
    n_splits_test: int = 5
    n_splits_both: int = 5
    splitter_train: Optional[object] = None
    splitter_test: Optional[object] = None
    splitter_both: Optional[object] = None
    if_kwargs: Optional[dict] = None
    return_pandas: bool = True

    def __post_init__(self):
        if self.if_kwargs is None:
            # Sensible defaults; adjust as needed.
            self.if_kwargs = dict(
                n_estimators=300,
                max_samples="auto",
                contamination="auto",
                bootstrap=False,
                n_jobs=-1,
                random_state=42,
                verbose=0,
            )

    def _make_splitter(self, fallback_splits: int, provided) -> object:
        if provided is not None:
            return provided
        return KFold(n_splits=fallback_splits, shuffle=True, random_state=self.if_kwargs.get("random_state", 42))

    def fit_transform(
        self,
        X_train: ArrayLike,
        X_test: ArrayLike,
    ) -> Tuple[Union[pd.DataFrame, np.ndarray], Union[pd.DataFrame, np.ndarray]]:
        """
        Returns
        -------
        train_feats, test_feats
            Either DataFrames or ndarrays with columns (or order):
            ['score_train_model','score_test_model','score_both_model']
        """
        Xtr = _to_numpy(X_train)
        Xte = _to_numpy(X_test)

        # --- Splitters
        spl_train = self._make_splitter(self.n_splits_train, self.splitter_train)
        spl_test  = self._make_splitter(self.n_splits_test,  self.splitter_test)
        spl_both  = self._make_splitter(self.n_splits_both,  self.splitter_both)

        # --- 1) Train-only models: OOF for train, avg for test
        s_tr_oof, tr_models = _oof_if_scores(Xtr, spl_train, self.if_kwargs)
        s_tr_on_te = _avg_scores_from_models(tr_models, Xte)

        # --- 2) Test-only models: OOF for test, avg for train
        s_te_oof, te_models = _oof_if_scores(Xte, spl_test, self.if_kwargs)
        s_te_on_tr = _avg_scores_from_models(te_models, Xtr)

        # --- 3) Both (concatenated) models: OOF for all rows
        X_all = np.vstack([Xtr, Xte])
        s_both_oof_all, _ = _oof_if_scores(X_all, spl_both, self.if_kwargs)
        s_both_tr = s_both_oof_all[: Xtr.shape[0]]
        s_both_te = s_both_oof_all[Xtr.shape[0] :]

        # Assemble outputs
        train_cols = np.column_stack([s_tr_oof, s_te_on_tr, s_both_tr])
        test_cols  = np.column_stack([s_tr_on_te, s_te_oof, s_both_te])

        if self.return_pandas:
            train_df = pd.DataFrame(train_cols, columns=["score_train_model","score_test_model","score_both_model"])
            test_df  = pd.DataFrame(test_cols,  columns=["score_train_model","score_test_model","score_both_model"])
            return train_df, test_df
        return train_cols, test_cols

    # For sklearn compatibility (not used here, but handy)
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        raise NotImplementedError("Call fit_transform(X_train, X_test) to build the triad features for both sets.")