# -*- coding: utf-8 -*-
"""modeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119UuLap3cA_xB7s6GmlK4yA4KmjllYbo
"""

import os
import json
import pickle
from pathlib import Path
from typing import List, Optional, Union, Callable, Any, Dict, Tuple

import numpy as np
import pandas as pd
from flaml import AutoML

'''
# -------------------------
# Adapter: "dict-metric" (returns {'score': ...}) -> FLAML custom metric
# Works for metrics like your make_adv_metric(...) output.
# It will call your metric on X = concat(X_train, X_val) where first part is train.
# -------------------------
def wrap_dict_metric_as_flaml_metric(dict_metric: Callable[..., Dict[str, Any]]):
    """
    dict_metric signature expected:
        dict_metric(X, y, sample_weight=None) -> dict with at least 'score' key
    """
    def _flaml_metric(
        X_val,
        y_val,
        estimator,   # not used by adv metric, but kept for FLAML signature
        labels,
        X_train,
        y_train,
        weight_val=None,
        weight_train=None,
        *args,
    ):
        # Build a single X where first n_train rows are "train" and rest "test"
        # This matches your make_adv_metric logic.
        if isinstance(X_train, (pd.DataFrame, pd.Series)):
            X_tr = X_train
        else:
            X_tr = pd.DataFrame(X_train)
        if isinstance(X_val, (pd.DataFrame, pd.Series)):
            X_te = X_val
        else:
            X_te = pd.DataFrame(X_val)

        X_all = pd.concat([X_tr.reset_index(drop=True), X_te.reset_index(drop=True)], axis=0, ignore_index=True)

        res = dict_metric(X_all, None, None)  # y and sample_weight unused for your adv metric
        score = float(res.get("score", 0.0))

        # FLAML minimizes; your metric wants to maximize score => use -score as loss
        loss = -score

        # Log everything else (if present)
        logs = {"score": score}
        for k, v in res.items():
            if k == "score":
                continue
            # keep scalars only in logs
            if isinstance(v, (int, float, np.floating, np.integer)):
                logs[k] = float(v)
        return loss, logs

    return _flaml_metric
'''


# -------------------------
# Persistence helpers
# -------------------------
def _ensure_dir(d: Optional[Union[str, Path]]) -> Optional[Path]:
    if d is None:
        return None
    p = Path(d)
    p.mkdir(parents=True, exist_ok=True)
    return p

def _save_automl_state(save_dir: Path, automl: AutoML, prefix: str = "flaml") -> None:
    pkl_path = save_dir / f"{prefix}_automl.pkl"
    meta_path = save_dir / f"{prefix}_best_meta.json"

    # pickle whole automl (best for inference/reuse)
    with open(pkl_path, "wb") as f:
        pickle.dump(automl, f)

    meta = {
        "best_estimator": getattr(automl, "best_estimator", None),
        "best_loss": getattr(automl, "best_loss", None),
        "best_config": getattr(automl, "best_config", None),
    }
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, default=str)

def _load_automl_state(load_dir: Path, prefix: str = "flaml") -> Optional[AutoML]:
    pkl_path = load_dir / f"{prefix}_automl.pkl"
    if not pkl_path.exists():
        return None
    with open(pkl_path, "rb") as f:
        return pickle.load(f)

# -------------------------
# Main training/prediction function
# -------------------------
def flaml_train_predict(
    x_train: Union[pd.DataFrame, np.ndarray],
    y_train: Union[pd.Series, np.ndarray, list],
    x_test: Union[pd.DataFrame, np.ndarray],
    model_list: List[str],
    time_budget: float,
    task: str = "regression",
    cv=None,                          # custom splitter object or None
    n_splits: int = 5,
    ensemble: bool = True,
    metric: Optional[Union[str, Callable]] = None,
    random_state: int = 42,
    groups=None,

    # NEW
    save_dir: Optional[Union[str, Path]] = None,
    load_dir: Optional[Union[str, Path]] = None,
    save_prefix: str = "flaml",
    warm_start: bool = True,

    # When cv is not None, build test predictions via fold models and return OOF
    return_oof: bool = True,
) -> Tuple[np.ndarray, AutoML, Optional[np.ndarray]]:
    """
    Returns:
        (test_predictions, automl, oof_predictions_or_None)

    Behavior:
    - Uses `load_dir` (if provided and file exists) to warm start via `starting_points`
    - Saves best-so-far state to `save_dir`:
        - after successful fit
        - on KeyboardInterrupt (best-so-far)
    - If `cv` is not None:
        - AutoML search uses your custom splitter (eval_method='cv')
        - Final prediction uses a fold-wise refit using best config (approx "CV OOF" style):
            - produces OOF predictions for train
            - predicts test in each fold and averages
      (This avoids "single refit on all data" and gives you a CV-style final predictor.)
    """

    # normalize types
    if not isinstance(x_train, (pd.DataFrame, pd.Series)):
        x_train = pd.DataFrame(x_train)
    if not isinstance(x_test, (pd.DataFrame, pd.Series)):
        x_test = pd.DataFrame(x_test)
    if not isinstance(y_train, (pd.Series, pd.DataFrame)):
        y_train = pd.Series(y_train)

    save_path = _ensure_dir(save_dir)
    load_path = _ensure_dir(load_dir) if load_dir is not None else None

    # ----- Warm start from previous run (starting_points) -----
    starting_points = None
    if warm_start and load_path is not None:
        prev = _load_automl_state(load_path, prefix=save_prefix)
        if prev is not None:
            # best_config_per_estimator is what you want for starting_points
            b = getattr(prev, "best_config_per_estimator", None)
            if isinstance(b, dict) and len(b) > 0:
                starting_points = b

    # ----- Metric handling -----
    # - If metric is None and regression => spearman FLAML metric
    # - If metric returns dict with "score" => wrap it into FLAML metric
    use_metric = None
    if metric is None and task == "regression":
        use_metric = _spearman_metric
    elif callable(metric):
        # detect "dict metric" by a quick structural check (no execution)
        # user can also directly pass a FLAML-metric with FLAML signature
        use_metric = metric
        if getattr(metric, "__name__", "").startswith("metric") or True:
            # If it's a dict-metric (like make_adv_metric returns),
            # wrap it. We'll decide by attempting a dry-call signature check.
            # Safer: user can pass the dict metric; we wrap it always if it returns dict at runtime.
            # We'll wrap if it *likely* expects (X,y,...) and returns dict.
            use_metric = wrap_dict_metric_as_flaml_metric(metric)
    else:
        use_metric = metric  # string metric name, if you use any

    # ----- AutoML settings -----
    automl = AutoML()
    automl_settings = {
        "time_budget": time_budget,
        "task": task,
        "log_file_name": "flaml.log",
        "estimator_list": model_list,
        "eval_method": "cv",
        "seed": random_state,
        "verbose": 1,
        "ensemble": ensemble,
        "metric": use_metric,
    }

    if starting_points is not None:
        automl_settings["starting_points"] = starting_points

    if cv is not None:
        automl_settings["split_type"] = cv
        # FLAML will use cv.get_n_splits() if available
    else:
        automl_settings["n_splits"] = n_splits

    # ----- Fit with interrupt-safe saving -----
    try:
        automl.fit(
            X_train=x_train,
            y_train=y_train,
            groups=groups,
            **automl_settings
        )
    except KeyboardInterrupt:
        # Save best-so-far state if possible
        if save_path is not None:
            try:
                _save_automl_state(save_path, automl, prefix=save_prefix)
            except Exception:
                pass
        # Re-raise so you still see it's interrupted (or comment out if you prefer silent)
        raise
    finally:
        # Save after normal completion too
        if save_path is not None:
            try:
                _save_automl_state(save_path, automl, prefix=save_prefix)
            except Exception:
                pass

    # ----- Final predictions -----
    oof_pred = None

    # If custom cv provided: build OOF and test via fold-wise refit using best config.
    # We do this by training a per-fold AutoML restricted to the best estimator and config,
    # with max_iter=1 (effectively "fit this config") and eval_method='holdout'.
    if cv is not None:
        splitter = cv
        n = len(x_train)
        oof_pred = np.full(n, np.nan, dtype=float)
        test_preds = []

        best_estimator = getattr(automl, "best_estimator", None)
        best_config = getattr(automl, "best_config", None)

        if best_estimator is None or best_config is None:
            # fallback: just use the fitted automl on full data
            test_pred = automl.predict(x_test)
            if not return_oof:
                oof_pred = None
            return np.asarray(test_pred), automl, oof_pred

        # fold budget: keep it small; you can adjust formula
        # Ensure >0 to allow the fold model to fit.
        # If you want deterministic "just fit once", max_iter=1 is the real limiter.
        splits = list(splitter.split(x_train, y_train, groups))
        k = len(splits)
        fold_time_budget = max(1.0, float(time_budget) / max(2, k * 5))

        # starting_points for fold fit: must be {estimator: [config]}
        sp_fold = {best_estimator: [best_config]}

        for fold, (tr_idx, va_idx) in enumerate(splits):
            X_tr = x_train.iloc[tr_idx]
            y_tr = y_train.iloc[tr_idx]
            X_va = x_train.iloc[va_idx]

            fold_automl = AutoML()
            fold_settings = {
                "time_budget": fold_time_budget,
                "task": task,
                "seed": random_state + fold,
                "verbose": 0,
                "eval_method": "holdout",
                "estimator_list": [best_estimator],
                "starting_points": sp_fold,
                "metric": use_metric,
                "max_iter": 1,          # key: train the provided config
                "ensemble": False,      # fold model is single best estimator
            }

            # Holdout split inside fold training: keep it simple
            # (It will still train a valid model; we only need it fitted on X_tr.)
            fold_automl.fit(X_train=X_tr, y_train=y_tr, **fold_settings)

            # OOF for this fold
            oof_pred[va_idx] = np.asarray(fold_automl.predict(X_va)).ravel()

            # Test pred for this fold
            test_preds.append(np.asarray(fold_automl.predict(x_test)).ravel())

        test_pred = np.mean(np.vstack(test_preds), axis=0)

        if not return_oof:
            oof_pred = None
        return np.asarray(test_pred), automl, oof_pred

    # Otherwise: standard predict from full-data refit model
    test_pred = automl.predict(x_test)
    return np.asarray(test_pred), automl, None