# -*- coding: utf-8 -*-
"""modeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119UuLap3cA_xB7s6GmlK4yA4KmjllYbo
"""

import os
import json
import pickle
from pathlib import Path
from typing import List, Optional, Union, Callable, Any, Dict, Tuple

import numpy as np
import pandas as pd
from sklearn.base import clone

'''
# -------------------------
# Adapter: "dict-metric" (returns {'score': ...}) -> FLAML custom metric
# Works for metrics like your make_adv_metric(...) output.
# It will call your metric on X = concat(X_train, X_val) where first part is train.
# -------------------------
def wrap_dict_metric_as_flaml_metric(dict_metric: Callable[..., Dict[str, Any]]):
    """
    dict_metric signature expected:
        dict_metric(X, y, sample_weight=None) -> dict with at least 'score' key
    """
    def _flaml_metric(
        X_val,
        y_val,
        estimator,   # not used by adv metric, but kept for FLAML signature
        labels,
        X_train,
        y_train,
        weight_val=None,
        weight_train=None,
        *args,
    ):
        # Build a single X where first n_train rows are "train" and rest "test"
        # This matches your make_adv_metric logic.
        if isinstance(X_train, (pd.DataFrame, pd.Series)):
            X_tr = X_train
        else:
            X_tr = pd.DataFrame(X_train)
        if isinstance(X_val, (pd.DataFrame, pd.Series)):
            X_te = X_val
        else:
            X_te = pd.DataFrame(X_val)

        X_all = pd.concat([X_tr.reset_index(drop=True), X_te.reset_index(drop=True)], axis=0, ignore_index=True)

        res = dict_metric(X_all, None, None)  # y and sample_weight unused for your adv metric
        score = float(res.get("score", 0.0))

        # FLAML minimizes; your metric wants to maximize score => use -score as loss
        loss = -score

        # Log everything else (if present)
        logs = {"score": score}
        for k, v in res.items():
            if k == "score":
                continue
            # keep scalars only in logs
            if isinstance(v, (int, float, np.floating, np.integer)):
                logs[k] = float(v)
        return loss, logs

    return _flaml_metric
'''


# -------------------------
# Persistence helpers
# -------------------------
def _ensure_dir(d: Optional[Union[str, Path]]) -> Optional[Path]:
    if d is None:
        return None
    p = Path(d)
    p.mkdir(parents=True, exist_ok=True)
    return p

def _save_automl_state(save_dir: Path, automl: Any, prefix: str = "flaml") -> None:
    pkl_path = save_dir / f"{prefix}_automl.pkl"
    meta_path = save_dir / f"{prefix}_best_meta.json"

    # pickle whole automl (best for inference/reuse)
    with open(pkl_path, "wb") as f:
        pickle.dump(automl, f)

    meta = {
        "best_estimator": getattr(automl, "best_estimator", None),
        "best_loss": getattr(automl, "best_loss", None),
        "best_config": getattr(automl, "best_config", None),
    }
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, default=str)

def _load_automl_state(load_dir: Path, prefix: str = "flaml") -> Optional[Any]:
    pkl_path = load_dir / f"{prefix}_automl.pkl"
    if not pkl_path.exists():
        return None
    with open(pkl_path, "rb") as f:
        return pickle.load(f)

# -------------------------
# Main training/prediction function
# -------------------------
def flaml_train_predict(
    x_train: Union[pd.DataFrame, np.ndarray],
    y_train: Union[pd.Series, np.ndarray, list],
    x_test: Union[pd.DataFrame, np.ndarray],
    model_list: List[str],
    time_budget: float,
    task: str = "regression",
    cv=None,                          # custom splitter object or None
    n_splits: int = 5,
    ensemble: bool = True,
    metric: Optional[Union[str, Callable]] = None,
    random_state: int = 42,
    groups=None,

    # NEW
    save_dir: Optional[Union[str, Path]] = None,
    load_dir: Optional[Union[str, Path]] = None,
    save_prefix: str = "flaml",
    warm_start: bool = True,

    # When cv is not None, build test predictions via fold models and return OOF
    return_oof: bool = True,
) -> Tuple[np.ndarray, Any, Optional[np.ndarray]]:
    """
    Returns:
        (test_predictions, automl, oof_predictions_or_None)

    Behavior:
    - Uses `load_dir` (if provided and file exists) to warm start via `starting_points`
    - Saves best-so-far state to `save_dir`:
        - after successful fit
        - on KeyboardInterrupt (best-so-far)
    - If `cv` is not None:
        - AutoML search uses your custom splitter (eval_method='cv')
        - Final prediction uses a fold-wise refit using best config (approx "CV OOF" style):
            - produces OOF predictions for train
            - predicts test in each fold and averages
      (This avoids "single refit on all data" and gives you a CV-style final predictor.)
    """

    # normalize types
    if not isinstance(x_train, (pd.DataFrame, pd.Series)):
        x_train = pd.DataFrame(x_train)
    if not isinstance(x_test, (pd.DataFrame, pd.Series)):
        x_test = pd.DataFrame(x_test)
    if not isinstance(y_train, (pd.Series, pd.DataFrame)):
        y_train = pd.Series(y_train)

    save_path = _ensure_dir(save_dir)
    load_path = _ensure_dir(load_dir) if load_dir is not None else None

    # ----- Warm start from previous run (starting_points) -----
    starting_points = None
    if warm_start and load_path is not None:
        prev = _load_automl_state(load_path, prefix=save_prefix)
        if prev is not None:
            # best_config_per_estimator is what you want for starting_points
            b = getattr(prev, "best_config_per_estimator", None)
            if isinstance(b, dict) and len(b) > 0:
                starting_points = b

    # ----- Metric handling -----
    # - If metric is None and regression => spearman FLAML metric
    # - If metric returns dict with "score" => wrap it into FLAML metric
    use_metric = None
    if metric is None and task == "regression":
        use_metric = _spearman_metric
    elif callable(metric):
        # detect "dict metric" by a quick structural check (no execution)
        # user can also directly pass a FLAML-metric with FLAML signature
        use_metric = metric
        if getattr(metric, "__name__", "").startswith("metric") or True:
            # If it's a dict-metric (like make_adv_metric returns),
            # wrap it. We'll decide by attempting a dry-call signature check.
            # Safer: user can pass the dict metric; we wrap it always if it returns dict at runtime.
            # We'll wrap if it *likely* expects (X,y,...) and returns dict.
            use_metric = wrap_dict_metric_as_flaml_metric(metric)
    else:
        use_metric = metric  # string metric name, if you use any

    # ----- AutoML settings -----
    from flaml import AutoML

    automl = AutoML()
    automl_settings = {
        "time_budget": time_budget,
        "task": task,
        "log_file_name": "flaml.log",
        "estimator_list": model_list,
        "eval_method": "cv",
        "seed": random_state,
        "verbose": 1,
        "ensemble": ensemble,
        "metric": use_metric,
    }

    if starting_points is not None:
        automl_settings["starting_points"] = starting_points

    if cv is not None:
        automl_settings["split_type"] = cv
        # FLAML will use cv.get_n_splits() if available
    else:
        automl_settings["n_splits"] = n_splits

    # ----- Fit with interrupt-safe saving -----
    try:
        automl.fit(
            X_train=x_train,
            y_train=y_train,
            groups=groups,
            **automl_settings
        )
    except KeyboardInterrupt:
        # Save best-so-far state if possible
        if save_path is not None:
            try:
                _save_automl_state(save_path, automl, prefix=save_prefix)
            except Exception:
                pass
        # Re-raise so you still see it's interrupted (or comment out if you prefer silent)
        raise
    finally:
        # Save after normal completion too
        if save_path is not None:
            try:
                _save_automl_state(save_path, automl, prefix=save_prefix)
            except Exception:
                pass

    # ----- Final predictions -----
    oof_pred = None

    # If custom cv provided: build OOF and test via fold-wise refit using best config.
    # We do this by training a per-fold AutoML restricted to the best estimator and config,
    # with max_iter=1 (effectively "fit this config") and eval_method='holdout'.
    if cv is not None:
        splitter = cv
        n = len(x_train)
        oof_pred = np.full(n, np.nan, dtype=float)
        test_preds = []

        best_estimator = getattr(automl, "best_estimator", None)
        best_config = getattr(automl, "best_config", None)

        if best_estimator is None or best_config is None:
            # fallback: just use the fitted automl on full data
            test_pred = automl.predict(x_test)
            if not return_oof:
                oof_pred = None
            return np.asarray(test_pred), automl, oof_pred

        # fold budget: keep it small; you can adjust formula
        # Ensure >0 to allow the fold model to fit.
        # If you want deterministic "just fit once", max_iter=1 is the real limiter.
        splits = list(splitter.split(x_train, y_train, groups))
        k = len(splits)
        fold_time_budget = max(1.0, float(time_budget) / max(2, k * 5))

        # starting_points for fold fit: must be {estimator: [config]}
        sp_fold = {best_estimator: [best_config]}

        for fold, (tr_idx, va_idx) in enumerate(splits):
            X_tr = x_train.iloc[tr_idx]
            y_tr = y_train.iloc[tr_idx]
            X_va = x_train.iloc[va_idx]

            fold_automl = AutoML()
            fold_settings = {
                "time_budget": fold_time_budget,
                "task": task,
                "seed": random_state + fold,
                "verbose": 0,
                "eval_method": "holdout",
                "estimator_list": [best_estimator],
                "starting_points": sp_fold,
                "metric": use_metric,
                "max_iter": 1,          # key: train the provided config
                "ensemble": False,      # fold model is single best estimator
            }

            # Holdout split inside fold training: keep it simple
            # (It will still train a valid model; we only need it fitted on X_tr.)
            fold_automl.fit(X_train=X_tr, y_train=y_tr, **fold_settings)

            # OOF for this fold
            oof_pred[va_idx] = np.asarray(fold_automl.predict(X_va)).ravel()

            # Test pred for this fold
            test_preds.append(np.asarray(fold_automl.predict(x_test)).ravel())

        test_pred = np.mean(np.vstack(test_preds), axis=0)

        if not return_oof:
            oof_pred = None
        return np.asarray(test_pred), automl, oof_pred

    # Otherwise: standard predict from full-data refit model
    test_pred = automl.predict(x_test)
    return np.asarray(test_pred), automl, None


class TimeRespectingOutOfSamplePredictor:
    """Generate out-of-sample predictions while respecting temporal ordering."""

    def __init__(self, primary_model, cv):
        self.primary_model = primary_model
        self.cv = cv

    @staticmethod
    def _extract_dates(frame: pd.DataFrame) -> pd.Index:
        if not isinstance(frame.index, pd.MultiIndex):
            raise ValueError("Expected a MultiIndex with a date level.")
        if "date" not in frame.index.names:
            raise ValueError("Expected MultiIndex level named 'date'.")
        return pd.to_datetime(frame.index.get_level_values("date"))

    def fit_predict(self, X: pd.DataFrame, y, prediction_sets: List[pd.DataFrame]):
        if not isinstance(X, pd.DataFrame):
            raise ValueError("X must be a pandas DataFrame.")

        y_series = y if isinstance(y, pd.Series) else pd.Series(y, index=X.index)
        oof_pred = pd.Series(np.nan, index=X.index, dtype=float)
        agg_preds = [pd.Series(0.0, index=pred.index, dtype=float) for pred in prediction_sets]
        counts = [0 for _ in prediction_sets]

        for train_idx, valid_idx in self.cv.split(X, y_series):
            X_train = X.iloc[train_idx]
            y_train = y_series.iloc[train_idx]
            X_valid = X.iloc[valid_idx]

            fitted = clone(self.primary_model)
            fitted.fit(X_train, y_train)
            oof_pred.iloc[valid_idx] = np.asarray(fitted.predict(X_valid)).ravel()

            train_max_date = self._extract_dates(X_train).max()
            for i, pred_set in enumerate(prediction_sets):
                pred_dates = self._extract_dates(pred_set)
                if pred_dates.min() <= train_max_date:
                    continue
                fold_pred = np.asarray(fitted.predict(pred_set)).ravel()
                agg_preds[i] += pd.Series(fold_pred, index=pred_set.index)
                counts[i] += 1

        final_preds = []
        for pred, cnt in zip(agg_preds, counts):
            if cnt == 0:
                final_preds.append(pd.Series(np.nan, index=pred.index, dtype=float))
            else:
                final_preds.append(pred / cnt)

        return oof_pred, final_preds


class MetaLabeler:
    """Meta-label classifier that augments features with primary model predictions."""

    def __init__(self, meta_model, cv, primary_predictions: pd.Series, profit_labels: pd.Series):
        self.meta_model = meta_model
        self.cv = cv
        self.primary_predictions = primary_predictions
        self.profit_labels = profit_labels

    @staticmethod
    def _predict_scores(model, X: pd.DataFrame) -> np.ndarray:
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(X)
            if proba.ndim == 2 and proba.shape[1] > 1:
                return proba[:, 1]
        return np.asarray(model.predict(X)).ravel()

    def _build_meta_features(self, X: pd.DataFrame, primary_preds: pd.Series) -> pd.DataFrame:
        if not X.index.equals(primary_preds.index):
            primary_preds = primary_preds.reindex(X.index)
        if primary_preds.isna().any():
            raise ValueError("Primary predictions contain missing values after alignment.")

        X_meta = X.copy()
        X_meta["primary_prediction"] = primary_preds.values
        return X_meta

    def fit_predict(self, X: pd.DataFrame, y_meta, prediction_sets: List[pd.DataFrame]):
        y_meta_series = y_meta if isinstance(y_meta, pd.Series) else pd.Series(y_meta, index=X.index)
        unique_labels = set(pd.Series(y_meta_series).dropna().unique())
        if not unique_labels.issubset({0, 1}):
            raise ValueError("y_meta must be binary and only contain values {0, 1}.")

        if not X.index.equals(self.profit_labels.index):
            aligned_profit = self.profit_labels.reindex(X.index)
        else:
            aligned_profit = self.profit_labels
        if aligned_profit.isna().any():
            raise ValueError("profit_labels must align with X and cannot contain NaNs.")

        X_meta = self._build_meta_features(X, self.primary_predictions)
        oof_pred = pd.Series(np.nan, index=X.index, dtype=float)
        agg_preds = [pd.Series(0.0, index=pred.index, dtype=float) for pred in prediction_sets]
        counts = [0 for _ in prediction_sets]

        for train_idx, valid_idx in self.cv.split(X_meta, y_meta_series):
            X_train = X_meta.iloc[train_idx]
            y_train = y_meta_series.iloc[train_idx]
            X_valid = X_meta.iloc[valid_idx]

            fitted = clone(self.meta_model)
            fitted.fit(X_train, y_train)
            oof_pred.iloc[valid_idx] = self._predict_scores(fitted, X_valid)

            train_dates = pd.to_datetime(X_train.index.get_level_values("date"))
            train_max_date = train_dates.max()
            for i, pred_set in enumerate(prediction_sets):
                pred_primary = self.primary_predictions.reindex(pred_set.index)
                X_pred_meta = self._build_meta_features(pred_set, pred_primary)
                pred_dates = pd.to_datetime(X_pred_meta.index.get_level_values("date"))
                if pred_dates.min() <= train_max_date:
                    continue
                fold_pred = self._predict_scores(fitted, X_pred_meta)
                agg_preds[i] += pd.Series(fold_pred, index=X_pred_meta.index)
                counts[i] += 1

        final_preds = []
        for pred, cnt in zip(agg_preds, counts):
            if cnt == 0:
                final_preds.append(pd.Series(np.nan, index=pred.index, dtype=float))
            else:
                final_preds.append(pred / cnt)

        return oof_pred, final_preds


class MetaLabelingSimulationPipeline:
    """End-to-end primary -> simulation -> meta-labeling -> simulation pipeline."""

    def __init__(
        self,
        primary_model,
        meta_model,
        cv,
        *,
        top_n_longs: int,
        top_n_shorts: int,
        meta_threshold: float = 0.5,
        simulation_kwargs: Optional[Dict[str, Any]] = None,
        simulate_returns_fn: Optional[Callable[..., Any]] = None,
    ):
        self.primary_model = primary_model
        self.meta_model = meta_model
        self.cv = cv
        self.top_n_longs = int(top_n_longs)
        self.top_n_shorts = int(top_n_shorts)
        self.meta_threshold = float(meta_threshold)
        self.simulation_kwargs = simulation_kwargs or {}
        self.simulate_returns_fn = simulate_returns_fn

        if self.top_n_longs <= 0 or self.top_n_shorts <= 0:
            raise ValueError("top_n_longs and top_n_shorts must both be > 0.")
        if not 0.0 <= self.meta_threshold <= 1.0:
            raise ValueError("meta_threshold must be between 0 and 1.")

    @staticmethod
    def _to_series(x, index: pd.Index, name: str) -> pd.Series:
        if isinstance(x, pd.Series):
            out = x
        else:
            out = pd.Series(x, index=index)
        if not out.index.equals(index):
            out = out.reindex(index)
        if out.isna().any():
            raise ValueError(f"{name} could not be aligned with X index.")
        return out.astype(float)

    @staticmethod
    def _mi_to_wide(x: pd.Series, name: str) -> pd.DataFrame:
        if not isinstance(x.index, pd.MultiIndex):
            raise ValueError(f"{name} must use MultiIndex (ticker, date).")
        tickers = x.index.get_level_values("ticker").astype(str)
        dates = pd.to_datetime(x.index.get_level_values("date"))
        x2 = x.copy()
        x2.index = pd.MultiIndex.from_arrays([tickers, dates], names=["ticker", "date"])
        wide = x2.unstack("ticker")
        wide.index = pd.to_datetime(wide.index)
        return wide.sort_index()

    def _build_meta_labels(self, close: pd.Series, selections: Dict[str, pd.DataFrame]) -> pd.Series:
        close_w = self._mi_to_wide(close, "close_prices")
        fwd_ret = close_w.shift(-1) / close_w - 1.0

        long_entries = selections["long_entries"].reindex(index=close_w.index, columns=close_w.columns).fillna(False)
        short_entries = selections["short_entries"].reindex(index=close_w.index, columns=close_w.columns).fillna(False)

        signed_ret = pd.DataFrame(np.nan, index=close_w.index, columns=close_w.columns, dtype=float)
        signed_ret = signed_ret.where(~long_entries, fwd_ret)
        signed_ret = signed_ret.where(~short_entries, -fwd_ret)

        labels_w = (signed_ret > 0.0).astype(float)
        active = long_entries | short_entries
        labels_w = labels_w.where(active)

        try:
            labels = labels_w.stack(future_stack=True).dropna()
        except TypeError:
            labels = labels_w.stack(dropna=True)
        labels.index = labels.index.set_names(["date", "ticker"])
        labels = labels.reorder_levels(["ticker", "date"]).sort_index()
        return labels.astype(int)

    def _simulate(self, rank_df: pd.Series, close_prices: pd.Series):
        simulate_fn = self.simulate_returns_fn
        if simulate_fn is None:
            from simulation import simulate_returns as simulate_fn

        return simulate_fn(
            rank_df=rank_df,
            price_df=close_prices,
            n_long=self.top_n_longs,
            n_short=self.top_n_shorts,
            **self.simulation_kwargs,
        )

    def run(self, X: pd.DataFrame, y_primary, close_prices) -> Dict[str, Any]:
        if not isinstance(X, pd.DataFrame):
            raise ValueError("X must be a pandas DataFrame.")

        y_primary_s = y_primary if isinstance(y_primary, pd.Series) else pd.Series(y_primary, index=X.index)
        close_s = self._to_series(close_prices, X.index, "close_prices")

        primary_predictor = TimeRespectingOutOfSamplePredictor(
            primary_model=self.primary_model,
            cv=self.cv,
        )
        primary_oof, _ = primary_predictor.fit_predict(X, y_primary_s, prediction_sets=[])

        valid_primary = primary_oof.notna()
        primary_for_sim = primary_oof.fillna(0.0)
        primary_pf, primary_sel = self._simulate(primary_for_sim, close_s)

        meta_labels_sparse = self._build_meta_labels(close_s, primary_sel)
        meta_labels = meta_labels_sparse.reindex(X.index).fillna(0).astype(int)

        if meta_labels.nunique() < 2:
            raise ValueError("Meta labels have a single class after simulation; cannot train meta model.")

        meta_labeler = MetaLabeler(
            meta_model=self.meta_model,
            cv=self.cv,
            primary_predictions=primary_oof.fillna(0.0),
            profit_labels=meta_labels,
        )
        meta_oof, _ = meta_labeler.fit_predict(X, meta_labels, prediction_sets=[])

        meta_score = meta_oof.fillna(0.0).clip(0.0, 1.0)
        take_mask = meta_score >= self.meta_threshold
        final_rank = primary_oof.fillna(0.0) * meta_score.where(take_mask, 0.0)
        final_rank = final_rank.where(valid_primary, 0.0)

        final_pf, final_sel = self._simulate(final_rank, close_s)

        primary_stats = primary_pf.stats() if hasattr(primary_pf, "stats") else None
        final_stats = final_pf.stats() if hasattr(final_pf, "stats") else None

        return {
            "primary_oof_predictions": primary_oof,
            "primary_simulation": primary_pf,
            "primary_selections": primary_sel,
            "meta_labels": meta_labels,
            "meta_oof_scores": meta_oof,
            "final_rank": final_rank,
            "final_simulation": final_pf,
            "final_selections": final_sel,
            "primary_stats": primary_stats,
            "final_stats": final_stats,
        }
