# -*- coding: utf-8 -*-
"""simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGUZ5xd3mRzhi7BLLG_9NQAGs4Er2xV1
"""

import plotly.io as pio
def plot_returns(pf):
  pio.renderers.default = "colab"
  total_value = pf.value().mean(axis=1)
  total_value.vbt.plot().show()

import numpy as np
import pandas as pd
import vectorbt as vbt

def simulate_returns(
    rank_df: pd.Series | pd.DataFrame,
    price_df: pd.Series | pd.DataFrame,          # interpreted as CLOSE (backward compatible)
    n_long: int,
    n_short: int | None = None,
    higher_is_better: bool = True,
    long_gross: float = 0.5,
    short_gross: float = 0.5,
    init_cash: float = 1_000_000.0,
    fees: float = 0.0,
    slippage: float = 0.0,
    freq="1D",
    min_names_each_day: int | None = None,

    # Optional OHLC:
    open_df: pd.Series | pd.DataFrame | None = None,
    high_df: pd.Series | pd.DataFrame | None = None,
    low_df:  pd.Series | pd.DataFrame | None = None,

    # Fixed base stops:
    sl_stop_pct: float = np.nan,   # e.g. 0.10 or 10 -> 10% SL; np.nan disables
    tp_stop_pct: float = np.nan,   # e.g. 0.20 or 20 -> 20% TP; np.nan disables
    sl_trail: bool = False,

    # Adversarial probability input + switches:
    adv_prob_df: pd.Series | pd.DataFrame | None = None,   # MultiIndex(ticker,date)
    adv_shares: bool = False,
    adv_stop_losses: bool = False,
    adv_take_profits: bool = False,

    # How to magnify:
    adv_scale: float = 1.0,        # factor = 1 + adv_scale * adv_prob
    adv_clip: tuple[float, float] = (0.0, 1.0),  # clip adv_prob into [0,1] by default
):
    """
    - adv_prob_df is expected to be probability-like (0..1). We clip by adv_clip.
    - Magnification factor is: factor = 1 + adv_scale * adv_prob
      If adv_prob is 0 -> factor=1 (no change). If adv_prob is 1 -> factor=1+adv_scale.
    - If sl_stop_pct or tp_stop_pct is np.nan, that stop is disabled regardless of adv scaling.
    """

    if n_short is None:
        n_short = n_long

    def _mi_to_wide(x, name: str) -> pd.DataFrame:
        if isinstance(x, pd.DataFrame):
            if x.shape[1] == 1:
                x = x.iloc[:, 0]
            else:
                raise ValueError(f"{name}: DataFrame must be 1 column (or pass a Series).")
        if not isinstance(x, pd.Series) or not isinstance(x.index, pd.MultiIndex):
            raise ValueError(f"{name}: must be a Series (or 1-col DF) with MultiIndex (ticker, date).")

        tickers = x.index.get_level_values(0).astype(str)
        dates = pd.to_datetime(x.index.get_level_values(1))

        x2 = x.copy()
        x2.index = pd.MultiIndex.from_arrays([tickers, dates], names=["ticker", "date"])
        wide = x2.unstack("ticker")
        wide.index = pd.to_datetime(wide.index)
        return wide.sort_index()

    def _normalize_pct_to_decimal_or_inf(x: float) -> float:
        """np.nan -> np.inf, else (10 -> 0.10), (0.10 -> 0.10)."""
        if x is None or (isinstance(x, float) and np.isnan(x)):
            return np.inf
        x = float(x)
        if x < 0:
            raise ValueError("Stop percentages must be non-negative.")
        return x / 100.0 if x > 1.5 else x

    # --- Build CLOSE (always required) ---
    ranks_w = _mi_to_wide(rank_df, "rank_df").astype(float)
    close_w = _mi_to_wide(price_df, "price_df(close)").astype(float)

    # --- Build optional OHLC ---
    open_w = high_w = low_w = None
    if open_df is not None:
        open_w = _mi_to_wide(open_df, "open_df").astype(float)
    if high_df is not None:
        high_w = _mi_to_wide(high_df, "high_df").astype(float)
    if low_df is not None:
        low_w = _mi_to_wide(low_df, "low_df").astype(float)

    # Align ranks & prices universe using CLOSE as anchor
    common_dates = ranks_w.index.intersection(close_w.index)
    common_tickers = ranks_w.columns.intersection(close_w.columns)

    ranks_w = ranks_w.loc[common_dates, common_tickers].sort_index()
    close_w = close_w.loc[common_dates, common_tickers].sort_index()

    if open_w is not None:
        open_w = open_w.reindex(index=close_w.index, columns=close_w.columns)
    if high_w is not None:
        high_w = high_w.reindex(index=close_w.index, columns=close_w.columns)
    if low_w is not None:
        low_w = low_w.reindex(index=close_w.index, columns=close_w.columns)

    # Valid observations based on CLOSE
    valid = ranks_w.notna() & close_w.notna() & (close_w > 0)

    enough = pd.Series(True, index=ranks_w.index)
    if min_names_each_day is not None:
        enough = valid.sum(axis=1) >= min_names_each_day

    x = ranks_w.where(valid)

    # Cross-sectional rank each day
    if higher_is_better:
        long_rank = x.rank(axis=1, method="first", ascending=False)
        short_rank = x.rank(axis=1, method="first", ascending=True)
    else:
        long_rank = x.rank(axis=1, method="first", ascending=True)
        short_rank = x.rank(axis=1, method="first", ascending=False)

    long_mask = (long_rank <= n_long) & enough.values[:, None]
    short_mask = (short_rank <= n_short) & enough.values[:, None]

    overlap = long_mask & short_mask
    if overlap.any().any():
        short_mask = short_mask & ~overlap

    nL = long_mask.sum(axis=1).astype(float)
    nS = short_mask.sum(axis=1).astype(float)

    wL = pd.Series(0.0, index=ranks_w.index)
    wS = pd.Series(0.0, index=ranks_w.index)
    wL.loc[nL > 0] = long_gross / nL.loc[nL > 0]
    wS.loc[nS > 0] = short_gross / nS.loc[nS > 0]

    # --- Signals ---
    long_prev = long_mask.shift(1, fill_value=False)
    short_prev = short_mask.shift(1, fill_value=False)

    long_entries = long_mask & ~long_prev
    long_exits   = ~long_mask & long_prev

    short_entries = short_mask & ~short_prev
    short_exits   = ~short_mask & short_prev

    # --- Base entry sizing (value) ---
    size = (long_entries.mul(wL, axis=0)).astype(float) + (short_entries.mul(wS, axis=0)).astype(float)
    size = size.fillna(0.0)
    size_value = size * init_cash

    # --- Adversarial factor (wide) ---
    factor_w = None
    if adv_prob_df is not None and (adv_shares or adv_stop_losses or adv_take_profits):
        adv_w = _mi_to_wide(adv_prob_df, "adv_prob_df").astype(float)
        adv_w = adv_w.reindex(index=close_w.index, columns=close_w.columns)

        lo, hi = adv_clip
        adv_w = adv_w.clip(lower=lo, upper=hi)

        # factor = 1 + adv_scale * adv_prob
        factor_w = 1.0 + float(adv_scale) * adv_w.fillna(0.0)

        # Apply to sizing (only where entering)
        if adv_shares:
            size_value = size_value * factor_w

    # --- Stops (scalar base -> maybe matrix via factor_w) ---
    base_sl = _normalize_pct_to_decimal_or_inf(sl_stop_pct)
    base_tp = _normalize_pct_to_decimal_or_inf(tp_stop_pct)

    sl_stop_arg = base_sl
    tp_stop_arg = base_tp

    if factor_w is not None:
        if adv_stop_losses and np.isfinite(base_sl):
            sl_stop_arg = (base_sl * factor_w).astype(float)
        if adv_take_profits and np.isfinite(base_tp):
            tp_stop_arg = (base_tp * factor_w).astype(float)

    # --- Build kwargs for vectorbt ---
    pf_kwargs = dict(
        close=close_w,
        entries=long_entries,
        exits=long_exits,
        short_entries=short_entries,
        short_exits=short_exits,
        size=size_value,
        size_type="value",
        init_cash=init_cash,
        fees=fees,
        slippage=slippage,
        freq=freq,
        sl_stop=sl_stop_arg,     # np.inf disables (or matrix equivalent if you pass one)
        sl_trail=sl_trail,
        tp_stop=tp_stop_arg,     # np.inf disables
    )

    if open_w is not None:
        pf_kwargs["open"] = open_w
    if high_w is not None:
        pf_kwargs["high"] = high_w
    if low_w is not None:
        pf_kwargs["low"] = low_w

    pf = vbt.Portfolio.from_signals(**pf_kwargs)

    selections = {
        "long_mask": long_mask,
        "short_mask": short_mask,
        "long_entries": long_entries,
        "long_exits": long_exits,
        "short_entries": short_entries,
        "short_exits": short_exits,
    }
    return pf, selections