# -*- coding: utf-8 -*-
"""simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGUZ5xd3mRzhi7BLLG_9NQAGs4Er2xV1
"""

import plotly.io as pio
def plot_returns(pf):
  pio.renderers.default = "colab"
  total_value = pf.value().mean(axis=1)
  total_value.vbt.plot().show()

import numpy as np
import pandas as pd
import vectorbt as vbt


class Simulator:
    """Long-only close-to-next-session simulator driven by prediction signals.

    Predictions are expected as a pandas Series or 1-column DataFrame with
    MultiIndex (ticker, date). Any value > 0 is treated as an active long signal.
    Orders are submitted at the close of each signal bar. Stops become active from
    the next bar onward by shifting stop percentages by one period.
    """

    def __init__(
        self,
        open_df: pd.Series | pd.DataFrame,
        high_df: pd.Series | pd.DataFrame,
        low_df: pd.Series | pd.DataFrame,
        close_df: pd.Series | pd.DataFrame,
        volumes_df: pd.Series | pd.DataFrame,
        *,
        tp: float = 0.02,
        sl: float = 0.01,
        horizon: int = 1,
        max_trade_size: float = 0.10,
        init_cash: float = 100_000.0,
        weighting: str = "equal",
        frequency: str = "1d",
        debug: bool = False,
    ):
        self.tp = float(tp)
        self.sl = float(sl)
        self.horizon = int(horizon)
        self.max_trade_size = float(max_trade_size)
        self.init_cash = float(init_cash)
        self.weighting = weighting
        self.frequency = frequency
        self.debug = bool(debug)

        if self.horizon < 1:
            raise ValueError("horizon must be >= 1")
        if self.max_trade_size <= 0:
            raise ValueError("max_trade_size must be > 0")
        if self.weighting != "equal":
            raise ValueError("Only weighting='equal' is currently supported.")

        self.open_w = self._mi_to_wide(open_df, "open_df")
        self.high_w = self._mi_to_wide(high_df, "high_df")
        self.low_w = self._mi_to_wide(low_df, "low_df")
        self.close_w = self._mi_to_wide(close_df, "close_df")
        self.volume_w = self._mi_to_wide(volumes_df, "volumes_df")

        self._align_market_data()
        self.pf = None
        self.trades_df = pd.DataFrame()

    @staticmethod
    def _mi_to_wide(x: pd.Series | pd.DataFrame, name: str) -> pd.DataFrame:
        if isinstance(x, pd.DataFrame):
            if x.shape[1] != 1:
                raise ValueError(f"{name}: DataFrame must have exactly one column.")
            x = x.iloc[:, 0]
        if not isinstance(x, pd.Series) or not isinstance(x.index, pd.MultiIndex):
            raise ValueError(f"{name}: must be a Series (or 1-col DF) with MultiIndex (ticker, date).")

        tickers = x.index.get_level_values(0).astype(str)
        dates = pd.to_datetime(x.index.get_level_values(1))
        x2 = x.copy()
        x2.index = pd.MultiIndex.from_arrays([tickers, dates], names=["ticker", "date"])
        wide = x2.unstack("ticker")
        wide.index = pd.to_datetime(wide.index)
        return wide.sort_index().astype(float)

    def _align_market_data(self):
        common_idx = self.open_w.index
        common_cols = self.open_w.columns
        for df in [self.high_w, self.low_w, self.close_w, self.volume_w]:
            common_idx = common_idx.intersection(df.index)
            common_cols = common_cols.intersection(df.columns)

        common_idx = common_idx.sort_values()
        common_cols = common_cols.sort_values()

        self.open_w = self.open_w.loc[common_idx, common_cols]
        self.high_w = self.high_w.loc[common_idx, common_cols]
        self.low_w = self.low_w.loc[common_idx, common_cols]
        self.close_w = self.close_w.loc[common_idx, common_cols]
        self.volume_w = self.volume_w.loc[common_idx, common_cols]



    @staticmethod
    def _extract_trades_df(portfolio) -> pd.DataFrame:
        """Best-effort extraction of trade records from a vectorbt Portfolio."""
        trades_obj = getattr(portfolio, "trades", None)
        if trades_obj is None:
            return pd.DataFrame()

        records_readable = getattr(trades_obj, "records_readable", None)
        if records_readable is not None:
            if callable(records_readable):
                try:
                    out = records_readable()
                except Exception:
                    out = None
            else:
                out = records_readable
            if isinstance(out, pd.DataFrame):
                return out.copy()

        records = getattr(trades_obj, "records", None)
        if records is not None:
            if callable(records):
                try:
                    out = records()
                except Exception:
                    out = None
            else:
                out = records
            if isinstance(out, pd.DataFrame):
                return out.copy()

        return pd.DataFrame()

    def run(self, predictions: pd.Series | pd.DataFrame):
        pred_w = self._mi_to_wide(predictions, "predictions")
        pred_w = pred_w.reindex(index=self.close_w.index, columns=self.close_w.columns)

        valid_signal = pred_w.notna() & self.close_w.notna() & (self.close_w > 0)
        raw_signal = (pred_w > 0) & valid_signal

        if self.horizon > 1:
            exits = raw_signal.shift(self.horizon, fill_value=False)
            exits = exits & ~raw_signal
        else:
            exits = raw_signal.shift(1, fill_value=False) & ~raw_signal

        entries = raw_signal & ~raw_signal.shift(1, fill_value=False)

        active_counts = raw_signal.sum(axis=1).replace(0, np.nan)
        per_name_weight = (self.max_trade_size / active_counts).clip(upper=self.max_trade_size)
        size_frac = raw_signal.mul(per_name_weight, axis=0).fillna(0.0)
        size_frac = size_frac.where(entries, 0.0)
        size_value = size_frac * self.init_cash

        slippage_matrix = calculate_smart_slippage(
            open_df=self.open_w,
            high_df=self.high_w,
            low_df=self.low_w,
            close_df=self.close_w,
            volume_df=self.volume_w,
            size_frac=size_frac,
            init_cash=self.init_cash,
        )

        # Stops should not trigger on entry bar because entry is at close.
        sl_matrix = pd.DataFrame(float(self.sl), index=self.close_w.index, columns=self.close_w.columns)
        tp_matrix = pd.DataFrame(float(self.tp), index=self.close_w.index, columns=self.close_w.columns)
        sl_matrix = sl_matrix.shift(1).fillna(np.inf)
        tp_matrix = tp_matrix.shift(1).fillna(np.inf)

        self.pf = vbt.Portfolio.from_signals(
            open=self.open_w,
            high=self.high_w,
            low=self.low_w,
            close=self.close_w,
            entries=entries,
            exits=exits,
            size=size_value,
            size_type="value",
            init_cash=self.init_cash,
            sl_stop=sl_matrix,
            tp_stop=tp_matrix,
            slippage=slippage_matrix,
            cash_sharing=True,
            freq=self.frequency,
        )

        self.trades_df = self._extract_trades_df(self.pf)

        diagnostics = {
            "prediction_active_count": int(raw_signal.to_numpy().sum()),
            "entry_count": int(entries.to_numpy().sum()),
            "exit_count": int(exits.to_numpy().sum()),
        }
        if self.debug:
            diagnostics["mapping_gap"] = diagnostics["prediction_active_count"] - diagnostics["entry_count"]
            print("Simulator diagnostics:", diagnostics)

        return self.pf, diagnostics


def calculate_smart_slippage(
    open_df: pd.DataFrame,
    high_df: pd.DataFrame,
    low_df: pd.DataFrame,
    close_df: pd.DataFrame,
    volume_df: pd.DataFrame,
    size_frac: pd.DataFrame,
    *,
    init_cash: float = 100_000.0,
    base_spread: float = 0.0002,
    vol_mult: float = 0.1,
    impact_mult: float = 0.1,
    min_slippage: float = 0.0005,
    max_slippage: float = 0.02,
) -> pd.DataFrame:
    """Estimate per-trade slippage with volatility + participation impact.

    The output is a matrix with the same [date x ticker] shape as `size_frac`,
    intended to be passed to vectorbt's `slippage` argument.
    """
    vol_comp = ((high_df - low_df) / open_df.replace(0.0, np.nan)) * float(vol_mult)

    trade_dollar_val = size_frac * float(init_cash)
    daily_dollar_volume = volume_df * close_df
    participation_rate = (trade_dollar_val / daily_dollar_volume.replace(0.0, np.nan)).fillna(0.0)
    impact_comp = float(impact_mult) * np.sqrt(participation_rate)

    total_slippage = float(base_spread) + vol_comp + impact_comp
    return total_slippage.clip(lower=float(min_slippage), upper=float(max_slippage)).fillna(0.0)

def simulate_returns(
    rank_df: pd.Series | pd.DataFrame,
    price_df: pd.Series | pd.DataFrame,          # interpreted as CLOSE (backward compatible)
    n_long: int,
    n_short: int | None = None,
    higher_is_better: bool = True,
    long_gross: float = 0.5,
    short_gross: float = 0.5,
    init_cash: float = 1_000_000.0,
    fees: float = 0.0,
    slippage: float = 0.0,
    freq="1D",
    min_names_each_day: int | None = None,

    # Optional OHLC:
    open_df: pd.Series | pd.DataFrame | None = None,
    high_df: pd.Series | pd.DataFrame | None = None,
    low_df:  pd.Series | pd.DataFrame | None = None,

    # Fixed base stops:
    sl_stop_pct: float = np.nan,   # e.g. 0.10 or 10 -> 10% SL; np.nan disables
    tp_stop_pct: float = np.nan,   # e.g. 0.20 or 20 -> 20% TP; np.nan disables
    sl_trail: bool = False,

    # Adversarial probability input + switches:
    adv_prob_df: pd.Series | pd.DataFrame | None = None,   # MultiIndex(ticker,date)
    adv_shares: bool = False,
    adv_stop_losses: bool = False,
    adv_take_profits: bool = False,

    # How to magnify:
    adv_scale: float = 1.0,        # factor = 1 + adv_scale * adv_prob
    adv_clip: tuple[float, float] = (0.0, 1.0),  # clip adv_prob into [0,1] by default
):
    """
    - adv_prob_df is expected to be probability-like (0..1). We clip by adv_clip.
    - Magnification factor is: factor = 1 + adv_scale * adv_prob
      If adv_prob is 0 -> factor=1 (no change). If adv_prob is 1 -> factor=1+adv_scale.
    - If sl_stop_pct or tp_stop_pct is np.nan, that stop is disabled regardless of adv scaling.
    """

    if n_short is None:
        n_short = n_long

    def _mi_to_wide(x, name: str) -> pd.DataFrame:
        if isinstance(x, pd.DataFrame):
            if x.shape[1] == 1:
                x = x.iloc[:, 0]
            else:
                raise ValueError(f"{name}: DataFrame must be 1 column (or pass a Series).")
        if not isinstance(x, pd.Series) or not isinstance(x.index, pd.MultiIndex):
            raise ValueError(f"{name}: must be a Series (or 1-col DF) with MultiIndex (ticker, date).")

        tickers = x.index.get_level_values(0).astype(str)
        dates = pd.to_datetime(x.index.get_level_values(1))

        x2 = x.copy()
        x2.index = pd.MultiIndex.from_arrays([tickers, dates], names=["ticker", "date"])
        wide = x2.unstack("ticker")
        wide.index = pd.to_datetime(wide.index)
        return wide.sort_index()

    def _normalize_pct_to_decimal_or_inf(x: float) -> float:
        """np.nan -> np.inf, else (10 -> 0.10), (0.10 -> 0.10)."""
        if x is None or (isinstance(x, float) and np.isnan(x)):
            return np.inf
        x = float(x)
        if x < 0:
            raise ValueError("Stop percentages must be non-negative.")
        return x / 100.0 if x > 1.5 else x

    # --- Build CLOSE (always required) ---
    ranks_w = _mi_to_wide(rank_df, "rank_df").astype(float)
    close_w = _mi_to_wide(price_df, "price_df(close)").astype(float)

    # --- Build optional OHLC ---
    open_w = high_w = low_w = None
    if open_df is not None:
        open_w = _mi_to_wide(open_df, "open_df").astype(float)
    if high_df is not None:
        high_w = _mi_to_wide(high_df, "high_df").astype(float)
    if low_df is not None:
        low_w = _mi_to_wide(low_df, "low_df").astype(float)

    # Align ranks & prices universe using CLOSE as anchor
    common_dates = ranks_w.index.intersection(close_w.index)
    common_tickers = ranks_w.columns.intersection(close_w.columns)

    ranks_w = ranks_w.loc[common_dates, common_tickers].sort_index()
    close_w = close_w.loc[common_dates, common_tickers].sort_index()

    if open_w is not None:
        open_w = open_w.reindex(index=close_w.index, columns=close_w.columns)
    if high_w is not None:
        high_w = high_w.reindex(index=close_w.index, columns=close_w.columns)
    if low_w is not None:
        low_w = low_w.reindex(index=close_w.index, columns=close_w.columns)

    # Valid observations based on CLOSE
    valid = ranks_w.notna() & close_w.notna() & (close_w > 0)

    enough = pd.Series(True, index=ranks_w.index)
    if min_names_each_day is not None:
        enough = valid.sum(axis=1) >= min_names_each_day

    x = ranks_w.where(valid)

    # Cross-sectional rank each day
    if higher_is_better:
        long_rank = x.rank(axis=1, method="first", ascending=False)
        short_rank = x.rank(axis=1, method="first", ascending=True)
    else:
        long_rank = x.rank(axis=1, method="first", ascending=True)
        short_rank = x.rank(axis=1, method="first", ascending=False)

    long_mask = (long_rank <= n_long) & enough.values[:, None]
    short_mask = (short_rank <= n_short) & enough.values[:, None]

    overlap = long_mask & short_mask
    if overlap.any().any():
        short_mask = short_mask & ~overlap

    nL = long_mask.sum(axis=1).astype(float)
    nS = short_mask.sum(axis=1).astype(float)

    wL = pd.Series(0.0, index=ranks_w.index)
    wS = pd.Series(0.0, index=ranks_w.index)
    wL.loc[nL > 0] = long_gross / nL.loc[nL > 0]
    wS.loc[nS > 0] = short_gross / nS.loc[nS > 0]

    # --- Signals ---
    long_prev = long_mask.shift(1, fill_value=False)
    short_prev = short_mask.shift(1, fill_value=False)

    long_entries = long_mask & ~long_prev
    long_exits   = ~long_mask & long_prev

    short_entries = short_mask & ~short_prev
    short_exits   = ~short_mask & short_prev

    # --- Base entry sizing (value) ---
    size = (long_entries.mul(wL, axis=0)).astype(float) + (short_entries.mul(wS, axis=0)).astype(float)
    size = size.fillna(0.0)
    size_value = size * init_cash

    # --- Adversarial factor (wide) ---
    factor_w = None
    if adv_prob_df is not None and (adv_shares or adv_stop_losses or adv_take_profits):
        adv_w = _mi_to_wide(adv_prob_df, "adv_prob_df").astype(float)
        adv_w = adv_w.reindex(index=close_w.index, columns=close_w.columns)

        lo, hi = adv_clip
        adv_w = adv_w.clip(lower=lo, upper=hi)

        # factor = 1 + adv_scale * adv_prob
        factor_w = 1.0 + float(adv_scale) * adv_w.fillna(0.0)

        # Apply to sizing (only where entering)
        if adv_shares:
            size_value = size_value * factor_w

    # --- Stops (scalar base -> maybe matrix via factor_w) ---
    base_sl = _normalize_pct_to_decimal_or_inf(sl_stop_pct)
    base_tp = _normalize_pct_to_decimal_or_inf(tp_stop_pct)

    sl_stop_arg = base_sl
    tp_stop_arg = base_tp

    if factor_w is not None:
        if adv_stop_losses and np.isfinite(base_sl):
            sl_stop_arg = (base_sl * factor_w).astype(float)
        if adv_take_profits and np.isfinite(base_tp):
            tp_stop_arg = (base_tp * factor_w).astype(float)

    # --- Build kwargs for vectorbt ---
    pf_kwargs = dict(
        close=close_w,
        entries=long_entries,
        exits=long_exits,
        short_entries=short_entries,
        short_exits=short_exits,
        size=size_value,
        size_type="value",
        init_cash=init_cash,
        fees=fees,
        slippage=slippage,
        freq=freq,
        sl_stop=sl_stop_arg,     # np.inf disables (or matrix equivalent if you pass one)
        sl_trail=sl_trail,
        tp_stop=tp_stop_arg,     # np.inf disables
    )

    if open_w is not None:
        pf_kwargs["open"] = open_w
    if high_w is not None:
        pf_kwargs["high"] = high_w
    if low_w is not None:
        pf_kwargs["low"] = low_w

    pf = vbt.Portfolio.from_signals(**pf_kwargs)

    selections = {
        "long_mask": long_mask,
        "short_mask": short_mask,
        "long_entries": long_entries,
        "long_exits": long_exits,
        "short_entries": short_entries,
        "short_exits": short_exits,
    }
    return pf, selections
