# -*- coding: utf-8 -*-
"""transactions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcgZ0mXSNARHqAWud8zslW4W8ajkJ0HQ
"""

from __future__ import annotations
import alpaca

from alpaca.trading.client import TradingClient
from alpaca.trading.enums import PositionSide

def close_all_positions(api_key: str, secret_key: str, *, paper: bool = True):
    """
    Close all open positions (long and short) for this account.

    :param api_key: Alpaca API key ID
    :param secret_key: Alpaca secret key
    :param paper: True to use paper trading, False for live
    :return: List of order objects created to close positions
    """
    client = TradingClient(api_key, secret_key, paper=paper)

    # This calls the /v2/positions/close endpoint under the hood
    closing_orders = client.close_all_positions(cancel_orders=True)
    return closing_orders

import pandas as pd

from alpaca.trading.enums import OrderSide, OrderType, TimeInForce, OrderClass
from alpaca.trading.requests import MarketOrderRequest, OrderRequest

from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockLatestQuoteRequest


# -----------------------------
# 2) POSITION HELPERS
# -----------------------------
def get_current_positions_dict(trading_client: TradingClient) -> dict[str, int]:
    """Returns current Alpaca positions as {symbol: int_shares}. Shorts negative."""
    positions = trading_client.get_all_positions()
    return {p.symbol: int(float(p.qty)) for p in positions}


# -----------------------------
# 3) ADV_PROB -> STOP/TP PCTS
# -----------------------------
def advprob_to_pcts(
    adv_prob: float,
    base_stop: float = 0.08,
    min_stop: float = 0.02,
    base_tp: float = 0.15,
    min_tp: float = 0.04,
) -> tuple[float, float]:
    """Map adv_prob in [0,1] to stop/tp percents (decimals)."""
    adv = float(min(max(adv_prob, 0.0), 1.0))
    conf = 1.0 - adv
    stop_pct = min_stop + conf * (base_stop - min_stop)
    tp_pct = min_tp + conf * (base_tp - min_tp)
    return float(stop_pct), float(tp_pct)


# -----------------------------
# 4) LIVE PRICE + BRACKET PRICE MATH
# -----------------------------
def get_live_mid_price(symbol: str) -> float:
    """Fetch latest quote and return midpoint price."""
    req = StockLatestQuoteRequest(symbol_or_symbols=[symbol])
    quotes = data_client.get_stock_latest_quote(req)
    q = quotes[symbol]

    bid = float(q.bid_price) if q.bid_price is not None else 0.0
    ask = float(q.ask_price) if q.ask_price is not None else 0.0

    if bid > 0 and ask > 0:
        return (bid + ask) / 2.0

    # Fallbacks if one side is missing
    if ask > 0:
        return ask
    if bid > 0:
        return bid

    raise ValueError(f"No valid bid/ask available for {symbol}")


def pct_to_bracket_prices(entry_price: float, side: OrderSide, stop_pct: float, tp_pct: float) -> tuple[float, float]:
    """Convert stop/tp percents into absolute prices."""
    if entry_price <= 0:
        raise ValueError("entry_price must be > 0")

    if side == OrderSide.BUY:
        stop_price = entry_price * (1.0 - stop_pct)
        tp_price = entry_price * (1.0 + tp_pct)
    else:  # SELL (short entry)
        stop_price = entry_price * (1.0 + stop_pct)
        tp_price = entry_price * (1.0 - tp_pct)

    return round(stop_price, 2), round(tp_price, 2)


def apply_alpaca_bracket_guardrails(ref_price: float, side: OrderSide, stop_price: float, tp_price: float) -> tuple[float, float]:
    """Ensure bracket legs are on correct side of ref price by at least $0.01."""
    if ref_price <= 0:
        raise ValueError("ref_price must be > 0")

    # Take-profit constraints
    if side == OrderSide.BUY:
        if tp_price < ref_price + 0.01:
            tp_price = round(ref_price + 0.01, 2)
        # Stop should be below ref for longs (if rounding pushed it above, nudge)
        if stop_price >= ref_price:
            stop_price = round(ref_price - 0.01, 2)
    else:
        if tp_price > ref_price - 0.01:
            tp_price = round(ref_price - 0.01, 2)
        # Stop should be above ref for shorts
        if stop_price <= ref_price:
            stop_price = round(ref_price + 0.01, 2)

    return stop_price, tp_price

# -----------------------------
# 5) ORDER SUBMISSION
# -----------------------------
def submit_entry_bracket_market(
    trading_client: TradingClient,
    symbol: str,
    qty: int,
    side: OrderSide,
    adv_prob: float,
    base_stop: float = 0.08,
    min_stop: float = 0.02,
    base_tp: float = 0.15,
    min_tp: float = 0.04,
    max_retries: int = 1,
):
    """Submit a MARKET BRACKET order (entry + attached TP/SL).

    Uses live quote for pricing, and if Alpaca returns a base_price constraint error,
    adjusts TP/SL against the returned base_price and retries once.
    """
    if qty <= 0:
        return None

    stop_pct, tp_pct = advprob_to_pcts(
        adv_prob,
        base_stop=base_stop,
        min_stop=min_stop,
        base_tp=base_tp,
        min_tp=min_tp,
    )

    def build_order(ref_price: float) -> tuple[MarketOrderRequest, float, float]:
        stop_price, tp_price = pct_to_bracket_prices(ref_price, side, stop_pct, tp_pct)
        stop_price, tp_price = apply_alpaca_bracket_guardrails(ref_price, side, stop_price, tp_price)
        o = MarketOrderRequest(
            symbol=symbol,
            qty=qty,
            side=side,
            time_in_force=TimeInForce.DAY,
            order_class=OrderClass.BRACKET,
            take_profit={"limit_price": tp_price},
            stop_loss={"stop_price": stop_price},
        )
        return o, stop_price, tp_price

    # First attempt uses the latest quote midpoint
    ref_price = get_live_mid_price(symbol)
    order, stop_price, tp_price = build_order(ref_price)

    attempt = 0
    while True:
        try:
            placed = trading_client.submit_order(order)
            print(
                f"{symbol}: BRACKET {side.value} {qty} | ref={ref_price:.2f} "
                f"TP={tp_price} SL={stop_price} id={placed.id}"
            )
            return placed
        except Exception as e:
            # Try to recover from Alpaca's base_price +/- 0.01 constraint errors.
            # The APIError message is usually a JSON string with base_price.
            err_text = str(e)

            if attempt >= max_retries:
                print(f"Error submitting bracket for {symbol}: {err_text}")
                return None

            base_price = None
            try:
                import json

                payload = json.loads(err_text) if err_text.strip().startswith("{") else None
                if isinstance(payload, dict) and "base_price" in payload:
                    base_price = float(payload["base_price"])
            except Exception:
                base_price = None

            if base_price is None:
                # Not the base_price error shape; don't retry.
                print(f"Error submitting bracket for {symbol}: {err_text}")
                return None

            # Rebuild TP/SL against the returned base_price
            # BUY:  TP >= base + 0.01, SL <= base - 0.01
            # SELL: TP <= base - 0.01, SL >= base + 0.01
            ref_price = base_price
            order, stop_price, tp_price = build_order(ref_price)

            # Extra hard constraints (in case rounding still violates)
            if side == OrderSide.BUY:
                tp_price = max(tp_price, round(base_price + 0.01, 2))
                stop_price = min(stop_price, round(base_price - 0.01, 2))
            else:
                tp_price = min(tp_price, round(base_price - 0.01, 2))
                stop_price = max(stop_price, round(base_price + 0.01, 2))

            order = MarketOrderRequest(
                symbol=symbol,
                qty=qty,
                side=side,
                time_in_force=TimeInForce.DAY,
                order_class=OrderClass.BRACKET,
                take_profit={"limit_price": tp_price},
                stop_loss={"stop_price": stop_price},
            )

            attempt += 1
            print(
                f"{symbol}: retrying with base_price={base_price:.3f} "
                f"TP={tp_price} SL={stop_price}"
            )


def submit_plain_market(
    trading_client: TradingClient,
    symbol: str,
    qty: int,
    side: OrderSide,
):
    """Submit a plain MARKET order (used for reducing/closing exposure)."""
    if qty <= 0:
        return None

    order = OrderRequest(
        symbol=symbol,
        qty=qty,
        side=side,
        type=OrderType.MARKET,
        time_in_force=TimeInForce.DAY,
    )

    placed = trading_client.submit_order(order)
    print(f"{symbol}: MARKET {side.value} {qty} id={placed.id}")
    return placed


# -----------------------------
# 6) REBALANCE
# -----------------------------
def rebalance_with_live_brackets(
    trading_client: TradingClient,
    df: pd.DataFrame,
    close_others: bool = True,
):
    """Rebalance to target shares. Uses BRACKET only when opening/increasing exposure."""

    required = {"symbol", "shares"}
    if not required.issubset(df.columns):
        raise ValueError("df must include columns: 'symbol', 'shares'")

    # If you want bracket sizing from adv_prob, ensure it is present
    if "adv_prob" not in df.columns:
        raise ValueError("df must include 'adv_prob' for bracket entries")

    current_positions = get_current_positions_dict(trading_client)

    target_positions = {row["symbol"]: int(row["shares"]) for _, row in df.iterrows()}

    for _, row in df.iterrows():
        symbol = str(row["symbol"]).upper()
        target = int(row["shares"])
        adv_prob = float(row["adv_prob"])

        current = current_positions.get(symbol, 0)
        delta = target - current

        if delta == 0:
            print(f"{symbol}: already at target {target}")
            continue

        side = OrderSide.BUY if delta > 0 else OrderSide.SELL
        qty = abs(int(delta))

        # Opening/increasing exposure → bracket.
        # - current==0: opening
        # - long (current>0) and delta>0: adding
        # - short (current<0) and delta<0: adding to short
        opening_or_increasing = (current == 0) or (current > 0 and delta > 0) or (current < 0 and delta < 0)

        if opening_or_increasing:
            submit_entry_bracket_market(
                trading_client=trading_client,
                symbol=symbol,
                qty=qty,
                side=side,
                adv_prob=adv_prob,
            )
        else:
            # Reducing exposure or flipping direction → plain market (simplest & safest)
            submit_plain_market(
                trading_client=trading_client,
                symbol=symbol,
                qty=qty,
                side=side,
            )

    if close_others:
        symbols_to_close = set(current_positions.keys()) - set(target_positions.keys())
        for symbol in symbols_to_close:
            current = current_positions[symbol]
            if current == 0:
                continue
            # Trade back to zero
            side = OrderSide.SELL if current > 0 else OrderSide.BUY
            qty = abs(int(current))
            print(f"{symbol}: not in targets, closing {current} shares")
            submit_plain_market(trading_client, symbol, qty, side)